hpcc-systems/Visualization

widgets/src/common/TextBox.js
=> Updated text in TextBox Widget would not display.

widgets/src/graph/Edge.js
=> Add weight and dashed support to graph edges.

widgets/src/common/SVGWidget.js, widgets/src/common/Widget.js
=> Make resize method public.

widgets/src/graph/Graph.js
=> Graphs - Allow user to disable dragging of nodes.

widgets/src/graph/Graph.js, widgets/src/graph/GraphData.js, widgets/src/graph/GraphLayouts.js
=> Graph Widget:  Add support for subgraph layouts (hierarchy layout only).

widgets/src/marshaller/Graph.js
=> GH-142 Expose serialize / deserialize methods.

demos/test.html, widgets/src/c3/Bar.js, widgets/src/c3/Donut.js, widgets/src/chart/MultiChartSurface.js
=> GH-144 Add C3 Donut and Bar charts

widgets/src/graph/Graph.js
Add optional transitions.
Allow smaller graphs.
Add more getBounds options.
Zoom to fit is now 100% (previously 90%).
Prevent auto zoom after layout.
Conflicts:
widgets/src/graph/Graph.js
=> Graph Widget Zoom Tweaks:

build.sh, widgets/src/graph/Graph.js, widgets/src/graph/GraphData.js
Add multi-select support.
Add clear method.
Allow zooming while over a node.
Make edge transitions optional.
=> More support for ECL Watch Graphs:

widgets/src/other/Table.js
=> GH-155 Table content does not refresh correctly after a call to "data"

widgets/src/chart/Bubble.js, widgets/src/common/Widget.js
=> GH-154 Bubble chart corrupts underlying data.

widgets/src/chart/MultiChart.js, widgets/src/chart/MultiChartSurface.js, widgets/src/common/Surface.js, widgets/src/common/Widget.js
Refactor visibility
Fixes #163
=> GH-163 Encapsulate Multi Chart out of MultiChartSurface

widgets/src/graph/Graph.js, widgets/src/other/Bag.js
=> GH-162 Move Selection Bag out of Graph

README.md, demos/dermatology.html, demos/test.html, widgets/src/chart/MultiChartSurface.js, widgets/src/common/FAChar.js, widgets/src/common/Icon.js, widgets/src/common/List.js, widgets/src/common/Menu.js, widgets/src/common/ResizeSurface.js, widgets/src/common/SVGWidget.js, widgets/src/common/Shape.js, widgets/src/common/Surface.css, widgets/src/common/Surface.js, widgets/src/common/Text.js, widgets/src/common/TextBox.js, widgets/src/common/Widget.js, widgets/src/graph/Edge.js
=> GH-143 Add support for Discoverable/Serialize/Deserialize

widgets/src/marshaller/HipieDDL.js
=> Special case Graph Double Click for RAMPs Phase I

build.sh, util/build.js
=> GH-166 Allow build folder to be optionally overridden

widgets/src/chart/MultiChartSurface.js, widgets/src/common/Surface.js
=> Content hiding code was in the wrong place.

widgets/src/common/Surface.css, widgets/src/common/Surface.js, widgets/src/common/Widget.js
(the menu is still displayed if present)
=> Add ability to turn on and off the title bar

demos/dashboard/index2.html
=> Fix index2.html

widgets/src/other/ISlider.js
=> GH-179 Add default click handler for Slider/Range

widgets/src/c3/Common.js, widgets/src/c3/Donut.js, widgets/src/c3/Pie.js, widgets/src/chart/I2DChart.js
=> Add C3 Click Support.

demos/dermatology.html, widgets/src/common/FAChar.js, widgets/src/common/Shape.js, widgets/src/common/Text.js, widgets/src/graph/Graph.js
Minor fix dermatology HTML.
Remove "class" from inner shape.
Move Font Family into Text Widget.
=> Make subgraph work with ECL Watch again

demos/dermatology.html, widgets/src/c3/Area.js, widgets/src/c3/Column.js, widgets/src/c3/Common.js, widgets/src/c3/Common2D.js, widgets/src/c3/Donut.js, widgets/src/c3/Gauge.js, widgets/src/c3/Line.js, widgets/src/c3/Pie.js, widgets/src/c3/Scatter.js, widgets/src/c3/Step.js, widgets/src/chart/I1DChart.js
=> Add C3_Gauge.

widgets/src/common/ResizeSurface.js
=> GH-172 Prevent negative sizes during surface resize.

widgets/src/google/Bar.js
=> Remove Palatte reference from google bar chart

demos/dermatology.html, demos/test.css, widgets/config.js, widgets/lib/requirejs/plugins/text.js
=> Display widget source code on dermatology page.

widgets/src/google/Bar.js, widgets/src/google/Column.js, widgets/src/google/Common.js, widgets/src/google/Line.js, widgets/src/google/Pie.js
@GordonSmith @jbrundage @gururx 
Please review
=> Adds palette to google charts

widgets/src/marshaller/Graph.js, widgets/src/marshaller/HipieDDL.js
=> GH-211 Use visualization title if it exists

widgets/src/tree/CirclePacking.js, widgets/src/tree/Dendrogram.js, widgets/src/tree/SunburstPartition.js
Add tooltips to tree visualizations.
=> Add missing click support for tree visualizations.

demos/dermatology.html, widgets/lib/c3/c3.css, widgets/lib/c3/c3.js, widgets/src/c3/Area.js, widgets/src/c3/Column.js, widgets/src/c3/Common.js, widgets/src/c3/CommonND.js, widgets/src/c3/Line.js, widgets/src/c3/Scatter.js, widgets/src/c3/Step.js
Add support for subchart
Add support for different x-axis types.
Common up similar code.
=> Upgrade to C3 Latest.

demos/dermatology.html
=> Minor browser incompatibility.

demos/dermatology.html, widgets/src/common/FAChar.js, widgets/src/common/Icon.js, widgets/src/common/ResizeSurface.js, widgets/src/common/Shape.js, widgets/src/common/Text.js, widgets/src/common/TextBox.js, widgets/src/common/Widget.js, widgets/src/graph/Vertex.js, widgets/src/other/Persist.js
=> Publish properties for text, faChar, textbox, shape, icon and Vertex

demos/dermatology.html, widgets/src/common/FAChar.css, widgets/src/common/FAChar.js, widgets/src/common/Icon.js, widgets/src/common/Menu.js, widgets/src/common/Shape.css, widgets/src/common/Shape.js, widgets/src/common/Surface.js, widgets/src/common/Text.css, widgets/src/common/Text.js, widgets/src/common/TextBox.js, widgets/src/common/Widget.js, widgets/src/graph/Vertex.js, widgets/src/other/Persist.js
Add tooltip to Icon
Allow use to select default widget in dermatology.
Add new publish type "Array".
=> Add annotation support to Graph Vertices.

widgets/src/tree/Dendrogram.js
=> Dendrogram Bad Merge

widgets/src/common/Widget.js
=> Sync overlay scale with Graph Control

widgets/src/common/SVGWidget.js, widgets/src/common/Surface.js, widgets/src/graph/Graph.js
=> Widgets which contain other widgets did not clean up correctly.

demos/dashboard/app/Main.js, demos/dashboard/app/tpl/Main.html, widgets/src/marshaller/Graph.js
=> Make Graph Marshaller a Widget

widgets/src/chart/MultiChart.js, widgets/src/chart/MultiChartSurface.js, widgets/src/common/Surface.js
=> Serialized MultiChart

demos/dashboard/index2.html, demos/graph/index.html, demos/test.html, widgets/src/common/FAChar.css, widgets/src/common/FAChar.js, widgets/src/common/Icon.css, widgets/src/common/Icon.js, widgets/src/common/Menu.js, widgets/src/common/Shape.js, widgets/src/common/Surface.js, widgets/src/common/Text.js, widgets/src/common/TextBox.js, widgets/src/common/Widget.js, widgets/src/map/Choropleth.js, widgets/src/map/ChoroplethCounties.js, widgets/src/map/ChoroplethCountries.js, widgets/src/map/ChoroplethStates.js, widgets/src/marshaller/HipieDDL.js, widgets/src/other/Persist.js, widgets/src/tree/SunburstPartition.js
=> Fix default value handling (and stylesheets)

widgets/src/google/Bar.js, widgets/src/google/Column.js, widgets/src/google/Common.js, widgets/src/google/Pie.js
=> Refactor some of google charts published properties.

widgets/config.js, widgets/lib/crossfilter/LICENSE, widgets/lib/crossfilter/crossfilter.js
=> Add third party crossfilter

widgets/src/c3/Common.js
=> Publish Legend Position.

widgets/src/tree/SunburstPartition.js
=> Sunburst not resizing.

widgets/src/tree/SunburstPartition.js
Conflicts:
widgets/src/tree/SunburstPartition.js
=> Sunburst Double Click Issues

widgets/src/marshaller/HipieDDL.js
=> Sorting should fallback to lowercase field names if needed.

widgets/src/c3/CommonND.js
=> Fixes double function declaration

widgets/src/common/HTMLWidget.js
=> HTML Widgets Didn't cleanup correctly on exit.

widgets/src/common/Text.js
=> Workaround for  https://bugzilla.mozilla.org/show_bug.cgi?id=612118

widgets/src/common/Surface.js
=> Icon not being hidden on initial display.

widgets/src/google/Line.js
=> Fixes typo in google/Line

widgets/src/marshaller/Graph.js
=> Restore marshaller layout on load.

widgets/src/chart/Column.js
@jbrundage @GordonSmith - Please review
=> Adds color palette to D3 Column

widgets/src/marshaller/HipieDDL.js
=> SYMP_AVE_HACK

widgets/src/common/Surface.js
=> Hidden Surface Icon sometimes displays

widgets/src/map/ChoroplethCountries.js
@GordonSmith @jbrundage
Please Review 
=> Adds Countries Choropleth testData

widgets/src/common/SVGWidget.js, widgets/src/common/Widget.js
Add ability to monitor a widget for property changes.
=> Property watch

widgets/src/common/HTMLWidget.js, widgets/src/common/SVGWidget.js, widgets/src/common/Widget.js, widgets/src/other/Table.js
Refactor and improve widget resizing, specifically the HTML Widget.
=> Widget Resize Tweaks

widgets/src/graph/Graph.js
Minor fixes for zoom to fit transition.
Fix for mouse over highlight.
=> Graph Transitions

widgets/src/marshaller/Graph.js, widgets/src/marshaller/HipieDDL.js, widgets/src/other/Persist.js, widgets/src/other/PropertyEditor.js
Refactored persist to make recursive serialization work.
Added initial support for marshaller serialization support.
=> Persist Refactor

demos/dermatology.html, demos/graph/css/style.css, widgets/config.js, widgets/lib/lodash/LICENSE.txt, widgets/lib/lodash/lodash.js, widgets/src/layout/Cell.js, widgets/src/layout/Grid.css, widgets/src/layout/Grid.js, widgets/src/layout/Surface.css, widgets/src/layout/Surface.js, widgets/src/marshaller/HTML.js
Add HTML Surface
Add HTML Grid / Cell
Update HTML Marshaller to use new Grid Layout
Update dermatology test page to use new Grid.
=> Grid Layout

widgets/src/other/IWordCloud.js, widgets/src/other/WordCloud.js
Publish word cloud properties.
Fix delay loading of library.
=> WordCloud Publish

demos/test.html, widgets/src/other/Slider.js
=> Publish Slider Properties

widgets/src/marshaller/Graph.js
=> Multichart regression in Graph Marshaller

widgets/src/other/Comms.js
=> Add support for WsWorkunits/WUGetStats

demos/graph/index.html, widgets/src/graph/Graph.js, widgets/src/other/Bag.js
Allow zoomTo(all|width|selection|100%)
Fixes #265
=> GH-265 Simplify "Zoom To" options

widgets/src/graph/Graph.css, widgets/src/graph/Graph.js, widgets/src/other/Bag.js
Shift + Drag to start new selection.
Ctrl + Shift + Drag to append to current selection.
Fixes #264
=> Drag to select

widgets/src/common/ResizeSurface.js, widgets/src/graph/Graph.js
Disable surface resize if dragging is disabled.
Fixes #260
=> GH-260 Optionally Disable Surface Resize

widgets/src/marshaller/HipieDDL.js
The previous request is getting blanked out on every fetchData call.
=> Cached Request Issue

widgets/src/common/SVGWidget.js, widgets/src/tree/Dendrogram.js
Add support for different SVGWidget origin positions.
Update Dendrogram to render at 0,0 origin.
=> SVGWidget Position Origin

demos/test.html, widgets/src/chart/Bubble.js, widgets/src/chart/XYAxis.js, widgets/src/common/SVGWidget.js, widgets/src/common/Widget.js
Render charts based on the origin.
Allow user to limit which test to run.
=> Chart Origin Positioning

demos/dermatology.html, widgets/src/google/Area.js, widgets/src/google/Bar.js, widgets/src/google/Column.js, widgets/src/google/Common.js, widgets/src/google/Common2D.js, widgets/src/google/CommonND.js, widgets/src/google/Line.js, widgets/src/google/Pie.js
@GordonSmith @jbrundage @gururx 
This is 2 PRs merged (Google Area Chart & Publish Params) ... please review
=> Adds Google Area and more publish params

widgets/src/tree/Dendrogram.js
=> Adds Orientation Change to Dendrogram

widgets/src/marshaller/HipieDDL.js
Update HipieDDL.js to use the same relative path scheme as the rest of the
framework.
=> Require calls inconsistent

src/other/Paginator.css, src/other/Paginator.js, src/other/Table.js
=> Adds Pagination widget and modifies Table widget (NEW PR)

demos/test-no-amd.html
=> GH-310 Add non-AMD test page.

src/common/Widget.js
Add specific support for Word-Cloud non AMD support.
Fixes #307
=> GH-307 Word-Cloud Require Support

src/google/Common.js
@GordonSmith Please Review ... 
=> Changes Google Background Color Default to Transparent

src/other/Paginator.js, src/other/Table.js
@GordonSmith Please Review & Merge
=> Broken Pagination (FIX)

demos/test-no-amd.html, src/c3chart/Area.js
=> Fix c3chart/Area and usages of c3chart in demos/test-no-amd.html

bower.json, demos/dermatology.html, gulpfile.js, src/amchart/Area.js, src/amchart/Bar.js, src/amchart/Bubble.js, src/amchart/Candle.js, src/amchart/CommonFunnel.js, src/amchart/CommonRadar.js, src/amchart/CommonSerial.js, src/amchart/CommonXY.js, src/amchart/FloatingColumn.js, src/amchart/Funnel.js, src/amchart/Gauge.js, src/amchart/Line.js, src/amchart/Pie.js, src/amchart/Polar.js, src/amchart/Pyramid.js, src/amchart/Scatter.js, src/config.js
@GordonSmith @jbrundage @dtsnell4 Please Review
=> Adds AmCharts

widgets/src/chart/MultiChart.js, widgets/src/marshaller/HipieDDL.js, widgets/src/other/Persist.js
Fix regression introduced with the UMD re-factoring.
Fixes #320
=> GH-320 Dynamic Files + Marshaller

demos/dermatology.html, src/layout/Cell.js, src/layout/Grid.css, src/layout/Grid.js, src/layout/Surface.js
Allow user to drag and drop widgets on the Grid Layout.
=> Grid Layout Visual Editor

src/c3chart/Area.js, src/c3chart/Column.js, src/c3chart/Common.js, src/c3chart/CommonND.js, src/c3chart/Donut.js, src/c3chart/Gauge.js, src/c3chart/Line.js, src/c3chart/Pie.js
=> Adds C3 Publish Params and .Load Refactor

src/c3chart/Area.js, src/c3chart/Common.js, src/c3chart/CommonND.js, src/c3chart/Line.js
=> C3 Fix & more publish params

demos/dermatology.html, src/layout/Cell.js, src/layout/Grid.js, src/marshaller/HTML.js
Dermatology serialization tests stopped working due to setContent not returning
"this".
Drag handle was not displaying on the Grid Layout when in design mode.
Fixes #361
=> GH-361 Serialization Test Broken

src/marshaller/Graph.js, src/marshaller/HTML.js, src/marshaller/HipieDDL.js
At support for events section in DDL.
(Not all widgets will support all events)
Fixes #332
=> GH-332 Add marshaller support for DDL Events

src/other/Persist.js
Only serialize the actual class of the widget.
Fixes GH-369
=> GH-369 Serialization Issue

src/other/Comms.js
Add timeout to comms JSONP calls.
=> JSONP Timeout

src/common/Widget.js, src/other/PropertyEditor.js
Replace __proto__ with Object.getPrototypeOf
Fixes GH-373
=> GH-373 IE10 Regression

src/tree/Dendrogram.js
One of the lint fixes broke the Dendrogram rendering.
Fixes GH-383
=> GH-383 Dendrogram Regression

src/chart/MultiChart.js
=> GH-380 Add amCharts to MultiChart

.jshintrc, src/chart/MultiChart.js, src/marshaller/HipieDDL.js, src/other/PropertyEditor.js, src/other/WordCloud.js
=> Lint Tweaks

apps/legacyDash.html
=> Legacy Dash Regression

demos/test-no-amd.html, demos/test.html, src/amchart/Area.js, src/amchart/Bar.js, src/amchart/Candle.js, src/amchart/CommonFunnel.js, src/amchart/CommonRadar.js, src/amchart/CommonSerial.js, src/amchart/CommonXY.js, src/amchart/FloatingColumn.js, src/amchart/Gauge.js, src/amchart/Line.js, src/amchart/Pie.js, src/amchart/Scatter.js, src/c3chart/Common2D.js
@jbrundage @dtsnell4 @GordonSmith Please Review
=> Changes to Color Palette and Params

bower.json
=> Fix script order to benefit apps that auto-inject Bower scripts

src/other/Slider.css
Removed font-family and font-size.
=> Invalid Slider Styles

src/graph/Graph.js
Publish the "allowDragging" method.
Fixes GH-403
=> GH-403 Disable Dragging of Vertices

src/amchart/Bar.js, src/amchart/Pie.js, src/api/INDChart.js, src/chart/Bubble.js, src/chart/Column.js, src/chart/Line.js, src/chart/MultiChart.js, src/chart/Pie.js, src/google/Common.js, src/google/Line.js, src/google/Pie.js, src/layout/Surface.js, src/map/Choropleth.js, src/tree/CirclePacking.js, src/tree/Dendrogram.js, src/tree/SunburstPartition.js
@GordonSmith @jbrundage Please Review
=> changes to partially sync svn - rebased onto 1.0.2

src/amchart/Bar.js, src/amchart/Pie.js, src/api/INDChart.js, src/chart/Bubble.js, src/chart/Column.js, src/chart/Line.js, src/chart/MultiChart.js, src/chart/Pie.js, src/google/Common.js, src/google/Line.js, src/google/Pie.js, src/layout/Surface.js, src/map/Choropleth.js, src/tree/CirclePacking.js, src/tree/Dendrogram.js, src/tree/SunburstPartition.js
@jbrundage @GordonSmith Please Review
=> changes to partially sync svn

demos/dermatology.html, src/layout/Grid.js, src/layout/Surface.js
Revert bad merge from https://github.com/GordonSmith/Visualization/commit/2704ac79c39ce6fd30b64c67db9e712351bfafce#diff-f2cc9bb8a08091bed26f9b2b2998dcc0.
Fixes GH-413
=> GH-413 Publish Cell Padding

src/other/Paginator.js, src/other/Table.js
@GordonSmith @jbrundage @anmoljagetia Please Review
=> Adds Auto ItemsPerPage (TABLE/PAGINATOR) GH-145

demos/dermatology.html, demos/graph/index.html, demos/test-no-amd.html, demos/test.html, src/graph/Edge.js, src/graph/Graph.css, src/graph/Graph.js, src/graph/GraphData.js, src/graph/GraphLayouts.js, src/marshaller/Graph.js, src/marshaller/HipieDDL.js
Publish existing properties.
Fixes GH-419
=> GH-419 Add Multigraph Support

src/other/Table.css, src/other/Table.js
=> Add Shift+Click support to Table

src/c3chart/Common1D.js, src/c3chart/Common2D.js, src/c3chart/Gauge.js
Fixes Common JS Update call order/c3 donut hole display
Fixes Gauge Palette issue
Fixes 433
@GordonSmith @dtsnell4 @jbrundage Please Review
=> GH-433 C3 Fix

src/chart/Column.js, src/chart/Line.js, src/chart/XYAxis.js
@GordonSmith @mlzummo Please review.
Signed-off-by: Anmol Jagetia anmoljagetia@gmail.com
=> Adds orientation selection

src/c3chart/Common.js, src/c3chart/CommonND.js
=> GH-444 C3 Pie chart is not unloading previous data

src/amchart/CommonFunnel.js, src/amchart/Pyramid.js
@GordonSmith @jbrundage Please Review
Fixes #430
=> GH-430 Replaces default label position and sets automargin true

src/common/Icon.js, src/common/Surface.css, src/common/Surface.js
@GordonSmith @dtsnell4 @anmoljagetia 
Please Review
=> Adds SVG Surface Buttons

src/common/Surface.js
=> GH-429 Surface Right/Bottom is getting clipped

src/common/Surface.js
Reverts hpcc-systems/Visualization#460
Pulled to wrong branch.
=> Revert "GH-429 Surface Right/Bottom is getting clipped"

src/google/Common.js
Convert strings to numbers prior to data load.
Fixes GH-459
=> GH-459 Google requires Numeric values

src/amchart/FloatingColumn.js
=> Fixes Issue #474 AMChart Floating Column example HTML will not load

src/other/Slider.js
=> GH-456 Center slider correctly

gulpfile.js
=> Tagging would skip bower.json + package.json

demos/dermatology.html, src/common/Surface.css, src/common/Surface.js, src/layout/Surface.css, src/layout/Surface.js
@GordonSmith @dtsnell4 @jbrundage 
Please Review 
=> Adds HTML Surface Buttons

src/layout/Grid.js
=> Scale not resetting correctly after design mode is invoked.

src/layout/Cell.js, src/layout/Grid.css, src/layout/Grid.js
@GordonSmith @mlzummo @dtsnell4 Please Review
=> Enhances layout/Grid.js designMode with more intuitive dragging behavior

src/form/Form.js, src/form/Input.js, src/marshaller/HTML.js, src/marshaller/HipieDDL.js
Add form support to the Marshaller
Fixes GH-239
=> GH-239 Form Support

src/form/Form.js
=> Fixes Form Input Clear

src/marshaller/HTML.js, src/marshaller/HipieDDL.js
=> Graph Annotations

src/chart/Column.js, src/chart/XYAxis.js
Add support for linear scale.
Add support for time scale.
Publish "sample" data property.
Fixes GH-508
=> GH-508  XAxis Scales

src/layout/Surface.js
=> Surface.render needs to return "this".

src/other/Comms.js
=> Fixes Comms Global NON-AMD Declaration

src/other/Table.js
=> Table should not attempt to display Objects

src/graph/Graph.js
=> Graph highlight functions should return this.

src/chart/Column.js, src/chart/Line.js, src/chart/Scatter.js, src/chart/XYAxis.js
=> Chart not persisting data correctly.

src/marshaller/HipieDDL.js
=> Form submit not resolving datasources correctly.

src/form/Input.js
Values setting/getting was not working in Chrome.
=> Add "date" as an input type.

src/amchart/Area.js, src/amchart/Bar.js, src/amchart/Bubble.js, src/amchart/Candle.js, src/amchart/FloatingColumn.js, src/amchart/Funnel.js, src/amchart/Gauge.js, src/amchart/Line.js, src/amchart/Pie.js, src/amchart/Polar.js, src/amchart/Pyramid.js, src/amchart/Scatter.js
=> Issue #536 - AMCharts this._class updated to new implementation with .prototype.class.

src/other/Comms.js
Add generic REST connection.
Add another roxie path parser.
=> New Comms Connection

demos/dermatology.html, src/chart/Area.js, src/chart/MultiChart.js, src/chart/Scatter.js, src/chart/Step.js, src/chart/XYAxis.js, src/common/Widget.js
Use scatter as basis of Line, Area and Step.
=> Scatter Refactor

src/other/Table.js
=> Table selection does not refresh correctly.

src/map/GMap.js
Improve marker handling.
Recenter USA
=> Google Map Tweaks

src/chart/XYAxis.js
Conflicts:
src/chart/XYAxis.js
=> Adds pow and log to Value Axis

src/chart/XYAxis.css, src/chart/XYAxis.js
=> XY Axis Reset Selection

demos/dermatology.html, src/common/WidgetArray.js, src/form/Form.js
Add option to drop empty fields from values() call.
=> Allow inputs to be placed side by side.

demos/marshaller/index.html, src/marshaller/HipieDDL.js
First load should only refresh items with no filters.
Added LegacyDash page which works with GitHub.
=> Marshaller First Load and Filters

src/chart/Column.js, src/chart/Scatter.js, src/chart/XYAxis.css, src/chart/XYAxis.js
Add "time" as an option to YAxis.
Fixes #509
=> GH-509 Additional YAxis Types

src/google/Common.js
@jbrundage @dtsnell4 @GordonSmith Please Review
=> Fixes google typo

apps/SampleSite/config.js, apps/SampleSite/sample_html/config.js, src/config.js
@GordonSmith @dtsnell4 @dtsnell4 Please Review
=> Adds HTTPS & rawgit cdn support to config.js

src/form/Form.js
=> GH-587 Form enter should submit

demos/dermatology.html, src/layout/Tabbed.css, src/layout/Tabbed.js
Basic layout of tabs and content panels
Fixes GH-518
=> GH-518 Add Tabbed

apps/SampleSite/grid.html, src/layout/Grid.css, src/layout/Grid.js
Fixes GH-607
This PR replaces GH-608
=> GH-607 Grid designMode now displays grid-drop-target

src/chart/MultiChart.js, src/chart/MultiChartSurface.js, src/common/Surface.js, src/common/Widget.js, src/other/Persist.js, src/other/PropertyEditor.js, src/other/ThemeEditor.js
MultiChartSurface and MultiChart are not persisting correctly
Fixes GH-612
=> GH-612 MultiChart Persist Issues

src/amchart/CommonFunnel.js, src/amchart/CommonRadar.js, src/amchart/CommonSerial.js, src/amchart/CommonXY.js, src/amchart/Pie.js, src/amchart/Polar.js
@GordonSmith Please Re-Review
Add click events to various AM Charts
Fixes GH-537
=> GH-537 AM Chart Click Events

src/marshaller/HipieDDL.js
@GordonSmith 
Adds support for form default value in DDL
Fixes #590
=> GH-590 Form Default Value

src/layout/Tabbed.js
Serialization is failing due to overzealous re-factoring.
=> Tabbed Layout Serialization

demos/dermatology.html, src/common/Widget.js
=> Allow widget params to be passed into dermatology demo URL.

demos/dermatology.html, demos/test.html, src/chart/MultiChart.js, src/chart/MultiChartSurface.js, src/chart/Summary.css, src/chart/Summary.js, src/common/HTMLWidget.js, src/common/SVGWidget.js, src/common/Widget.js, src/graph/Graph.js, src/map/GMap.js
=> Summary Widget

demos/dermatology.html, src/layout/AbsoluteSurface.css, src/layout/AbsoluteSurface.js, src/layout/Layered.css, src/layout/Layered.js
Added AbsoluteSurface
Fixes GH-646
=> GH-646 Layered Layout

src/other/Comms.js
Convert numbers to Numbers.
Trim strings.
Fixes GH-588
Fixes GH-585
=> Fix ESP Response

src/common/Surface.js
@GordonSmith @dtsnell4 @jbrundage
Fixes GH-599
Please Review
Fixes IE & Firefox click event of surface buttons issue
Fixes GH-599
Signed-off-by: Mathew Zummo mzummo@gmail.com
=> GH-599 Surface Button Fix (click event)

src/common/Surface.js
Surface Button Container is failing on the test page.
=> SVG Surface Button Issue

src/marshaller/Graph.js
Graph Marshaller is failing in master branch.
=> Graph Marshaller Regression

demos/dermatology.html, src/common/Widget.js
@GordonSmith @dtsnell4 @jbrundage 
Please Review
=> Adds debug option to require config for global obj/array of widgets

src/common/Surface.js
=> Fixes Lint Failure in Surface.js

src/graph/Edge.js, src/other/MorphText.js, test/widgets.js
=> Test that testData exists for all widgets

src/amchart/Bar.js, src/amchart/FloatingColumn.js, src/amchart/Pie.js
@GordonSmith @arjunachala 
Please Review
Changes AmCharts to default to 2D (no depth)
Fixes GH-610
=> GH-610 AmChart 2D

src/common/ResizeSurface.js, test/widgets.js
=> Test for valid class names

test/widgets.js
=> Adds Unit Test for useClonePalette param

demos/test.html, package.json, src/common/Menu.js, src/common/Widget.js, src/graph/Edge.js, src/graph/Graph.js, src/graph/Vertex.js, src/map/GMap.js, src/other/MorphText.js, test/runner.html, test/widgets.js
Test rendering each widget with a call to testData.
MorphText:  Added testData method.
Menu:  Fixed invalid shape property.
Widget:  Allow html-color of type null or ""
Edge:  Fix error on empty render.
Graph:  Allow layout of type "None".
Vertex:  Fixed color typo.
GMap:  Fixed Layout typo.
=> Test:  Render widget with testData

.travis.yml, gulpfile.js, package.json, test/runner.css, test/runner_build.html, test/runner_rawgit.html, test/widgets.js
=> Add rawgit support for test page

apps/SampleSite/PopupSamples/config.js, apps/SampleSite/config.js, apps/SampleSite/sample_html/config.js, demos/test.html, gulpfile.js, src/amchart/CommonFunnel.js, src/amchart/CommonRadar.js, src/amchart/CommonSerial.js, src/amchart/CommonXY.js, src/amchart/Gauge.js, src/amchart/Pie.js, src/config.js
adds changes for amcharts images path
changes to gulp for amcharts
=> adds changes for amcharts images path & gulp build

demos/test-no-amd.html, src/chart/Scatter.js, src/common/Widget.js, src/form/Slider.js, src/other/ThemeEditor.js
Fixes scatter and slider non-amd build issues
=> GH-680 Fixes test-no-amd.html

bower.json
=> [GH-706] Add hpcc-viz-form.min.js to bower.json

src/amchart/CommonFunnel.js, src/amchart/CommonRadar.js, src/amchart/CommonSerial.js, src/amchart/CommonXY.js, src/amchart/Gauge.js, src/amchart/Pie.js, src/other/ThemeEditor.js
@GordonSmith Please Review 
it seems that the dist version didn't like it when the property was present
=> Fixes oversight in NON-AMD version with amcharts img directory resolution

src/form/Slider.js
=> GH-713 Slider Events not firing during play

demos/dermatology.html, src/layout/Popup.js
Signed-off-by: <Dan.Snell@lexisnexis.com>
=> Popup Widget (Issue #516)

bower.json, package.json, src/config.js, test/runner.html
=> [GH-712] Move RequireJS deps to package.json, fix build and test

src/form/Slider.js, test/anmol.js, test/runner.html
This PR Adds tests that test all the functionality of the Slider widget. I am not squashing the commits as of it, because this is still a work in progress.
@GordonSmith Please review!
=> Adds tests for Slider Widget

apps/SampleSite/PopupSamples/config.js, apps/SampleSite/config.js, apps/SampleSite/sample_html/config.js, src/config.js
=> Fixes rawgit URL for amchart images

src/common/Utility.js, test/utility.js
@GordonSmith @jbrundage @dtsnell4 
Please Review
=> Adds Utility Obj

src/common/HTMLWidget.js, src/common/SVGWidget.js, src/common/Widget.js, src/layout/AbsoluteSurface.css, src/layout/AbsoluteSurface.js, src/layout/Layered.css, src/layout/Layered.js
=> AbsoluteSurface Fixes

src/other/Table.js
Fix table pagination
Fixes GH-705
=> GH-705 Fix table pagination

src/graph/Edge.js
=> Fix edge unit test console error.

demos/test.html, src/common/Surface.js
=> Surface content positioning is incorrect for HTML content.

demos/test-no-amd.html, src/other/ThemeEditor.js
=> Adds themeeditor console log fix and non-amd-test fixes

src/common/Widget.js, src/layout/Surface.js, src/layout/Tabbed.js
Surface needs to check for modified on some properties.
=> Add support for show/hide tabs on tabbed layout.

src/api/ITooltip.js, src/chart/Bubble.js, src/chart/Column.js, src/chart/Pie.js, src/chart/Scatter.js, src/chart/XYAxis.js, src/map/Choropleth.js, src/map/ChoroplethCounties.js, src/map/ChoroplethCountries.js, src/map/ChoroplethStates.js
Add Tooltips to existing HPCC Charts
Fixes GH-584
Signed-off-by: <Dan.Snell@lexisnexis.com>
=> GH-584 D3 Tooltip Widget

src/other/Table.css, src/other/Table.js
Adds functionality for a fixed table header and fixed first column for the table widget.
Fixes GH-542
Signed-off-by: Dan Snell <dan.snell@lexisnexis.com>
=> GH-542 Fixed table header and first column

src/chart/Scatter.js, src/form/Slider.js
=> Backport some non amd fixes from master.

demos/test-no-amd.html, src/form/Input.js, src/google/Scatter.js, src/google/Timeline.js, src/google/TreeMap.js, src/layout/Border.js, src/layout/Grid.js, src/layout/Surface.js, src/other/Table.js
New table doesn't work in tooltip.
Circular reference during build.
Remove "noise" from Border.testData.
Minor click issue.
Minor lint issue.
=> Up-merge conflicts

src/other/Persist.js
=> Persist regression - syntax error.

apps/SampleSite/config.js, apps/SampleSite/sample_html/config.js, apps/SampleSite/sample_html/other/HeatMap.html, bower.json, demos/dermatology.html, demos/test-no-amd.html, demos/test.html, gulpfile.js, src/common/CanvasWidget.js, src/config.js, src/marshaller/HipieDDL.js, src/other/HeatMap.js, test/runner_build_nonamd.html, test/widgets.js
=> Add new heatmap and canvas widgets

src/chart/Column.js
=> Add opacity to stacked columns.

src/marshaller/HTML.js, src/marshaller/HipieDDL.js, src/other/Persist.js
=> COMMS Data Loaded Check and Persist walk function change

demos/dermatology.html, demos/test-no-amd.html, gulpfile.js, src/layout/AbsoluteSurface.js, src/layout/Layered.js, src/layout/Popup.js, src/layout/Tabbed.js, src/map/Choropleth.js, src/map/ChoroplethStatesHeat.js, src/map/GMap.css, src/map/GMap.js, src/map/GMapGraph.js, src/map/GMapHeat.js, src/map/TestHeatMap.js, test/widgets.js
=> Refactor Maps

src/layout/Border.js
=> Fixes #781 - Border layout now stretches to fit SVG containers

src/common/SVGWidget.js, src/common/Surface.js, src/common/Utility.js, src/common/Widget.js, src/layout/Layered.css, src/other/Table.js, test/anmol.js, test/widgets.js
=> Fix sizing of HTML Widget in SVG Widget.

src/other/Comms.js, src/other/ThemeEditor.js
=> LocalStorage uses are now limited to getItem/setItem/removeItem

src/other/Table.css
Add border-spacing and border-collapse properties to Table.css.
Fixes GH-793
=> GH-793 Table Widget Border Spacing

apps/SampleSite/legend.html, demos/dermatology.html, src/other/Legend.css, src/other/Legend.js, src/other/Table.js
Fixes #523
Fixes #524
Fixes #578
=> Adds Legend Widget for both Ordinal and Rainbow

demos/HelloWorld/index.html, demos/marshaller/index.html, src/layout/Tabbed.css, src/marshaller/Graph.js, src/marshaller/HTML.js, src/marshaller/HipieDDL.js
=> Allow events across dashboards.

src/other/Paginator.css, src/other/Paginator.js, src/other/Table.js
@GordonSmith @dtsnell4 Please Review
Adds new publish parameter autoCalcIPP
Changes Paginator so that its fixed height
Adds new features to Paginator (jump to page)
Fixes GH-771
=> GH-771 TABLE (AUTO CALC ITEMS PER PAGE) AND PAGINATOR UPDATE

src/other/Table.js
Fixes #808
@GordonSmith @dtsnell4 Please review
https://rawgit.com/jbrundage/Visualization/candidate-1.6.0/demos/dermatology.html?src/other/Table
=> GH-808 Table widget can display numbers again

src/other/Table.js
Fixes a bug where the the table header disappears when the first column is turned off.
=> Table Widget Fixed First Column

src/layout/Grid.css, src/layout/Grid.js, src/other/PropertyEditor.js, test/runner_build_nonamd.html
SelectionBag is now utilized in layout/Grid to handle the selection of one or more Cells.
Fixes #662
https://rawgit.com/jbrundage/Visualization/GridLayout_meets_SelectionBag/demos/dermatology.html?src/layout/Grid&designMode=true
=> GH-662 Adds SelectionBag to Grid

src/common/HTMLWidget.js, src/marshaller/HipieDDL.js, src/other/Paginator.css, src/other/Paginator.js, src/other/Table.js
Adds new publish parameter autoCalcIPP
Changes Paginator so that its fixed height
Adds new features to Paginator (jump to page)
Fixes GH-771
=> GH-771 Table pagination fixed height

src/other/PropertyEditor.js
Excludes properties with no tag.
Fixes GH-822
=> GH-822 PropertyEditor ExcludeTags Issue

src/chart/XYAxis.js, src/common/Widget.js
=> GH-695 Tick String Formatting

src/c3chart/CommonND.js
Adding **yAxisTickFormat** to c3chart/CommonND
Fixes GH-836
@GordonSmith @mlzummo Please Review
=> GH-836 Adds Y-Axis Tick Formatting for C3 Charts

src/amchart/Area.js, src/amchart/Bar.js, src/amchart/Bubble.js, src/amchart/Candle.js, src/amchart/CommonRadar.js, src/amchart/CommonSerial.js, src/amchart/CommonXY.js, src/amchart/FloatingColumn.js, src/amchart/Funnel.js, src/amchart/Line.js, src/amchart/Pie.js, src/amchart/Polar.js, src/amchart/Pyramid.js, src/amchart/Scatter.js
Adds AMCHART BALLOON with same output formatting as HPCC Charts
Fixes GH-827
=> GH-827 Adds Amchart Balloon

src/common/Surface.js
Note:  C3 Legends are not being hidden
=> GH-806 Surface menu overlay issue

src/amchart/CommonRadar.js, src/amchart/CommonSerial.js, src/amchart/CommonXY.js
Adds Y-Axis tick formatting to Amcharts
Fixes GH-829
=> GH-829 Amcharts Axis Tick Formatting

demos/dermatology.html, src/common/Widget.js, src/layout/Surface.js, src/other/Persist.js
=> GH-844 Themes not resetting correctly

src/common/Surface.js, src/common/Widget.js, src/layout/AbsoluteSurface.js, src/layout/Border.js, src/layout/Grid.js, src/layout/Popup.js, src/layout/Surface.js, src/layout/Tabbed.js
Common up all async rendering into widget.
Fixes GH-841
=> GH-841 Tabbed ASync render

src/chart/MultiChart.js, src/layout/Tabbed.js, src/marshaller/HTML.js, src/marshaller/HipieDDL.js
=> GH-854 Deserializing a marshaller event issues

src/map/GMap.js, src/map/GMapGraph.js
Zoom to fit still expected old format.
Fixes GH-847
=> GH-847 Google map zoom to fit issue

src/chart/MultiChartSurface.js, src/marshaller/HipieDDL.js, src/marshaller/Tabbed.js, src/other/Comms.js, src/other/PropertyEditor.js, src/other/ThemeEditor.js
Revert HTML marshaller to be just a Grid.
Fixes GH-866
=> GH-866 Add tabbed marshaller

demos/dermatology.html, src/other/Table.css, src/other/Table.js
Fixes GH-797
@GordonSmith @dtsnell4 @mlzummo Please Review
https://rawgit.com/jbrundage/Visualization/TableColors_1.8.0/demos/dermatology.html?src/other/Table
=> GH-797 Adds table colors to the sample themes

src/layout/Border.js
Fixes GH-859
https://rawgit.com/jbrundage/Visualization/1.8.0_BorderEnhancements/demos/dermatology.html?src/layout/Border&leftShrinkWrap=true
Signed-off-by: Jay Brundage jaman.brundage@lexisnexis.com
=> GH-859 Adds Border ShrinkWrap params

src/graph/Graph.js
=> GH-873 Graph getNeighborMap corruption

src/other/Table.js
Adds a publish parameter that will show or hide the Table Widget's header if true or false.
Fixes GH-860
=> GH-860 Table Show-Hide Header

src/chart/MultiChartSurface.js, src/chart/Pie.js, src/common/ResizeSurface.js, src/common/Shape.js, src/common/Surface.js, src/map/Choropleth.js, src/other/Audio.js, src/other/MorphText.js
See https://github.com/hpcc-systems/Visualization/pull/596 for full list of comments.
=> GH-539 CONV_P - Adds publish params for already existing functions

src/layout/Grid.js
=> GH-883 Tidy Grid Class

src/other/Persist.js
=> GH-882 Implements Persist.propertyWalker filter

src/chart/Summary.css
=> GH-892 Summary layout issue

src/other/Paginator.js, src/other/Table.js
Re-implemented pagination calculations and div location.
Table:  Reset sort when new data is loaded.
Pagination:  Optionally set number of adjacent pages to show.
Fixes GH-895
=> GH-895 Table Pagination Regression

src/other/Table.js
Resetting the table data (.columns([]) and .data([]) ) would cause the widget to error.
Fixes GH-897
=> GH-897 Reset Table Data

npm-shrinkwrap.json
=> GH-921 clean-css 3.4.2 breaks the build environment

src/amchart/Pie.js
Supports "simple" and "multi"
Fixes GH-939
=> GH-939 Publish selectionMode to AM Chart PIE

src/other/Table.js
Changes the creation of the fixed Column from native Javascript to D3.js.  Also fixes highlighting of table rows when fixedColumns() is true and showHeader() is false.
Fixes GH-937, GH-936
=> GH-937 Setting Table Styles

src/other/Table.css, src/other/Table.js
=> GH-928 Add alternate line backgrounds to Table

src/chart/Column.js, src/chart/Scatter.js, src/chart/XYAxis.js
Prevent overlapping labels on the x-axis.
Three modes:  None, Stagger and Hide.
Fixes GH-933
=> GH-933 Overlapping axis labels

src/other/PropertyEditor.js
Fixes GH-948
Also fixes 'set' publish param type functionality when PropertyEditor is in 'By Param' mode.
https://rawgit.com/jbrundage/Visualization/GH-948-PE-MultiBug/demos/dermatology.html?src/chart/MultiChart
=> GH-948 Adds 'watch' use to PropertyEditor

src/other/Legend.js, src/other/Table.js, test/otherFactory.js
Fixes GH-900
https://rawgit.com/jbrundage/Visualization/GH-900-LegendCenter/demos/dermatology.html?src/other/Legend
=> GH-900 Adds Legend verticalAlignment

src/other/PropertyEditor.js
Fixes GH-953
@GordonSmith @dtsnell4 Please review
https://rawgit.com/jbrundage/Visualization/GH-953-PE-Cols-Data/demos/dermatology.html?src/chart/MultiChart
=> GH-953 Fixes PropEdit nested widget showData/Col

test/runner_build.html
Fixes console.log error in unitTestBuild
Fixes GH-967
=> GH-967 AMCHART CONSOLE LOG FIX

src/other/PropertyEditor.js
Fixes GH-950
@GordonSmith @dtsnell4 Please review
=> GH-950 Replaces matches with filter in PropEdit

demos/dermatology.html
=> Allow URL to specify which test to display.

src/form/Input.css, src/form/Input.js
Fixes GH-970
http://rawgit.com/jbrundage/Visualization/GH-970-PE-Color/demos/dermatology.html?src/layout/Surface
=> GH-970 Adds HTML5 color input to form/Input.js

src/amchart/CommonFunnel.js, src/amchart/CommonRadar.js, src/amchart/CommonSerial.js, src/amchart/Pie.js
=> GH_903 AmCharts Value Field Fix

src/layout/Grid.js
Fixes GH-884
@mlzummo @GordonSmith Please review
https://rawgit.com/jbrundage/Visualization/GH-884-GridCellBorders/demos/dermatology.html?src/layout/Grid&surfaceBorderWidth=4
=> GH-884 Adds surfaceBorderWidth to Grid

src/chart/XYAxis.css, src/chart/XYAxis.js, test/chartFactory.js
=> Adds XYAxis Label Rotation

demos/test-no-amd.html, src/google/Bar.js, src/google/Common.js, src/google/Line.js, src/google/Scatter.js, test/runner_build_nonamd.html
Reverts hpcc-systems/Visualization#927
=> Revert "GH-749 Add Second Y Axis to Google Charts"

src/form/Input.js
@GordonSmith @jbrundage Please Review
Fixes GH-1017
=> GH-1017 Fixes checkbox value

src/form/Input.js
=> GH-1023 Fixes select default value (cand 1.8)

src/form/Input.js
=> GH-1023 Fixes select default value (1.6.8)

src/amchart/Area.js, src/amchart/Bar.js, src/amchart/CommonFunnel.js, src/amchart/CommonRadar.js, src/amchart/CommonSerial.js, src/amchart/CommonXY.js, src/amchart/Line.js, src/amchart/Pie.js
changes - xAxisGridPosition: start
changes - grid alpha and axis line color
Fixes GH-768
=> AmCharts simple and multi selection via selectionColor PP and selectionmode()

src/layout/Cell.js, test/layoutFactory.js
Fixes GH-747
@GordonSmith @dtsnell4 @mlzummo I've added **indicateTheseIds** publish param to layout/Cell.js
It holds an array of DOM IDs and displays a div over each corresponding html element when the use hovers over the Cell.
https://rawgit.com/jbrundage/Visualization/GH-747-HoverIndicators/demos/dermatology.html?src/layout/Grid.hoverIndicator
=> GH-747 Adds Hover Indicators to layout/Cell.js

src/config.js
=> Potential Fix for require.js timeout issues

src/common/Widget.js
=> GH-915 Overwrite PP

src/form/Input.js
@GordonSmith @jbrundage @dtsnell4 - Please Review
Fixes console.log errors with property editor and html-colors being in form of "#f00" or ""
Fixes GH-1030
=> GH-1030 Fixes html-color form_Input 3 digit and ""

src/amchart/CommonFunnel.js, src/amchart/CommonRadar.js, src/amchart/CommonSerial.js, src/amchart/CommonXY.js, src/amchart/Gauge.js, src/amchart/Pie.js
Fixes console errors by changing null value params for fonts
Fixes GH-1042
=> GH-1042 Fix Amchart console errors

src/c3chart/Common.js, test/c3chartFactory.js
Fix C3 Bar Clipping
Fixes GH-1019
=> GH-1019 - Fix C3 Bar Clipping

demos/dermatology.html, src/amchart/Area.js, src/amchart/Bar.js, src/c3chart/Area.js, src/c3chart/Column.js, src/c3chart/Combo.js, src/google/Area.js, src/google/Bar.js, src/google/Column.js, test/DataFactory.js, test/c3chartFactory.js
Fixes GH-957
@mlzummo @dtsnell4 Please review
I added a more complex sample to show capabilities of the various combinations of chart types (We should probably do the same with the other libraries:
http://rawgit.com/jbrundage/Visualization/C3-ComboChart/demos/dermatology.html?src/c3chart/Combo
EDIT: Replaced sample URL with one that works
=> GH-957 Adds c3chart/Combo.js

src/google/Common.js, src/google/Timeline.js, src/google/TreeMap.js, test/DataFactory.js, test/googleFactory.js
Adds support that returns the row data, column and selected true/false when a row is clicked/selected.
Fixes GH-769
=> GH-769 Adds Simple Selection to Google Charts

src/common/Text.js, src/composite/MegaChart.js, src/layout/Border.js, src/other/Legend.js, src/other/Table.js, test/Factory.js, test/compositeFactory.js, test/widgets.js
Fixes GH-1028
Fixes GH-1027
http://rawgit.com/jbrundage/Visualization/MEGA_CHART_CLUSTER/demos/dermatology.html?src/cluster/MegaChart
=> GH-1028 Adds MegaChart widget

src/layout/Accordion.js, src/layout/Tabbed.js
Fixes GH-1060
@mlzummo @dtsnell4 Please review
http://rawgit.com/jbrundage/Visualization/NaN-2015-10-19/demos/dermatology.html?src/layout/Tabbed
=> GH-1060 Fixes Accordion and Tabbed NaN errors

.travis.yml, src/map/GMap.js
=> GH-1045 GMap Unit Tests failing on travis

apps/SampleSite/grid.html, src/map/GMap.js, test/runner_build_nonamd.html
=> Allow Http/Https dyanmic switching of loading gmap

demos/test-no-amd.html, gulpfile.js, test/runner_build_nonamd.html
MegaChart is not building correctly.
Fixes GH-1056
=> GH-1056 Non AMD Unit Test Failures

src/form/Input.js, test/DataFactory.js
@GordonSmith @jbrundage - Please Review
Removes incorrect input types
Adds new input types
Fixes GH-960
=> GH-960 Adds new input types

src/map/GMap.js
=> GH-1071 GMap Unit Tests Failing

test/formFactory.js
@GordonSmith @dtsnell4 @jbrundage 
=> Fixes form_Input console.log error for incorrect input type (UT)

src/google/Area.js, src/google/Bar.js, src/google/Column.js, src/google/Line.js, src/google/Scatter.js
Changes the publish param for axis formatting from "string" to "set".
Fixes GH-835
=> GH-835 Google Axis Ticks Formatting

src/amchart/CommonSerial.js, src/chart/XYAxis.js, test/amchartFactory.js, test/chartFactory.js
@GordonSmith @dtsnell4 @jbrundage Please Review
Question1 - does the sorting need to be applied to the Y Axis and is the data index 1 or 0 on that if so?
Question2 - does this need to be applied to C3 and Google?
Fixes AmChart & HPCC X-Axis Time
Fixes GH-1063
=> GH-1063 Fixes AmChart & HPCC X-Axis Time

src/common/Text.js
Fixes GH-1086
http://rawgit.com/jbrundage/Visualization/GH-1086-List/demos/dermatology.html?src/common/List
=> GH-1086 Text rotation offsets corrected

src/google/Timeline.js
Adds a timeFormat publish parameter so the developer can specify the time/date format of the data.
Fixes GH-887
=> GH-887 Google Timeline Time Parser

src/amchart/CommonFunnel.js, src/amchart/CommonRadar.js, src/amchart/CommonSerial.js, src/amchart/CommonXY.js, src/amchart/Gauge.js, src/amchart/Pie.js
@GordonSmith @jbrundage @dtsnell4 - Please Review
-Adds AmChart element class names
-Fixes change in scatter label behavior (need to monitor this more closely)
Fixes GH-1083
=> GH-1083 - Adds AmChart element class names & Scatter fix

src/other/Paginator.css, src/other/Table.js
Adds CSS so that the paginator does not wrap to another line.
Also added checks for fixedSize() param so the size is not set to 0.
Fixes GH-890
Fixes GH-1090
=> GH-890 Pagination + Narrow Space

src/layout/Cell.js
@jbrundage @dtsnell4 @GordonSmith Please Review (one of the 3 issues reported from DSP team)
Fixes GH-1098
=> GH-1098 Fix Cell IndicateIds

src/c3chart/Common.js, src/c3chart/CommonND.js, src/c3chart/Line.js
=> GH-1080 Fix C3 Time Axis (1.6.8)

src/c3chart/CommonND.js
=> GH-1080 Fix C3 Time Axis

src/form/TextArea.js, test/formFactory.js
=> GH-1110 Add Input TextArea Specialization

src/other/Table.css, src/other/Table.js, test/otherFactory.js
Adds params to sum total the contents of a numeric column.
Fixes GH-1101
=> GH-1101 Table column totals

demos/dermatology.html
Fixes GH-981
@mlzummo @dtsnell4 Please review
This code change simply updates the Surface title at the top of the dermatology.html page when switching between widgets.
http://rawgit.com/jbrundage/Visualization/GH-981-DermTitle/demos/dermatology.html
=> GH-981 Derm page displays correct Surface title

demos/marshaller/index.html, src/amchart/CommonFunnel.js, src/amchart/CommonRadar.js, src/amchart/CommonSerial.js, src/amchart/CommonXY.js, src/amchart/Pie.js, src/common/Utility.js, src/marshaller/HipieDDL.js
Pass true/false based on selection / de-selection.
Improved Surface Titles (params).
Fixed resize issue with marhaller demo page.
Added "endsWith" to Utility.js
Fixes GH-1131
=> GH-1131 AM Charts Click Missing Selection Flag

src/composite/MegaChart.js, src/marshaller/HTML.js, src/marshaller/HipieDDL.js
=> GH-1115 Integrate MegaChart into Marshallers

src/google/Combo.js, test/googleFactory.js
Adds Google's Combo Chart to the framework.
Fixes GH-1107
=> GH-1107 Add Google Combo chart

src/marshaller/HipieDDL.js
When a visualization has new data loaded into it, its previous selection (cached in the marhsaller) needs to cleared.
Fixes GH-1136
=> GH-1136 Marshaller selections persist too long

src/common/Utility.js, test/utility.js
=> Add D3ArrayAdapter

src/common/FAChar.js, src/common/Icon.js, src/common/List.js, src/common/Menu.js, src/common/Surface.js, src/common/TextBox.js, src/common/Widget.js, src/common/WidgetArray.js, src/form/Form.js
=> Simple Leak Checking.

src/common/Widget.js, src/layout/Cell.js, src/layout/Grid.js, src/marshaller/HTML.js, src/other/PropertyEditor.js
HTML Marshaller will highlight which widgets update other widgets.
Fixed bug in Grid.getCell (broken when cell density was introduced).
Partial fix for performance issue (opening new issue(s) for my thoughts).
=> GH-1116 Highlight Update Targets

src/graph/Graph.js, src/graph/GraphLayouts.js, src/other/Table.js
Fix minor Table selection issue.
=> Added Force Directed Settings

src/other/Persist.js
Fixes deserialization of empty widgetarray
Fixes GH-1126
=> GH-1126 WIDGET_ARRAY_PERSIST_FIX

src/amchart/CommonFunnel.js, src/amchart/CommonRadar.js, src/amchart/CommonSerial.js, src/amchart/CommonXY.js, src/amchart/Gauge.js, src/amchart/Pie.js
=> Adds AmCharts Cursor

src/amchart/Bar.js, src/amchart/Column.js, src/amchart/CommonSerial.js, src/amchart/Scatter.js, src/chart/Bar.js, src/google/Column.js, test/amchartFactory.js, test/chartFactory.js
Standardizes Column & Bar
Fixes GH-1096
=> GH-1096 Standardizes Column & Bar

src/chart/Bar.js, src/chart/Gantt.js, test/chartFactory.js
=> GH-1011 Add Gantt Chart

src/amchart/CommonSerial.js
=> GH-1203 Fixes Column selection visibility

test/amchartFactory.js
=> Fixes AmChart Test Data Inconsistencies

demos/graph/app/Main.js, demos/graph/css/graph.css, demos/graph/css/style.css, demos/graph/index.html, demos/graph/main.js
Added Force Directed Settings
Add alert to edge click.
Rebase onto latest sources.
Add extra params to send
Add tabbed tables
Add selection to 1 degree
Rebasing onto latest
Add serialization to Graph.
Fixes GH-1168
=> GH-1168 Show/Hide Selection breaks grid

src/amchart/CommonSerial.js, test/amchartFactory.js
@GordonSmith @dtsnell4 @jbrundage Please Review
Fixes GH-1185
=> GH-1185 AmChart Date Sorting Fix

src/composite/MegaChart.js
=> GH-1211 Fixes column/data call in MegaChart

src/c3chart/Common.js, src/c3chart/Common1D.js, src/c3chart/Common2D.js, src/c3chart/CommonND.js
Fixes GH-767
@mlzummo @dtsnell4 Please review
http://rawgit.com/jbrundage/Visualization/GH-767-AddC3Sel/demos/dermatology.html?src/c3chart/Bar
=> GH-767 Adds selection to C3 charts

src/c3chart/Common.js
=> GH-1216 C3 pie chart displaying too many slices

src/marshaller/HipieDDL.js, test/marshallerFactory.js
=> GH-1118 Choro + Array of Weights

src/map/GMap.js
@GordonSmith @dtsnell4 - please review
=> Gmap Unit Test warn fix

src/marshaller/HipieDDL.js
=> GH-1223 Rollback MegaChart to MultiChart

src/google/Common.js
Create / Remove Google Charts on demand.
=> GH-1214 Empty Google Chart Error

src/common/Class.js, src/common/Platform.js, src/common/PropertyExt.js, src/common/Widget.js, src/other/Persist.js, test/runner_build_nonamd.html
=> Refactor Widget Base Class

src/amchart/Column.js, src/amchart/CommonFunnel.js, src/amchart/CommonRadar.js, src/amchart/CommonSerial.js, src/amchart/CommonXY.js, src/amchart/Gantt.js, src/amchart/Pie.js
AmCharts DataProvider updated on related PP changes & columns()
Color By Category Fixed
=> Misc AmCharts Fixes

gulpfile.js
Auto create and push the bX.Y.Z branch
=> Improve Release Process

src/google/Area.js, src/google/Column.js, src/google/Line.js, src/google/Scatter.js
@dtsnell4 @GordonSmith - Please Review
Fixes GH-1218
=> GH-1218 GOOGLE DUP LABEL FIX

src/layout/Surface.js
=> GH-1158 Fixes Surface button annotations for FF

src/amchart/Area.js, src/amchart/Column.js, src/amchart/CommonFunnel.js, src/amchart/CommonRadar.js, src/amchart/CommonSerial.js, src/amchart/CommonXY.js, src/amchart/Line.js, src/amchart/Pie.js
=> Misc Fixes (1.8.2)

demos/dermatology.html, src/common/Shape.js, src/common/Widget.js, src/other/PropertyEditor.css, src/other/PropertyEditor.js
Fix leaking watches.
Fix Shape Colours.
Added "render=false" to prevent contained widgets or widgetArrays from auto rendering.
Fixes GH-1153
=> GH-1153 Adds new PropEdit

src/api/IInput.js, src/form/Form.js, src/form/Input.js, test/formFactory.js
Adds PP so that forms can't submit on empty data
Fixes GH-1178
=> GH-1178 FORM_SUBMIT_BLANK FIX

src/marshaller/HipieDDL.js
Wraps "clear" in if for Graph for events
Fixes GH-1243
=> GH-1243 HippieDDL Graph Fix

.jshintrc, bower.json, demos/marshaller/index.html, demos/test-no-amd.html, gulpfile.js, src/common/Widget.js, src/config.js, src/marshaller/Graph.js, src/marshaller/HTML.js, src/marshaller/HipieDDL.js, src/marshaller/Tabbed.js, src/other/Comms.js, test/runner_build_nonamd.html
Added ES6 Promise/A+ Polyfill
Fixes GH-991
=> GH-991 Add better error reporting.

src/common/Widget.js, src/layout/Grid.js, src/other/PropertyEditor.js
Fixes object watch for firefox
Fixes GH-1250
=> GH-1250 - DERM_OBJ_WATCH_FIX

demos/dermatology.html
=> Sync URL with property selection.

src/layout/Cell.js
Fixes GH-1255
@GordonSmith @mlzummo @dtsnell4 Please Review
=> GH-1255 Makes layout/Cell dragHandle ID-specific

demos/DataAnalyst/css/graph.css, src/other/Table.js
Removed conflicting css from graph.css.  Also fixed error in pagination calculation.
Fixes GH-1262
=> GH-1262 Table Render Issues

src/other/PropertyEditor.css, src/other/PropertyEditor.js
Fixes GH-1258
http://rawgit.com/jbrundage/Visualization/GH-1258/demos/dermatology.html?src/layout/Grid
=> GH-1258 Adds sub-prop table span to table head

src/composite/MegaChart.js, src/marshaller/HipieDDL.js
=> GH-1263 Fixes MegaChart axis label bugs

demos/dermatology.html
=> Add encoding to URL params.

src/amchart/CommonSerial.js, src/amchart/CommonXY.js, src/amchart/SerialAxis.js, src/amchart/XYAxis.js, src/api/Axis.js, src/common/PropertyExt.js, test/amchartFactory.js
@GordonSmith @jbrundage @dtsnell4 - Please Review
(still need to clean up commented code but would like you to read the commented sections and get ideas for comments)
=> Adds Axis Object - Refactors Amcharts Axis PPs

src/amchart/Gantt.js, test/amchartFactory.js
Adds AmChart Gantt Guide (vertical lines)
=> Adds AmChart Gantt Guide (vertical lines)

gulpfile.js, src/chart/MultiChart.js, src/common/Class.js, src/common/Database.js, src/common/PropertyExt.js, src/common/Utility.js, src/common/Widget.js, src/map/Graph.js, src/map/Layered.js, src/marshaller/HipieDDL.js, src/other/Comms.js, src/other/Persist.js, src/other/PropertyEditor.js, src/other/Table.js, test/datagrid.js, test/marshallerFactory.js, test/otherFactory.js, test/widgets.js
Allow Class.mixin to augment class list.
Remove existing Table formatting and replace with fields.
Allow persist suuport for non Widget classes which mixin PropertyExt.
Comms timeout previously set to 1 (for testing?)
=> Add mask + formatting to Database.Grid

demos/dermatology.html, src/common/Database.js, src/marshaller/HipieDDL.js, src/other/Comms.js, test/marshallerFactory.js
Add testID to dermatology URL history.
=> Symposium Hack being bypassed with new DB

src/marshaller/HipieDDL.js
=> GH-1283 Omit null and undefined request params

demos/dermatology.html, src/composite/MegaChart.js, src/layout/Border.css, src/layout/Border.js
Fixes GH-1278
http://rawgit.com/jbrundage/Visualization/GH-1278/demos/dermatology.html?src/layout/Border&designMode=true
http://rawgit.com/jbrundage/Visualization/GH-1278/demos/dermatology.html?src/composite/MegaChart
=> GH-1278 Refactors layout/Border designMode

src/chart/MultiChart.js, src/composite/MegaChart.js, src/layout/Border.js, src/other/Legend.css, src/other/Legend.js, test/compositeFactory.js
Fixes GH-1287
http://rawgit.com/jbrundage/Visualization/Legend_Imp/demos/dermatology.html?src/composite/MegaChart.pie
=> GH-1287 Enhances Legend within MegaChart

src/common/Database.js, src/common/PropertyExt.js, src/common/Widget.js, src/graph/Graph.js, src/marshaller/HipieDDL.js, src/other/Comms.js, test/marshallerFactory.js
=> More DB Regressions

src/other/PropertyEditor.css, src/other/PropertyEditor.js
=> GH-1259 Improves Cell propEdit filter

src/common/PropertyExt.js, src/other/Persist.js
=> Remove "theme" support from Publish Params.

src/marshaller/HipieDDL.js
=> Merge conflict

src/layout/Cell.js, src/layout/Grid.css, src/layout/Grid.js, src/layout/Surface.css, src/layout/Surface.js, test/layoutFactory.js
Fixes GH-1264
@mlzummo please review
http://rawgit.com/jbrundage/Visualization/GH-1264/demos/dermatology.html?src/layout/Grid&designMode=true
=> GH-1264 Hides widgets while Grid in designMode

src/other/Table.js
Adds sortByFieldIndex and minWidgetHeight publish parameters to make the table sorting persistible.
Also adds the Utility.multiSort() as the sorting function.
Fixes GH-1155
=> GH-1155 Table Sort Publish Param

demos/dermatology.html
=> Fix Dermatology URL + Params (again)

src/api/ITooltip.js, src/map/Choropleth.js, src/map/ChoroplethCounties.js, src/map/ChoroplethCountries.js, src/map/ChoroplethStates.js, src/map/GeoHash.js, src/map/Graph.js, src/map/Heat.js, src/map/Pins.js
=> Performance Optimizations

src/layout/Grid.css, src/layout/Grid.js
Partially Fixes GH-1200
http://rawgit.com/jbrundage/Visualization/Grid_Imps/demos/dermatology.html?src/layout/Grid
=> GH-1200 Adds params to Grid designMode styles

src/composite/MegaChart.js, src/marshaller/HipieDDL.js
Adds megachart to marshaller
Adds new params to megachart for multichart
Fixes GH-1320
=> GH-1320 MEGACHART_MARSHALLER_FIX

src/marshaller/HTML.js
@GordonSmith @jbrundage
Please Review ... i think we need a more universal way of fixing this ... but this in the meantime fixes this specific issue
Fixes DSP MARSHALLER/PERSIST issue
Fixes GH-1316
=> GH-1316 MARSHALLER_PERSIST_FIX

src/common/PropertyExt.js, src/other/PropertyEditor.css, src/other/PropertyEditor.js, src/other/Table.js
Allow conditional disabling of properties in the property editor.
Fixes GH-1330
=> GH-1330 Enable Table Pivoting

src/google/Common.js, src/google/Material.js, src/google/MaterialBar.js, src/google/MaterialGantt.js, test/DataFactory.js, test/googleFactory.js
Adds Google Visualization Library Gantt chart (v1.1)
Fixes GH-1106
Signed-off-by: Dan Snell <Mathew.Zummo@lexisnexis.com>
=> GH-1106 Add Google Gantt Chart

src/amchart/CommonSerial.js, src/amchart/CommonXY.js, src/api/Axis.js, src/other/PropertyEditor.js
re-factors Axis to use PropertyExt & changes PE render option
Fixes GH-1341
=> GH-1341 PROPEDITOR_AXIS_OBJ_FIX

demos/graph/app/Main.js
=> GH-1328 ZN_Graph table corruption

src/other/Html.css, src/other/Html.js, test/otherFactory.js
Fixes GH-1314
@mlzummo @GordonSmith please review
Example using **.html()** publish param:
http://rawgit.com/jbrundage/Visualization/Html_Widget/demos/dermatology.html?src/other/Html.simple
Example using **.data()**:
http://rawgit.com/jbrundage/Visualization/Html_Widget/demos/dermatology.html?src/other/Html.array
=> GH-1314 Adds other_Html widget

src/graph/Graph.js, src/marshaller/HipieDDL.js
Allows the graph to persist and recreate new vertexes/edges
Fixes GH-1336
=> GH-1336 MARSHALLER_PERSIST_GRAPH_FIX

src/api/IInput.js, src/form/Button.js, src/form/CheckBox.js, src/form/ColorInput.js, src/form/Input.js, src/form/Radio.js, src/form/Range.js, src/form/Select.js, src/form/Slider.js, test/DataFactory.js, test/formFactory.js
=> GH-1229 Form Input Refactor

src/google/Combo.js, test/googleFactory.js
=> GH-1347 GOOGLE_COMBO_COMPAT

.jshintrc, src/common/Widget.js, src/graph/Edge.css, src/graph/Graph.css, src/graph/Vertex.css
Signed-off-by: Gordon Smith <gordon.smith@gmail.com>
=> Allow runtime classing of widgets

src/chart/Column.js, src/chart/XYAxis.js, src/other/Table.js
* Selection brush + no data rendered invalid rect
* Columns rendering data beyond max columns
Fixes GH-1319
=> GH-1319 XYAxis rendering invalid shapes

src/amchart/Combo.js, src/amchart/CommonSerial.js, src/amchart/CommonXY.js, src/amchart/SerialAxis.js, test/amchartFactory.js
=> GH-1108 AmCharts Combo

demos/dermatology.html, src/common/PropertyExt.js, src/common/Widget.js, src/other/PropertyEditor.js
Adds ability to override tags by prototype
Adds ability to filter PPs by basic, intermediate, advance
Fixes GH-1246
=> GH-1246 PE OVERRIDE TAGS & FILTER

src/form/Form.js, src/form/Input.js, src/marshaller/HipieDDL.js
=> GH-1350 INPUT_REGRESSION

src/chart/MultiChart.js
Adds new chart types to MultiChart
Fixes GH-1323
=> GH-1323 ADD_MULTICHART_TYPES

gulpfile.js
=> GH-1364 es6-promise is not resolved in AMD build.

src/other/Table.js
Simplify selection update.
Only sort data if sort criteria has changed.
Fixes GH-1362
=> GH-1362 Table selection is broken

apps/legacyDash.html, src/layout/Border.js, src/other/Persist.js, src/other/Toolbar.js, test/persist.js
=> GH-1367 Desrialization Regression

src/common/Database.js
=> GH-1342 Improve HIPIE mapping console errors

src/marshaller/HipieDDL.js
Not displaying child label.
Fixes GH-1345
=> GH-1345 Graph marshaller not using default icon

src/layout/Cell.js
=> GH-1372 Cell indicator throws exception

src/composite/MegaChart.js
=> GH-1375 Adds chart publishProxy to MegaChart

src/amchart/Axis.js, src/amchart/CommonSerial.js, src/amchart/CommonXY.js, src/amchart/SerialAxis.js, src/amchart/XYAxis.js, src/common/PropertyExt.js, src/other/PropertyEditor.js, test/amchartFactory.js
Adds PP for backwards compat and old publish params back
Fixes GH-1334
=> GH-1334 AMCHART_BACKWARD_COMPAT

src/other/Table.js, test/otherFactory.js
=> GH-1332 Reset cell widths on update

demos/graph/app/Main.js, demos/graph/css/graph.css, src/other/Table.js
=> Rebase ZN_GRAPH onto 1.10.0

src/chart/MultiChart.js
=> GH-1385 Multi Chart uses wrong BAR

src/other/Persist.js
=> GH-1392 Themes using wrong method to access property values.

gulpfile.js, package.json, src/common/Platform.js, src/other/Persist.js
=> GH-1390 Use build version in persist strings.

src/chart/MultiChart.js, src/composite/MegaChart.js, src/marshaller/HipieDDL.js, src/other/Persist.js, src/other/PropertyEditor.js
=> GH-1384 Fields not persisting correctly

src/chart/MultiChart.js, src/common/PropertyExt.js, src/common/Widget.js, src/composite/MegaChart.js
=> GH-1388 Prevent duplicate PP serialization

gulpfile.js
=> Add bundles definition file to assist dynamic loading.

gulpfile.js
=> GH-1400 tag-release needs to include Platform.js

src/chart/MultiChart.js, src/common/HTMLWidget.js
=> MultiChart not resizing correctly

src/amchart/CommonSerial.js, src/amchart/CommonXY.js, test/amchartFactory.js
Fixes SerialObj Handling and Persisting
Fixes GH-1411
=> GH-1411 AmChart Fix

src/amchart/Column.js, src/layout/Popup.js
Fixes GH-1403
Removes the css includes of empty css files in amchart/Column.js and layout/Popup.js
=> GH-1403 Removes includes of empty css files

src/other/Comms.js
=> GH-1383 Adds IE9/10 url parse fix to Comms.js

src/other/Comms.js
=> GH-1430 WU Marshaller ignores filters of 0

src/common/HTMLWidget.js, src/common/SVGWidget.js, src/common/Widget.js, src/marshaller/HTML.js, src/other/Paginator.js
=> GH-1442 Typo:  domeNode

src/form/TextArea.js
=> GH-1460 Add spellcheck PP to TextArea

src/layout/Tabbed.js
=> GH-1459 Tabbed not clearing correctly

src/layout/Cell.js
Fixes GH-1354
http://rawgit.com/jbrundage/Visualization/GH-1354-nonpp/demos/dermatology.html?src/layout/Grid.hoverIndicator
=> GH-1354 Refactors 'indicateTheseIds' in Cell.js

src/amchart/Pie.js
(labels wont get clipped)
Fixes GH-1445
=> GH-1445 AMCHARTS_PIE_LABEL_FIX

src/common/Widget.js, src/other/Persist.js
=> GH-1457 Allow alternatives to "_w" for ID prefixes

src/common/Widget.js, src/marshaller/HipieDDL.js
=> GH-1474 Marshaller updates title params incorrectly

src/marshaller/HipieDDL.js
=> GH-1480 Selection should default to "undefined" and not ""

src/marshaller/HTML.js, src/marshaller/HipieDDL.js
=> GH-1469 Optionally allow clear to propagate

src/marshaller/HipieDDL.js
=> GH-1399 Prevent marshaller from rendering during D3 transition

src/c3chart/Common.js, test/c3chartFactory.js
Reverts hpcc-systems/Visualization#1441
=> Revert "GH-1399 C3Charts can corrupt"

src/amchart/CommonSerial.js, src/amchart/CommonXY.js
=> GH-1489 Fixes backwards compat and context

src/marshaller/HTML.js, src/marshaller/HipieDDL.js
=> GH-1491 Optionally clear data on refresh

demos/dermatology.html, src/marshaller/HipieDDL.js
=> GH-1484 "...loading..." not being reset correctly

src/composite/MegaChart.js, src/marshaller/FlyoutButton.js, src/marshaller/HTML.js, test/marshallerFactory.js, test/widgets.js
Improved merging of DDL + Persist widgets.
Fixed update indicators.
Fixes GH-1487
Fixes GH-1470
=> GH-1487 Add flyout support to MegaCharts

src/marshaller/HipieDDL.js
=> GH-1501 DUD properties not being propagated correctly

src/marshaller/HTML.js
Find an empty slot for any new widgets.
Fixes GH-1505
=> GH-1505 Merging DDL + Dermatology changes

package.json, src/common/Utility.js, src/marshaller/Graph.js
=> Fix D3 3.5.16 + unit test failure.

bower.json, package.json, src/common/Platform.js
=> Branch candidate-1.14.0

src/amchart/CommonSerial.js, src/chart/XYAxis.js
=> GH-1516 Automate sortDates as needed

src/marshaller/HipieDDL.js
Dermatology title is lost during refresh process.
Fixes GH-1514
=> GH-1514 Title reverts to DDL title

src/amchart/CommonSerial.js
=> GH-1523 - Sorts data() with dataObjArr

src/c3chart/Common.js, src/c3chart/CommonND.js, src/c3chart/Line.js, src/chart/Summary.js, src/layout/Surface.js, src/layout/Tabbed.js
=> GH-1410 Checks _exists before appending 'px'

src/chart/MultiChart.js, src/chart/Summary.js
Add option to "play" through the data.
=> GH-1511 Convert summary to 2D chart

src/common/Utility.js, src/common/Widget.js, src/composite/MegaChart.js
=> GH-1531 CSV download not encoded correctly

src/map/GMapLayered.js, src/map/Layered.js
Render needs to return this.
Fixes GH-1540
=> GH-1540 Layered maps render issue

bower.json, src/chart/HexBin.css, src/chart/HexBin.js, src/chart/MultiChart.js, src/config.js, test/chartFactory.js
=> GH-1510 Add HexBin chart

src/amchart/SerialAxis.js
Defaulting to null instead of 0.
Fixes GH-1557
=> GH-1557 AM Charts invalid axis rotation value

src/config.js, src/configRawGit.json
=> Topojson rawgit location has moved.

src/chart/MultiChart.js, src/common/PropertyExt.js, src/composite/MegaChart.js, src/marshaller/HipieDDL.js
=> GH-1517 "_" properties should be set as default values

src/layout/Grid.js, src/marshaller/HTML.js
=> GH-1513 Removed widgets still display

src/common/PropertyExt.js
Proxy properties are not broadcasting changes.
Fixes GH-1549
=> GH-1549 ProxyProperties + monitor

src/other/HeatMap.js
=> GH-1581 HeatMap Regression

src/other/Table.js
Default to single select mode for tables.
=> GH-1573 Table Single Select

src/google/Material.js, src/map/GMap.js
Comparing "https" and not "https:"
Fixes GH-1583
=> GH-1583 Google Map + https failed to load

src/other/Table.js
=> GH-1596 Table number alignment fails

src/common/PropertyExt.js
=> GH-1585 Optional + _exists issue

src/chart/MultiChart.js, src/common/Palette.js, src/common/PropertyExt.js, src/common/Widget.js, src/layout/Border.js, src/other/Legend.js, src/other/PropertyEditor.js
=> GH-1591 Legends don't update to match choice in paletteID

bower.json, gulpfile.js, src/api/ITooltip.css, src/api/ITooltip.js, src/chart/Bubble.css, src/chart/Bubble.js, src/chart/Column.css, src/chart/Column.js, src/chart/Pie.js, src/chart/Scatter.css, src/chart/Scatter.js, src/config.js, src/map/Choropleth.css, src/map/Choropleth.js, src/map/ChoroplethCounties.js, src/map/ChoroplethCountries.js, src/map/ChoroplethStates.js, src/map/Graticule.js, src/map/Heat.js, src/map/Layer.js, src/other/Table.js, test/DataFactory.js
Swicthed to use d3-tip.
Fixes GH-1125
=> GH-1125 Tooltips show in wrong location

src/chart/Pie.css, src/chart/Pie.js
=> Hide pie labels which overflow.

src/chart/Axis.css, src/chart/Axis.js, src/chart/Column.css, src/chart/HexBin.js, src/chart/Scatter.js, src/chart/XYAxis.js, src/configRawGit.json
=> GH-1604 Chart Guide Lines

src/api/ITooltip.css, src/api/ITooltip.js, src/chart/Axis.js, src/chart/Column.js, src/chart/HexBin.js, src/chart/XYAxis.js, src/common/PropertyExt.js
=> GH-1606 Add focus support to XYAxis

src/google/MaterialGantt.js
Renamed to Gantt
Fixes GH-1614
=> GH-1614 Google Renamed GanttChart

src/map/Choropleth.js, src/map/ChoroplethCounties.js, src/map/ChoroplethCountries.js, src/map/ChoroplethStates.js, src/map/Layered.js, src/map/TopoJSONChoropleth.js, test/mapFactory.js
=> GH-1617 Autosize map to fit data

src/chart/HexBin.js, src/chart/XYAxis.js
Disable focus when not horizontal.
=> A bit better when focus is enabled.

src/composite/MegaChart.js
Refresh Chart Type Select on render.
Fixes GH-1628
=> GH-1628 MegaChart Type Select Sync Issue

demos/loader/index.html, demos/test.html, gulpfile.js, src/loader.js
Failed to locate script file.
Fixes GH-1608
=> GH-1608 Move loader into global namespace

src/chart/Axis.js, test/chartFactory.js
=> GH-1618 Overlap mode "wrap" for axis labels

src/chart/XYAxis.js
=> GH-1636 Guild lines + focus out of sync

src/map/GMap.js, test/mapFactory.js
Fixes GH-1643
http://rawgit.com/jbrundage/Visualization/GMAP_STYLES_1.14.0/demos/dermatology.html?src/map/GMap.colored
=> Fixes GH-1643 Adds styling publish param to GMap

src/graph/Vertex.js, test/DataFactory.js, test/graphFactory.js
Fixes GH-1671
http://rawgit.com/jbrundage/Visualization/GH-1671_Vertex/demos/dermatology.html?src/graph/Graph
http://rawgit.com/jbrundage/Visualization/GH-1671_Vertex/demos/dermatology.html?src/graph/Graph.restyle
=> GH-1671 Adds Vertex publish properties

src/common/Class.js
=> GH-1667 Mixin class is incorrect.

src/common/PropertyExt.js, src/common/Utility.js, src/other/PropertyEditor.js, test/publish.js, test/runner.html
=> GH-1655 Add runtime "set" support

src/common/Utility.js
=> GH-1666 Allow member class declarations

src/common/Database.js, test/datagrid.js
=> GH-1653 Add "views" to Database.Grid;

src/common/SVGZoomWidget.css, src/common/SVGZoomWidget.js, src/tree/Dendrogram.css, src/tree/Dendrogram.js, test/treeFactory.js
Add radial layout
Add tree layout
Add pan + zoom
=> Radial Dendrogram

bower.json, gulpfile.js, src/chart/BulletChart.css, src/chart/BulletChart.js, src/config.js, test/chartFactory.js, test/datagrid.js, test/runner_build_nonamd.html
=> Bullet Chart

src/other/Select.css, src/other/Select.js, test/otherFactory.js
=> Data Driven Select

src/chart/MultiChart.js, src/other/NestedTable.js, test/otherFactory.js
Default array in cell to a new table instance.
=> Nested Table

src/other/Comms.js, src/other/Table.js, test/otherFactory.js
JS Array.foreach skips undefined cell elements.
Fixes GH-1694
=> GH-1694 Table + undefined cells

src/chart/MultiChart.js, src/common/Database.js, src/map/GMapLayered.js, src/map/GMapPin.js, src/map/GMapPinLine.js, src/map/Lines.css, src/map/Lines.js, src/map/Pins.js, test/chartFactory.js, test/datagrid.js, test/mapFactory.js, test/marshallerFactory.js, test/widgets.js
=> Custom GMaps

src/chart/MultiChart.js, src/common/Database.js, src/tree/Treemap.css, src/tree/Treemap.js, test/chartFactory.js, test/datagrid.js, test/mapFactory.js, test/treeFactory.js
Signed-off-by: fnisswandt <Franz.Nisswandt@lexisnexis.com>
=> Treemap initial implementation plus palette / misc cleanup.

src/amchart/CommonSerial.js
Fixes GH-1722
@GordonSmith @jbrundage @jchambers-ln - Please Review
=> Adds show all label support for amcharts

src/other/Table.js
=> GH-1638 Pivot mode broken

bower.json, src/chart/MultiChart.js, src/composite/MegaChart.js, src/marshaller/HipieDDL.js, src/other/Legend.css, src/other/Legend.js, src/other/Table.js, test/compositeFactory.js
Add choro to multichart
Add rainbow bin count and format to rainbow legend
Tweak rainbow legend
Fixes GH-1625
=> GH-1625 Add Choropleth Legend

demos/dermatology.html
=> GH-1751 Add save/load to dermatology

src/chart/Bullet.css, src/chart/Bullet.js, src/common/Database.js, src/common/Utility.js, src/graph/Sankey.css, src/graph/Sankey.js, src/map/GMapPin.js, src/map/GMapPinLine.js, src/other/CalendarHeatMap.css, src/other/CalendarHeatMap.js, src/tree/Dendrogram.css, src/tree/Dendrogram.js, src/tree/Treemap.css, src/tree/Treemap.js, test/otherFactory.js
* Bullet
* GMapPin
* GMapPinLine
* CalendarHeatMap
* Dendrogram
* Treemap
* Sankey
Fixes GH-1710
=> GH-1710 Add selection support

src/marshaller/HipieDDL.js, test/marshallerFactory.js
=> GH-1757 Filter edges with unseen to/from vertices

src/other/Select.js
Add optional property to insert blank row.
Fixes GH-1776
=> GH-1776 Select sends invalid click event

src/other/Comms.js
Allow hosting app to hook the JSONP call to ESP.
=> GH-1735 Hookable JSONP

src/composite/MegaChart.js
=> GH-1774 Add procedure downloadCSV to MegaChart

src/map/GMap.js
=> GH-1804 Add default GMap API Key

src/chart/Bubble.js, src/chart/Bullet.js, src/chart/Pie.js, src/chart/XYAxis.js, src/common/Utility.js, src/graph/Sankey.js, src/layout/Grid.js, src/map/Choropleth.js, src/map/ChoroplethContinents.js, src/map/ChoroplethCounties.js, src/map/ChoroplethCountries.js, src/map/ChoroplethStates.js, src/map/Pins.js, src/map/TopoJSONChoropleth.js, src/marshaller/HipieDDL.js, src/marshaller/HipieDDLMixin.js, src/other/CalendarHeatMap.js, src/other/Persist.js, src/other/Table.js, src/tree/Dendrogram.js, src/tree/Treemap.js
Serialize widget state.
Fixes GH-1799
=> GH-1799 Serialize State

src/api/ITooltip.css, src/form/Select.js, src/layout/Toolbar.css, src/layout/Toolbar.js
Buttons are too tall.
Fixes GH-1800
=> GH-1800 MegaChart Toolbar and IE

src/common/PropertyExt.js
Monitor/Broadcast proxy properties.
Fixes GH-1801
=> GH-1801 Monitor Proxy Properties

src/marshaller/HipieDDL.js
=> Common up const strings in HipieDDL.js

src/chart/Summary.js, test/chartFactory.js
Unit tests using wrong data shape.
Fixes GH-1787
=> GH-1787 Summary ignores field formats

src/chart/MultiChart.js, src/common/Database.js, src/common/Widget.js, src/composite/MegaChart.js, src/map/Layered.js, src/map/Pins.js, src/marshaller/HTML.js, src/marshaller/HipieDDL.js, src/marshaller/HipieDDLMixin.js, src/other/PropertyEditor.js, test/compositeFactory.js, test/mapFactory.js, test/marshallerFactory.js
=> GH-1664 DDL Choro Layers

src/map/Layered.css
Ignores dermatology setting
Fixes GH-1814
=> GH-1814 Choropleth Background Color

src/common/Database.js
Ignore missing data and aggregate functions.
Fixes GH-1794-MissingDataFunc
=> GH-1794 MissingData + Aggregates

src/composite/MegaChart.js
typo, slice should be splice.
Fixes GH-1703
=> GH-1703 Show/Hide MegaChart Toolbar Items

src/marshaller/HipieDDL.js
=> GH-1720 Suppress empty params in title.

demos/dermatology.html, src/common/Utility.js
=> GH-1772 Dermatology not updating URL correctly

src/common/Class.js
=> GH-1803 Optimize Mixin

src/common/PropertyExt.js, src/other/Persist.js
Move into PropertyExt
Fixes GH-1802
=> GH-1802 Refactor Persist.discover

src/api/ITooltip.js, src/chart/Area.js, src/chart/Axis.js, src/chart/Bar.js, src/chart/Gantt.js, src/chart/HexBin.js, src/chart/Line.js, src/chart/Pie.js, src/chart/Scatter.js, src/chart/Step.js, src/chart/XYAxis.js
Ensure initial settings are the default values.
Fixes GH-1798
=> GH-1798 Default all initial settings

src/map/GMapPin.js, src/map/Pins.js
=> Fixes GH-1306 Adds PP to Pins for flexibility

src/layout/Cell.css, src/layout/Cell.js
=> GH-1760 IndicateTheseIds catches all mouse events

src/other/Table.js
Render errors when no node.
Fixes GH-1830
=> GH-1830 Table Render Failure

src/marshaller/HipieDDL.js
Requires https://github.com/hpcc-systems/HIPIE/issues/1796
Fixes GH-1756
=> GH-1756 Icon enums not working

bower.json, gulpfile.js, src/config.js, src/loader.js, src/other/AutoCompleteText.css, src/other/AutoCompleteText.js, test/otherFactory.js
Fixes GH-1622
Signed-off-by: mounicarachakonda <mounica.rachakonda@lexisnexis.com>
=> GH-1622 Auto Complete Select Input

src/common/Database.js
Merge conflict:  Return "Missing Data" inside a function.
Fixes GH-1840
=> GH-1840 Regression Missing Data

src/marshaller/HipieDDL.js
Check that widget has columns to set (forms won't).
Fixes GH-1838
=> GH-1838 Regression caused by GH-1829

src/graph/Vertex.js, src/marshaller/HipieDDL.js
=> GH-1849 Allow all flag properties

src/marshaller/Graph.js, src/marshaller/HipieDDL.js, test/marshallerFactory.js
Add support for HIPIE mappings in events.
Fixes GH-1848
=> GH-1848 Refactor request calculation

src/marshaller/HipieDDL.js, src/marshaller/HipieDDLMixin.js, src/other/Comms.js
Added timeout option for marshallers
Fixes GH-1719
=> GH-1719 Publish Timeout

apps/SampleSite/sample_html/graph/Graph.html, demos/dermatology.html, demos/graph/app/Main.js, src/common/Utility.js, src/graph/Edge.js, src/graph/Graph.js, src/marshaller/HipieDDL.js, test/commonFactory.js, test/graphFactory.js
* Dash Arrays
* Markers
* Colors
Fixes GH-1647
=> GH-1647 Graph Edge Styles

src/other/Select.js
=> GH-1864 Click event working in Select.js

src/other/Comms.js, test/loader.js
=> GH-1842 Generalize WsECL connection

src/chart/Summary.js, src/common/PropertyExt.js, test/chartFactory.js
Allow user to pick columns
Allow embeded HTML
Fixes GH-1847
=> GH-1847 Viz II Summary

src/marshaller/HipieDDL.js
Default to dataSource URL.
Fixes GH-1860
=> GH-1860 Setting DDL/URL

src/graph/GraphData.js, src/marshaller/Graph.js
Specifically adding flyout widgets
Fixes GH-1857
=> GH-1857 Graph Marshaller fails to render

gulpfile.js, src/chart/MultiChart.js, src/common/Utility.js, src/marshaller/HipieDDL.js, src/other/Comms.js, src/other/Table.js
Add support for DDL defined nested widgets inside a table.
Fixes GH-724
=> GH-724 Nested Tables

src/map/Pins.js
=> GH-1868 Disable pins "bring to top" for IE

src/other/Table.js
=> GH-1837 Add dblclick support to Table

demos/dermatology.js
=> Switch resize to use lazyRender

src/graph/Vertex.js, src/marshaller/HipieDDL.js, test/marshallerFactory.js
"Row" being removed closer to the data arrival.
Suppress log messages
Fixes GH-1883
=> GH-1883 Graph Edges Missing

demos/dermatology.js
=> Dermatology re-renders every property change.

demos/dermatology.css
=> Style .surfaceTitle > h3 to match mega chart

src/marshaller/HipieDDL.js
Ensure most recent request if processed last.
=> GH-1871 Request/Response Sequence

src/marshaller/HipieDDL.js
=> GH-1877 Visualizations with no inputs fail to render

src/marshaller/HipieDDL.js
Fixes GH-1887-DDLFieldTypeDataset
=> GH-1887 Add support for DDL Field Type Dataset

src/marshaller/FlyoutButton.js, src/marshaller/HipieDDLMixin.js
=> GH-1713 Optionally keep flyout forms open on submit

src/loader.js
=> GH-1901 topojson using wrong URL

src/marshaller/HipieDDL.js, src/other/Comms.js
Use default values to prime the dashboard.
Fixes GH-1881
=> GH-1881 Default Form Filters

src/map/Pins.js
=> GH-1899 Moves map pin events to g.pin element

src/marshaller/HipieDDL.js, src/other/Table.js, test/marshallerFactory.js
MegaCharts didn't render correctly inside tables.
Missing widget creation code.
Fixes GH-1885
=> GH-1885 Nested Widget Regression

src/marshaller/Graph.js, src/marshaller/HTML.js
=> GH-1896 Marshaller _ddldashboards invalid access

src/composite/MegaChart.js, src/form/Input.js
=> GH-1058-MegaChart show legend toolbar button

src/marshaller/HipieDDL.js
Reverts hpcc-systems/Visualization#1876
=> Revert "GH-1871 Request/Response Sequence"

src/amchart/Column.js
Fixes GH-1823
signed off by :mounica.rachakonda@lexisnexis.com
=> GH-1823 amCharts dynamic properties

src/other/AutoCompleteText.js
=> GH-1884 AutoComplete with interactions.

src/other/Select.js, test/otherFactory.js
=> GH-1913 Optionally sort data driven Select

src/marshaller/HipieDDL.js, src/other/Table.js
=> GH-1920 DUD Pagination Settings Ignored

src/other/Table.js
=> GH-1923 Add "vertical" align property for tables

src/marshaller/HipieDDL.js
Cached request could be updated mid transaction.
Fixes GH-1934
=> GH-1934 HipieDDL.fetchData + cached request

src/amchart/Gauge.js, test/DataFactory.js, test/amchartFactory.js
Make bands a % of the low/high values
default the tick interval to NULL
Fixes GH-1555
=> GH-1555 AM Gauge Chart Bands Overflow

src/graph/Graph.js
Fixes GH-1941
Signed-off-by: jbrundage <jbrundage372@gmail.com>
=> GH-1941 Adds class to hovered Graph Vertex/Edge

src/other/Comms.js
=> GH-1936 WUID Dashboards duplicate result fetches

src/amchart/CommonSerial.js
Use correct series from graph object.
Fixes GH-1537
=> GH-1537 AM Chart Balloon Text Issue

src/chart/MultiChart.js, src/other/AutoCompleteText.js, test/otherFactory.js
Align logic with other_Select
Fixes GH-1949-AutoComplete
=> GH-1949 Add auto complete to MultiChart

src/layout/Border.js, src/other/Legend.js
=> GH-1947 Disable Legend Pagination

src/marshaller/HipieDDL.js
(Also added for vertex)
Fixes GH-1965
=> GH-1965 Graph edge needs original data

src/tree/Dendrogram.js, src/tree/Indented.css, src/tree/Indented.js, test/treeFactory.js
Added indented tree with nested XML support
=> GH-1670 Indented Tree

demos/marshaller/custom-bootstrap/scripts/main.js, src/marshaller/HipieDDL.js, src/marshaller/HipieDDLMixin.js
Add method to serializeRequests, which in turn can be used with primeData.
Fixes GH-1946
=> GH-1946 Marshaller Serialize Requests

src/common/Database.js, src/marshaller/HipieDDL.js
Additional check for missing data.
Fixes GH-1972
=> GH-1972 "undefined" cell issue

src/amchart/CommonSerial.js
Previous selection detection incorrect.
Fixes GH-1970
=> GH-1970 AM Line Click

src/other/Legend.js
=> GH-1976 Legend hidden on persist restore

src/marshaller/HipieDDL.js
=> GH-1985 Auto Upgrade Choropleth

src/layout/Grid.js
=> GH-1981 Grid surfacePadding overwrites cells

src/common/Database.js, test/datagrid.js
=> GH-1978 Field values not persisting

src/marshaller/HipieDDL.js
=> GH-1990 Remove invalid mapping de-reference

src/chart/Summary.css
=> GH-1989 Main Image Clipped

src/other/Comms.js
v5 and v6 have subtly different responses.
Fixes GH-1998
=> GH-1998 Roxie Response Version Differences

src/marshaller/HipieDDL.js
=> GH-1995 Roxie ignores default values

src/marshaller/HipieDDL.js
=> GH-2000 request.refresh set to "undefined"

src/api/IGraph.js, src/graph/Graph.js, src/marshaller/HipieDDL.js
=> GH-1991 Invalid graph event params

src/common/Widget.js
DDL field name needs to take precedence
=> GH-2016 Click Event + Custom Field Labels

src/graph/Graph.js, src/marshaller/HipieDDL.js
Implement vertex/edge click correctly.
=> GH-2015 Revert GH-1990

src/other/Paginator.css, src/other/Table.js
=> GH-2003 Table paginator blocks scroll bar

src/other/WordCloud.js
=> GH-2035 Word cloud issue with no data

src/loader.js
=> GH-2028 Prevent src/other/Persist from being included in hpcc-viz.js

src/chart/MultiChart.js, src/map/GMapLayered.js, src/marshaller/HipieDDL.js
Also enable OPENSTREET
Fixes GH-2021
=> GH-2021 Add GOOGLE_MAP to Hipie Layered

demos/dermatology.html
=> Add option to test builds to dermatology.html

src/other/AutoCompleteText.js
Fixes GH-2040
Signed-off by : Mounica Rachakonda mounica.rachakonda@lexisnexis.com
=> GH-2040 Dynamic width for AutoComplete textbox.

src/layout/AbsoluteSurface.css, src/layout/Layered.css, src/map/GMapLayered.js, src/map/Pins.css, src/map/Pins.js, test/layoutFactory.js
Invalid IE check
Change Pin cursor
Fixes GH-2023
=> GH-2023 Layered Events not propogating

src/map/Pins.css, src/map/Pins.js
=> GH-2057 GMap + Pins - events conflict

src/other/Opportunity.css, src/other/Opportunity.js, src/other/PropertyEditor.js, test/DataFactory.js, test/otherFactory.js
Fixes GH-2008
Signed-off by : Mounica Rachakonda <mounica.rachakonda@lexisnexis.com>
=> GH-2008 Opportunity movement widget.

src/composite/MegaChart.js, src/marshaller/HipieDDLMixin.js
=> GH-2019 Add classes to MegaChart Toolbar Items

src/chart/MultiChart.js
=> GH-2062 MultiChart setting chart should update chartType

src/common/Database.js, src/other/Table.js
=> GH-2067 Optionally hide table columns

src/composite/MegaChart.js, src/layout/Surface.js, src/other/PropertyEditor.js
Change order of title + background properties.
Display classID of widget in property editor.
=> GH-2073 Clarify surface / mega chart properties

package.json
=> Add missing dependency (for node 3.x)

src/marshaller/HipieDDL.js
=> GH-2052 Get state fails for items with no datasource

bower.json, demos/dermatology.css, demos/dermatology.js, gulpfile.js, package.json, src/layout/Cell.js, src/layout/Grid.css, src/layout/Grid.js, src/layout/Surface.css, src/layout/Surface.js, src/loader.js, src/map/Layered.js, src/marshaller/HTML.js, src/other/PropertyEditor.js, test/layoutFactory.js
=> GH-2030 Gridster Style Layout

src/chart/MultiChart.js
Signed-off by : Mounica Rachakonda mounica.rachakonda@lexisnexis.com
=> Added Handson and Opportunity to multichart

src/marshaller/HipieDDL.js
On initial load, all widgets should be updated from roxie.
Fixes GH-2085
=> GH-2085 Roxie + null filters

src/chart/Summary.js
=> GH-2098 Summary ChartType - Added checkboxes to hide the sub metric

src/map/GMap.js, test/mapFactory.js
Fixes GH-2091
http://rawgit.com/GordonSmith/Visualization/gh_2091/demos/dermatology.html?src/map/GMap.streetView
http://rawgit.com/GordonSmith/Visualization/gh_2091/demos/dermatology.html?src/map/GMap.splitStreetView
=> GH-2091 Adds StreetView API support

src/marshaller/HipieDDL.js
=> GH-2081 Choropleth county heuristic is never called.

src/marshaller/HipieDDL.js
=> GH-2087 Deselect event mapping is incorrect

src/map/ChoroplethStates.js
=> GH-2086 Choropleth + dblclick

src/chart/Bubble.js, src/map/Layered.js
=> GH-2117 Invalid "exit" overloads

src/other/CalendarHeatMap.js
=> GH-2119 Calendar Heatmap Delta Issue

src/graph/Edge.js
=> GH-2127 Adds graph/Edge fix for IE9/10/11

src/other/Comms.js
=> GH-2038 POST support not working.

src/other/Persist.js
=> GH-2036 Add promise support to deserializeFromObject

src/chart/Axis.js
=> GH-2032 Axis parser issue

src/map/GMap.js, src/map/GMapLayered.js
Allow host page to specify their own load script.
Fixes GH-2121
=> GH-2121 Delay load GMap

src/layout/Grid.css
=> GH-2131 Grid/Table CSS Clash

src/chart/XYAxis.css, src/chart/XYAxis.js
=> GH-2130 XYAxis focus + selection resize issues

src/marshaller/HipieDDL.js, src/other/Table.js, test/marshallerFactory.js
=> GH-2065 Add column level clicking support

src/composite/Dermatology.css, src/composite/Dermatology.js, src/form/OnOff.css, src/form/OnOff.js, src/layout/Border.js
=> GH-2034 Add Dermatology Widget

src/common/Utility.js
=> GH-2061 Add safe stringify to Utility

gulpfile.js, src/amchart/Area.js, src/amchart/Bar.js, src/amchart/Column.js, src/amchart/Combo.js, src/amchart/CommonFunnel.js, src/amchart/CommonRadar.js, src/amchart/CommonSerial.js, src/amchart/CommonXY.js, src/amchart/Gantt.js, src/amchart/Gauge.js, src/amchart/Pie.js, src/amchart/Polar.js, src/amchart/Pyramid.js, src/amchart/Scatter.js, src/config.js, src/loader.js, test/runner_build.html
=> GH-2113 Rename AM Charts Namespaces

src/common/Utility.js, src/marshaller/HipieDDL.js, src/other/Comms.js
=> GH-2033 Move exists into Utility.js

src/other/ESP.js
=> GH-2037 Refactor ESP calls.

src/layout/Grid.css, src/layout/Grid.js
Restrict dragging to predefined snapping extent.
Fixes GH-2138
=> GH-2138 Limit Grid Dragging

src/graph/Edge.js
=> GH-2149 Adds showArc pub param to Edge

src/other/Comms.js
Partial "quick" fix
Fixes GH-2009
=> GH-2009 Better string v numeric "fixing"

src/map/GMap.js, test/mapFactory.js
Fixes #GH-2083
http://rawgit.com/jesse-morris-ln/Visualization/GH_2083/demos/dermatology.html?src/map/GMap.drawing&mapDrawingTools=true
Signed-off-by: Jesse Morris jesse.morris@lexisnexis.com
=> Fixes GH-2083 Adds support for google maps drawing tools.

src/chart/Summary.css, src/map/OpenStreet.js
=> GH-2161 Default to https over http

demos/dermatology.js, src/chart/MultiChart.js, src/common/Database.js, src/common/Widget.js, src/composite/MegaChart.js, src/marshaller/HipieDDL.js
=> GH-2143 Clone regression for non dashboards

src/other/RadioCheckbox.css, src/other/RadioCheckbox.js, test/otherFactory.js
TODO Revisit when multi selection support has been added to 1.16.x
Fixed GH-2159
http://rawgit.com/gordonsmith/Visualization/checkbox/demos/dermatology.html?src/other/RadioCheckbox.simple
=> GH-2159 Radio/Checkbox Widget

bower.json, src/common/Widget.js, src/composite/MegaChart.css, src/composite/MegaChart.js, src/loader.js, test/compositeFactory.js
=> GH-2165 Adds Maximize feature to MegaChart

src/map/GMapPin.js, src/map/Pins.js
Fixes GH-2172
Signed-off-by: jbrundage <jbrundage372@gmail.com>
=> GH-2172 Added omitNullLatLong to map/Pins.js

src/amchart/CommonFunnel.js, src/amchart/CommonRadar.js, src/amchart/CommonSerial.js, src/amchart/CommonXY.js, src/amchart/Funnel.js, src/amchart/Pie.js, src/amchart/Pyramid.js
=> GH-2101 amCharts Tooltip number formatting

src/chart/XYAxis.js
=> GH-2179 XYAxis Range Selection Regression

src/composite/MegaChart.css, src/composite/MegaChart.js
Fixes GH-2189
@GordonSmith @jprichard Please review
Signed-off-by: jbrundage <jbrundage372@gmail.com>
=> GH-2189 Adds optional 'info' button to MegaChart

src/other/Table.js
Ensure row click is handled before cell click.
Fixes GH-2176
=> GH-2176 Table Click Regression

src/other/Comms.js
Fixes GH-2199
Signed-off-by: Jay Brundage jaman.brundage@lexisnexis.com
=> GH-2199 Resolves Max call stack issue within Comms.js

test/widgets.js
* Object.getOwnPropertySymbols
=> Omit handson test as phantomJS is missing an API call

src/chart/MultiChart.js, src/graph/Graph.js, src/marshaller/HipieDDL.js, test/marshallerFactory.js
DDL graph instances are not currently placed inside the Mega Chart.
Fixes GH-2190
=> GH-2190 DDL Graph + MegaChart

src/marshaller/HipieDDL.js
Add support for edge labels.
Fixes GH-2190
=> GH-2193 Graph edge missing label

src/marshaller/HipieDDL.js
=> GH-2211 Remove test code.

src/marshaller/HipieDDL.js
DDL not locating persisted widget correctly.
=> GH-2223 Persist restore + DDL failing

src/common/Database.js
=> GH-2230 Time masking fails if cell is numeric

packages/util/src/logging.ts
=> Comms/GH-3 Redirect Logging

src/composite/MegaChart.js
=> GH-2220 Max button should default to hidden

src/marshaller/HipieDDL.js, test/marshallerFactory.js
Switch to "-min", "-max", "-set"
Added logic to convert for local and Roxie.
Fixes GH-2231
=> GH-2231 Improved range filtering

src/marshaller/HipieDDL.js
=> GH-2237 Reorder sort + rollup calculations

src/marshaller/HipieDDL.js
"Fixing" the input filters for roxie query, cause commoned up WUID queries to fail.
Fixes GH-2252
=> GH-2252 WUID + Request optimisations

src/common/Database.js, src/marshaller/HipieDDL.js, src/other/Comms.js
Move sorting to after mappings.
Rollback previous stable nesting change.
Warn when WU is archived.
=> GH-2254 Sorting by calculated fields fails.

src/marshaller/HipieDDL.js
Form range fields were not being formatter for WU based dashboards.
Fixes GH-2269
=> GH-2269 Form range fields issue

src/map/ChoroplethCounties.js
=> GH-2278 US Counties and leading "0" in the FIPS.

src/chart/MultiChart.js
Test page:  http://rawgit.com/yangxulexis/Visualization/candidate-1.16.x/demos/dermatology.html?src/chart/MultiChart.flightPath&chartType=TABLE_PIVOT
=> Add pivot table to multichart.js to make it available on DSP

src/common/Utility.js, src/composite/MegaChart.js, src/marshaller/HipieDDL.js, src/other/Comms.js
Allow user to specify a template for the params section.
Fixes GH-2274
=> GH-2274 Marshaller Configurable Title params

src/api/IInput.js, src/form/Form.css, src/form/Form.js, src/form/Input.js
Show submit as default Button
Show focus on each from buttons
Show button as disabled more clearly
Enable submit button as user types
Fixes GH-2272
=> GH-2272 Import form visuals

src/map/GMapLayered.js, src/map/GMapPin.js, src/map/GMapPinLine.js
=> GH-2289 GMap Zoom to data

src/map/Pins.js, test/mapFactory.js
=> GH-2316 Adds d3-tip to map/Pins

src/composite/MegaChart.js
=> GH-2315 Adds optional data count to MegaChart toolbar

src/layout/Modal.css, src/layout/Modal.js, test/DataFactory.js, test/layoutFactory.js
This partially resolves one of the 10 items on "the list"
=> GH-2324 Adds Modal layout widget

src/chart/HexBin.js, src/chart/Pie.js, src/chart/Scatter.js, src/other/PropertyEditor.js
The 'range' input makes it quite a bit easier to test certain things.
=> GH-2328 Adds optional 'range' input for 'number' params

src/api/ITooltip.js, test/chartFactory.js
Fixes GH2313
http://rawgit.com/jbrundage/Visualization/GH2313_f/demos/dermatology.html?src/chart/Pie.true_false
=> GH-2313 Adds tooltipFormat support for opts.label of false

src/other/Comms.js
Regression introduced with:  https://github.com/hpcc-systems/Visualization/pull/2299
Fixes GH-2333
=> GH-2333 Range Filtering Fails for WU Based Dashboards

.gitignore, .travis.yml, package-lock.json, tests/test-amchart/package.json, tests/test-c3chart/package.json, tests/test-chart/package.json, tests/test-common/package.json, tests/test-comms/package.json, tests/test-composite/package.json, tests/test-dgrid/package.json, tests/test-form/package.json, tests/test-google/package.json, tests/test-graph/package.json, tests/test-handson/package.json, tests/test-layout/package.json, tests/test-loader/package.json, tests/test-map/package.json, tests/test-marshaller/package.json, tests/test-other/package.json, tests/test-react/package.json, tests/test-timeline/package.json, tests/test-tree/package.json, tests/test-util/package.json
Updated to latest travis version.
Enabled "sudo" in travis environment.
Added package-lock.json to repo.
=> Unit tests are failing on Travis

demos/dermatology/tests/DataFactory.js, demos/dermatology/tests/chartFactory.js, packages/chart/src/Axis.ts, packages/chart/src/Column.ts, packages/chart/src/HexBin.ts, packages/chart/src/Scatter.ts, packages/chart/src/XYAxis.ts, packages/common/src/PropertyExt.ts, packages/common/src/Widget.ts, tests/test-comms/src/ecl/topology.spec.ts
=> GH-2343 Overlay Charts

packages/ddl-shim/package.json, packages/ddl-shim/src/ddl.ts, packages/ddl-shim/src/ddl2.ts, packages/ddl-shim/src/index.ts, packages/dgrid/src/DatasourceStore.ts, packages/marshaller/rollup.config.js, packages/marshaller/src/ddl1/HipieDDL.ts, packages/marshaller/src/ddl2/activities/activity.ts, packages/marshaller/src/ddl2/activities/filter.ts, packages/marshaller/src/ddl2/activities/groupby.ts, packages/marshaller/src/ddl2/activities/hipiepipeline.ts, packages/marshaller/src/ddl2/activities/project.ts, packages/marshaller/src/ddl2/activities/roxie.ts, packages/marshaller/src/ddl2/activities/sort.ts, packages/marshaller/src/ddl2/activities/wuresult.ts, packages/marshaller/src/ddl2/ddl.ts, packages/marshaller/src/ddl2/ddlimport.ts, packages/marshaller/src/ddl2/graphadapter.ts, packages/marshaller/src/ddl2/javascriptadapter.ts, packages/marshaller/src/ddl2/model.ts
Add watch to ddl-shim build
Update DDL1 to latest samples
Update DDL2 to include range support
Rename namespaces to DDL1 and DDL2
Add validation methods to the activities
Add int64 support
Rename view to hipiePipeline
Fixes GH-2370
=> GH-2370 DDL Validation

package-lock.json, packages/dgrid-shim/package.json, packages/dgrid-shim/src/loaderConfig.js, packages/dgrid-shim/util/ScopedDojoRequire.js, packages/dgrid-shim/webpack.config.js, packages/dgrid/package.json, packages/dgrid/src/Common.ts, packages/dgrid/src/DBStore.ts, packages/dgrid/src/Table.ts
Add addition ESP data types.
Fixes GH-2368
=> GH-2368-DGrid Refresh Issue

packages/phosphor-shim/rollup.config.js, packages/phosphor-shim/src/index.ts, packages/phosphor/src/SplitPanel.ts, packages/phosphor/src/TabPanel.ts, packages/phosphor/src/WidgetAdapter.css, packages/phosphor/src/WidgetAdapter.ts, packages/phosphor/src/index.ts
=> GH-2365 Add Phosphor TabPanel

packages/ddl-shim/src/index.ts, packages/ddl-shim/src/upgrade.ts
=> GH-2374 DDL v1->v2 upgrade

demos/dermatology/tests/compositeFactory.js, demos/dermatology/tests/layoutFactory.js, demos/dermatology/www/index-dev.html, package-lock.json, packages/api/src/IHighlight.ts, packages/api/src/index.ts, packages/chart/src/Bubble.ts, packages/chart/src/Bullet.ts, packages/chart/src/Column.ts, packages/chart/src/Pie.ts, packages/chart/src/Scatter.ts, packages/common/src/Class.ts, packages/composite/src/ChartPanel.ts, packages/layout/package.json, packages/layout/src/Border2.ts, packages/layout/src/ChartPanel.css, packages/layout/src/ChartPanel.ts, packages/layout/src/Legend.ts, packages/other/package.json
Adds series classes on chart package widgets
Highlight series when mouse over legend items
Fixes GH-2342
=> GH-2342 Highlight series from legend

demos/dashy/src/index.ts, demos/dashy/src/sampleddl.ts, demos/dermatology/tests/compositeFactory.js, packages/common/src/PropertyExt.ts, packages/layout/src/ChartPanel.ts, packages/layout/src/Modal.ts, packages/layout/src/TitleBar.css, packages/layout/src/TitleBar.ts
Simplify titlebar and chartpanel interactions.
Remove double renders.
Fixes GH-2335
=> GH-2335 Add info button and popup to ChartPanel

demos/dashy/src/index.ts, packages/codemirror/package.json, packages/codemirror/rollup.config.js, packages/codemirror/src/XMLEditor.ts, packages/codemirror/src/index.ts, packages/marshaller/package.json, packages/marshaller/src/ddl2/ddleditor.ts, packages/marshaller/src/index.ts, tests/test-marshaller/package.json
=> GH-2364 Move DDLEditor into marshaller

.gitignore
=> Adds generated ddl schema files to gitignore

.vscode/launch.json
=> Adds updated vscode launch settings

demos/dermatology/tests/phosphorFactory.js, packages/phosphor/src/DockPanel.ts
=> Fixes DP tab drag issue and DP grid dermatology demo

packages/layout/src/ChartPanel.ts
=> Adds ChartPanel highlight

package-lock.json, packages/common/package.json
Force typings to version 1 (now d3-scale 2.x is relased).
Fixes GH-2402
=> GH-2402 Invalid d3-scale typings

.vscode/launch.json, demos/graph/canvas_test.html, demos/graph/canvas_test.js, demos/graph/css/canvas_test.css, src/common/CanvasWidget.js, src/graph/EdgeC.js, src/graph/GraphC.js, src/graph/Vertex.js, src/graph/VertexC.js, test/graphFactory.js
=> GH-2307 Adds GraphC

demos/dermatology/tests/mapFactory.js
Fix Choro States Heat Demo
Fix Layered + GMapLayered Demos.
Fixes GH-2414
=> GH-2414 Fix Map Demos

demos/dermatology/.vscode/launch.json, demos/dermatology/tests/compositeFactory.js, packages/common/src/ProgressBar.ts, packages/common/src/index.ts, packages/composite/src/ChartPanel.ts, packages/layout/src/ChartPanel.ts
Fixes GH-2336
Signed-off-by: Jaman <jbrundage372@gmail.com>
=> GH-2336 Add  progress bar to ChartPanel

src/chart/MultiChart.js
=> GH-2418 Add XML Tree to MultiChart

packages/comms/src/connection.ts, packages/comms/src/espConnection.ts, packages/comms/src/services/wsWorkunits.ts
Add loader to dev build
Fix dashy html
Fixes GH-394
=> GH-394 Add support for large XML Archives

packages/common/src/Class.ts, packages/comms/package.json, packages/comms/rollup.config.js, packages/comms/src/connection.ts, packages/comms/src/espConnection.ts, packages/comms/src/index.node.ts, packages/comms/src/index.ts, packages/loader/src/meta.ts, packages/util/src/debounce.ts, tests/test-comms/package.json, tests/test-comms/src/ecl/workunit.spec.ts
=> GH-2379 Comms use fetch instead of request

packages/dgrid/src/DatasourceStore.ts, packages/marshaller/src/ddl2/activities/activity.ts, packages/marshaller/src/ddl2/activities/databomb.ts, packages/marshaller/src/ddl2/activities/filter.ts, packages/marshaller/src/ddl2/activities/groupby.ts, packages/marshaller/src/ddl2/activities/hipiepipeline.ts, packages/marshaller/src/ddl2/activities/limit.ts, packages/marshaller/src/ddl2/activities/nullview.ts, packages/marshaller/src/ddl2/activities/project.ts, packages/marshaller/src/ddl2/activities/roxie.ts, packages/marshaller/src/ddl2/activities/sort.ts, packages/marshaller/src/ddl2/activities/wuresult.ts, packages/marshaller/src/ddl2/model.ts, packages/util/src/array.ts
Common up naming conventions
Add more functors to data pipeline
Fixes GH-2408
=> GH-2408 Optimize Pipeline

packages/comms/src/ecl/workunit.ts, tests/test-comms/src/ecl/workunit.spec.ts
=> GH-2429 Simplify access to ECL Exceptions

src/graph/GraphC.js, src/graph/VertexC.js
=> GH2435 Adds VertexC click events and font

src/graph/VertexC.js
=> GH2438 Adds VertexC anno font outside loop

src/graph/GraphC.js
=> GH2443 Adds drag logic to GraphC

demos/dermatology/tests/layoutFactory.js, packages/layout/src/Carousel.css, packages/layout/src/Carousel.ts, packages/layout/src/index.ts, tests/test-layout/src/layout.spec.ts
Add Carousel widget.
Fixes GH-2441
=> GH-2441 Carousel

packages/common/src/FAChar.ts, packages/common/src/HTMLWidget.ts, packages/common/src/Icon.ts, packages/common/src/PropertyExt.ts, packages/common/src/Shape.ts, packages/common/src/Text.ts, packages/common/src/TextBox.ts, packages/dgrid/src/Table.ts, packages/graph/src/Edge.ts, packages/graph/src/Vertex.ts, packages/layout/src/Border2.ts
Optimize primitive rendering.
Fixes GH-2448
=> GH-2448 Graph Optimizations

.gitignore
DSP development team is primary using intelliJ now for development so I've added to the .gitignore file .idea which will prevent any of the IDE project files from being committed
=> update git ignore to ignore intellij configuration

src/marshaller/HipieDDL.js
Marshaller is not extracting the correct mappings for slider.
Fixes GH-2454
=> GH-2454 Marshaller Slider issue

demos/dermatology/tests/chartFactory.js, package-lock.json, packages/chart/package.json, packages/chart/src/Gauge.ts, packages/chart/src/index.ts, packages/loader/src/meta.ts, tests/test-chart/src/chart.spec.ts
=> GH-2457 Gauge Widget

demos/WeCare/package.json, demos/WeCare/src/index.ts, demos/WeCare/webpack.config.js, packages/api/src/IInput.ts, packages/form/src/Button.ts, packages/form/src/CheckBox.ts, packages/form/src/ColorInput.ts, packages/form/src/Input.ts, packages/form/src/InputRange.ts, packages/form/src/OnOff.ts, packages/form/src/Radio.ts, packages/form/src/Range.ts, packages/form/src/Select.ts
Distinguish between keyup and tab off
Update WeCare to latest.
=> GH-2460 Add "complete" flag to form inputs

README.md
=> GH-2467 Update GitHub ReadMe file.

packages/map/src/GMap.ts, packages/map/src/GMapPin.ts, packages/map/src/Pins.ts
Street view on click fails when click is overloaded.
Fixes GH-2478
=> GH-2478 GMapPins has invalid SVG

demos/dermatology/tests/formFactory.js, packages/composite/src/MultiChart.ts, packages/form/src/FieldForm.ts, packages/form/src/Form.ts, packages/form/src/index.ts, tests/test-form/src/form.spec.ts
Add Form which is created from Field meta information.
Fixes GH-2480
=> GH-2480 FieldForm

demos/dashy/.vscode/launch.json, demos/dashy/style/index.css, demos/dermatology/tests/Factory.js, demos/dermatology/tests/eclwatchFactory.js, packages/comms/src/connection.ts, packages/util/src/debounce.ts
Add missing dermatology test page.
Fixes GH-2486
=> GH-2486 Reverse comms "omit" order.

packages/common/src/Icon.ts, packages/common/src/SVGWidget.ts, packages/common/src/SVGZoomWidget.ts, packages/common/src/Widget.ts, packages/graph/package.json, packages/graph/src/Edge.ts, packages/graph/src/Graph.ts, packages/graph/src/GraphData.ts, packages/graph/src/GraphLayouts.ts, packages/graph/src/Subgraph.css, packages/graph/src/Subgraph.ts, packages/graph/src/Vertex.ts, packages/graph/src/index.ts, packages/marshaller/src/dashy.ts
Add "left" icon position to Vertex
Improve edge hit detection
Update to latest dagre
Add buttons to change layout at runtime.
Use common tooltip widget
Fixes GH-2491
=> GH-2491 Add Subgraph Graph Widget

demos/dermatology/tests/chartFactory.js, packages/chart/src/SummaryC.ts, packages/chart/src/index.ts
Fixes #2494 
Signed-off-by: Jaman <jbrundage372@gmail.com>
=> GH2494 Adds SummaryC

packages/common/src/PropertyExt.ts, packages/react/src/Orb.ts
=> GH-2498 Standardize PP Tags

packages/dgrid-shim/package.json, packages/dgrid-shim/src/index.ts, packages/dgrid-shim/src/loaderConfig.js, packages/dgrid-shim/webpack.config.js, packages/dgrid/src/DBStore.ts
Pollutes global dojoConfig namespace.
Pollutes touch events.
Remove unneeded items from build.
Fixes GH-2505
=> GH-2505 DGrid-shim issues

demos/dermatology/tests/eclwatchFactory.js, packages/chart/src/Axis.ts, packages/common/src/Text.ts, packages/common/src/TextBox.ts, packages/comms/src/ecl/scope.ts, packages/eclwatch/src/WUScopeController.ts, packages/eclwatch/src/WUTimeline.ts, packages/eclwatch/src/index.ts, packages/timeline/src/MiniGantt.ts
Fix invalid SVG generation in Axis
Add types to Text widget anchor property
Expose WUScopeController
Refactor WUDetails tooltip generator
Move request structure into PP for WUTimeline
Fixes GH-2512
=> GH-2512 Generalize WUTimeline

packages/comms/src/clienttools/eclcc.ts, tests/test-comms/src/clienttools/eclcc.spec.ts, tests/test-comms/src/index.spec.ts
=> GH-2514 Add Win64 detection to ClientTools

packages/other/src/HeatMap.ts
=> GH2519 Changes HeatMap skewData to use size

packages/common/src/Widget.ts
=> GH2517 Adds lazyRender callback

packages/graph/src/Graph.ts
=> GH-2523 Graph default tooltip can cause exception

packages/layout/package.json, packages/layout/src/ChartPanel.ts, tests/test-composite/package.json, tests/test-layout/package.json, tests/test-other/package.json
Add button to chart panel to display the underlying data.
Fixes GH-2537
=> GH-2537 ChartPanel Data View

packages/common/src/Widget.ts
=> fix: Widget.LazyRender Broken

packages/phosphor/src/DockPanel.ts
Need to retest every render.
Only call refit if needed.
Fixes GH-2521
=> fix: Hide single tabs fix

packages/common/src/Widget.ts
=> feat: Prevent Render when hidden

packages/chart/src/Column.ts
=> feat: Add value text to Column/Bar chart

packages/ddl-shim/cli/index.ts, packages/ddl-shim/package.json, packages/ddl-shim/tsconfig-cli.json
=> feat:  Add cli options to ddl-shim

packages/dgrid/src/Common.ts, packages/dgrid/src/DBStore.ts, packages/dgrid/src/Table.ts
=> feat: Auto size columns on table load.

packages/ddl-shim/package.json
=> chore: Add "bin" to ddl-shim to make work with npx

demos/dashy/.vscode/launch.json, demos/dashy/index-dev.html, demos/dashy/src/index.ts, packages/dgrid-shim/package.json, packages/dgrid-shim/webpack.config.js, packages/loader/src/requirejs.ts
Also ensure it works with generic cdn.
=> fix: Ensure loader works with AMD and unpkg

packages/amchart/package.json, packages/api/package.json, packages/c3chart/package.json, packages/chart/package.json, packages/chart/src/XYAxis.ts, packages/common/package.json, packages/comms/src/ecl/workunit.ts, packages/comms/src/services/wsWorkunits.ts, packages/eclwatch/src/WUTimeline.ts, packages/map/package.json, packages/other/package.json, packages/react/package.json
=> feat:  Add ability to get a normalized array of WUDetail scopes

demos/dermatology/tests/timelineFactory.js, packages/eclwatch/src/WUGraph.ts, packages/eclwatch/src/WUScopeController.ts, packages/eclwatch/src/WUTimeline.ts, packages/graph/src/Graph.ts, packages/layout/src/Border2.ts, packages/timeline/src/MiniGantt.css, packages/timeline/src/MiniGantt.ts
Switched to use normal (row, col, sel) paradigm.
Added selection indicator.
=> fix: MiniGantt click event was non standard

demos/dashy/.vscode/launch.json, packages/ddl-shim/cli/index.ts, packages/ddl-shim/package.json, packages/ddl-shim/src/ddl.ts, packages/ddl-shim/src/upgrade.ts, packages/marshaller/src/dashy.ts, packages/marshaller/src/ddl2/activities/filter.ts, packages/marshaller/src/ddl2/javascriptadapter.ts
Added baseUrl and wuid options to upgrade cli
Filter validation was creating invalid string
Added DDL reference into generated TS
Fixes GH-2579
=> fix: DDL upgrade failing on SLIDER

packages/marshaller/src/ddl2/javascriptadapter.ts
=> fix: TS Form generation was invalid

packages/ddl-shim/src/ddl.ts, packages/ddl-shim/src/upgrade.ts
=> fix: DDL Upgrade Title and Properties are optional

packages/marshaller/src/dashy.ts
=> fix: Dashy calls render prior to the widget being added to the DOM

packages/comms/src/clienttools/eclMeta.ts, packages/comms/src/clienttools/eclcc.ts
=> feat: Include list of checked files during syntax check

packages/comms/src/clienttools/eclMeta.ts, packages/comms/src/clienttools/eclcc.ts, packages/comms/src/index.node.ts, tests/test-comms/src/clienttools/eclcc.spec.ts
=> fix: Auto eclcc seleciton based on build version

packages/comms/src/index-common.ts, packages/comms/src/services/wsAccount.ts
=> feat: Add support for WsAccounts + Verfiy User

apps/dashPOC/.vscode/launch.json, apps/dashPOC/index.html, apps/dashPOC/package.json, apps/dashPOC/rollup.config.js, apps/dashPOC/src/dashPOC.ts, apps/dashPOC/src/hookSend.ts, apps/dashPOC/src/index.ts, apps/dashPOC/style/index.css, apps/dashPOC/tsconfig.json, apps/dashPOC/webpack.config.js
=> chore: Add DashPOC test app

demos/dermatology/tests/commonFactory.js, packages/common/src/HTMLWidget.ts, packages/common/src/Icon.ts, packages/common/src/SVGWidget.ts, packages/common/src/Text.ts, packages/common/src/TextBox.ts, packages/common/src/Widget.ts, packages/graph/src/Subgraph.ts, packages/graph/src/Vertex.ts
Use calculated values in preference to DOM calls.
Fixes GH-2567
=> fix: Optimize getBBox calls

packages/layout/src/ChartPanel.ts
=> feat: ChartPanel title hide and overlay options

tests/test-common/src/common.spec.ts, tests/test-common/src/index.spec.ts
=> chore: Add missing entity tests

packages/ddl-shim/src/upgrade.ts
Introduced with:  https://github.com/hpcc-systems/Visualization/pull/2582
=> fix: Output ID was wrong

packages/marshaller/src/dashy.ts
=> fix: Add missing save method to dashy

packages/common/src/TitleBar.ts
=> fix: Icon bar buttons should not cause navigation

tests/test-comms/src/clienttools/eclcc.spec.ts, tests/test-comms/src/clienttools/some.ecl
=> chore: Add test for client tools
