widgets/src/graph/Graph.js

Resizing a surface in a graph does not refresh edges in IE

---

widgets/src/common/Menu.js
widgets/src/common/Surface.js
widgets/src/graph/Graph.js

Only listen for body events while menu is visible.
No reason for vertex clicks to prevent propagation.
Fixes #171

GH-171 Resizing surface while menu is open causes title bar to resize

---

demos/dermatology.html

Dermatology fails to load when opened in web browser with no web server.

---

widgets/src/other/Comms.js

URL Params should be URI decoded before being used.

---

widgets/src/marshaller/Graph.js
widgets/src/marshaller/HTML.js

If no databomb is specified, it causes an error.

Databomb Regression

---

demos/dashboard/app/tpl/Main.html
widgets/src/marshaller/HipieDDL.js

If a datasource update has been triggered by a onSelect event, then the list
of visualizations that are updated by the new data is limited to the list of
visualizations that the onSelect specifies.

Limit scope of onSelect updates.

---

src/c3chart/Common.js

Should we place the legend position in each widget instead of common? (or perhaps in the non-1d Common(s)) ?

Fixes C3 Gauge Cut-off #291

---

gulpfile.js

Travis-CI will report as failed if there are any linting errors.

Report Lint Errors as Error

---

src/common/Icon.js

Formal click event for Icon

---

demos/dermatology.html
src/other/Slider.css
src/other/Slider.js

This is in reference to #353.
@GordonSmith @mlzummo  Please review.
This adds a play and a loop button to the slider.
The buttons don't appear as of now on the rawgit link, becuase the styles override the FontAwesome style with Verdana. #406 fixes this issue.
Demo at : http://rawgit.com/anmoljagetia/Visualization/playSlider2/demos/dermatology.html
Also, I am looking for a better commit message, and squashing all the commits into one? does "Adds the ability to play or loop GH-353" look plausible?

Adds the play button to the slider

---

src/other/Table.css
src/other/Table.js

@GordonSmith @mlzummo Please review!
Adds the ability to sort the data in the table based on column selected. 
Demo at : http://rawgit.com/anmoljagetia/Visualization/tableSort/demos/dermatology.html?src/other/Table

Adds the ability to sort table data

---

bower.json
gulpfile.js

Added missing plugin dependencies.
Swicthed to "patched" plugins (fixed to support DOJO AMD).

ECLWatch Support

---

src/other/Table.css
src/other/Table.js

@GordonSmith @mlzummo Please review!
Fixes GH-427

Adds Multiselect to the Table Widget

---

src/chart/Column.css
src/chart/XYAxis.js

@GordonSmith Please Review.
Refactors XYAxis to have dataAxis and columnAxis instead of xAxis and yAxis.

Refactors X and Y to Data & Column in XYAxis

---

demos/dermatology.html
src/api/INDChart.js
src/chart/Scatter.css
src/chart/Scatter.js

@GordonSmith @mlzummo Please review.
Demo at : http://rawgit.com/anmoljagetia/Visualization/scatterPlot/demos/dermatology.html?src/chart/Scatter
Fixed GH-495

GH-495 Adds the Scatter Chart

---

src/chart/Column.js

GH-521 Adds N-D Data to Column Chart

---

src/chart/Column.js
src/chart/XYAxis.js

#538.
@GordonSmith @mlzummo Please Review.

GH-538 Adds support for range of data in the Column Chart

---

src/chart/XYAxis.js

Do not attempt to format "null/undefined/empty" values.
Fixes GH-619

GH-619 "null" values and "Date" values causes errors.

---

src/other/Persist.js

Fixes GH-573
This applies to deserializing "widget" type publish parameters.

GH-573 Persist now uses correct key for "widget" param deserialize

---

src/other/Table.js

Adding/removing or editing the columns will cause them to lose their correct order.
Fixes GH-582

GH-582 Table columns render in wrong sequence

---

src/chart/MultiChart.js

MultiChart can corrupt display by re-using charts.

---

src/layout/Grid.css
src/layout/Grid.js
src/layout/Surface.js
src/other/PropertyEditor.js

Design Mode dropCells are now drawn with a canvas element. This allows it to load much faster and support any realistic number of columns/rows without lag.
Three new publish params:
extraDesignModeWidth - offers control of the number of additional columns added in designMode
extraDesignModeHeight - offers control of the number of additional rows added in designMode
cellDensity - offers control of the number of cells per standard cell

Optimizes Grid designMode

---

src/c3chart/Area.js
src/common/Surface.js
src/common/Text.js
src/other/PropertyEditor.js
test/widgets.js

When exclude tags are changed at the root level, it should force a re-calc of
the property editor tree.
Fixes GH-768

GH-768 PropertyEditor excl tags do not propagate

---

src/common/Widget.js

Published arrays need to be initialized at construction otherwise the default array in the __meta_ will be used as a Class Static instance (shared by all).

Published Array Initialization

---

src/marshaller/HipieDDL.js

Sorting assumed data was numeric (fine for charts, not for Table).
Fixes GH-722

GH-722 Sort not working for strings

---

src/google/Common.js

@GordonSmith @dineshshetye Please Review
Fixes draw error thrown by google when draw is initialized for the first time before it can be converted to a google dataArray obj
Fixes GH-823

GH-823 GOOGLE DRAW ERROR

---

src/other/Persist.js
test/persist.js
test/runner.html

Serializing too much, should only do one level at a time.
Fixes GH-820

GH-820 Property Walker Serialization Issue

---

demos/dermatology.html
src/other/PropertyEditor.js

Fixes GH-455
An array of publish param IDs can be passed to PropertyEditor.showProperties() to restrict all other publish parameters from displaying in the PropertyEditor.
@prakash-sukumar @GordonSmith Please Review

GH-455 Adds showProperties to PropertyEditor

---

src/common/Widget.js

Not hiding 100% on FF when menu is selected.
Fixes GH-806

GH-806 C3 Charts + MultiChartSurface

---

src/chart/Column.js

Column can use out of date info for the tooltip and click events.
Fixes GH-891

GH-891 Column Tooltip/Click Issue

---

src/marshaller/HipieDDL.js

_changed was being set based on the previous request.  It needs also take into
consideration which widget triggers the request (both might send in the same
value, but the updates will be different).
Fixes GH-909

GH-909 HipieDDL _changed flag is set incorrectly

---

demos/test-no-amd.html
src/google/Bar.js
src/google/Common.js
src/google/Line.js
src/google/Scatter.js
test/runner_build_nonamd.html

Updates Google Bar/Column, Line and Scatter charts to latest Google Material Charts version.  Implements the "axes" and "series" options to create dual-y axes.
Fixes GH-749

GH-749 Add Second Y Axis to Google Charts

---

apps/SampleSite/legend.html
demos/dermatology.html
src/layout/Border.js
src/layout/Grid.js
src/layout/Layered.js
src/layout/Tabbed.js

Fixes GH-946
The **padding** and **cellPadding** publish params have been renamed to **surfacePadding**. 
Note: The Layered and Tabbed layouts currently don't use Surface objects. If you'd prefer a different name because of that fact, that's understandable. Otherwise, **surfacePadding** is a clear indication of functionality.

GH-946 Standardizes layout padding params

---

src/other/Comms.js

Should fallback to case insensitive field matching.
Fixes GH-964

GH-964 WU Filtering Field IDs

---

src/other/PropertyEditor.js

Fixes GH-1002
Converts two for ... in loops to for(var x=0;x<arr.length;x++) loops to resolve a JS conflict with a one of DSP's js framework files.
@mlzummo @GordonSmith @dtsnell4 @jchambers-ln
More can be read about it here:
http://stackoverflow.com/questions/8262128/javascript-for-loop-returning-key-indexof

GH-1002 Fixes PropEdit looping bug in DSP

---

src/c3chart/CommonND.js

Fixes GH-980
@GordonSmith @mlzummo @dtsnell4 Please Review
All C3 charts should now appropriately change color when the paletteID is changed (not requiring multiple updates before displaying the color change).
http://rawgit.com/jbrundage/Visualization/GH-980-C3ChartColors/demos/dermatology.html?src/c3chart/Line

GH-980 Sets paletteID before C3 common update

---

src/layout/Popup.js
test/layoutFactory.js

Changes the way the Popup widget shows and hides content from "display: none|block;" to the Widget prototype's ".visible(true|false)" method.  Also removes the test button code from the Popup widget file.
Fixes GH-997
Signed-off-by: Dan Snell <dan.snell@lexisnexis.com>

GH-997 Popup Widget Display/Hide

---

src/other/WordCloud.js

Adds WordCloud Zoom Support
Fixes GH-971
Doesnt zoom unless you mouse over a word ... not sure if we want it to behave like that or not?

GH-971 WordCloud Zoom

---

src/api/ITooltip.js
src/common/Menu.js
src/common/Widget.js
src/layout/Tabbed.js
test/layoutFactory.js

Changes the way tabs are hidden from "display: none/block" to using the Widget.prototype.visible(). Only the currently displayed widget is resized.
Fixes GH-914

GH-914 Switching tabs slow and resizes widget

---

src/other/Table.js

For MegaChart/Border Widget shrinkWrap feature. Previous the table would only accept dimensions in pixels. 
Fixes GH-1123

GH-1123 Table Widget - allow for size of 100%

---

src/google/Area.js
src/google/Bar.js
src/google/Column.js

Area, Bar and Column charts were incorrectly returning a "stacked" property to the Google chart.  This property is actually called "isStacked".
The HPCC publish parameter remains "stacked"
Fixes GH-1127

GH-1127 Google Stacked Property

---

src/layout/Tabbed.css
src/layout/Tabbed.js

Add a publish parameter to place the tabs underneath the widgets instead of on top. Uses absolute positioning to place the tabs container.
Fixes GH-1148

GH-1148 Tabs on Bottom

---

src/amchart/CommonFunnel.js
src/amchart/CommonRadar.js
src/amchart/CommonSerial.js
src/amchart/CommonXY.js
src/amchart/Gantt.js
src/amchart/Pie.js

@GordonSmith @dtsnell4 @jbrundage  - Please Review
Allows amcharts to persist selections on update if data has not been updated
Fixes GH-1144

GH-1144 AmChart Select Persist Fix

---

src/composite/MegaChart.js
src/other/Table.css
src/other/Table.js
test/otherFactory.js

Refactors Table Widget to remove all copying javascript for the fixed header and first column. Makes widget all d3js.  Adds code to deselect a selected row(s) in the table.  Adds paginationLimit() publish parameter to automatically turn on pagination when a developer-defined number of rows is reached.
Fixes GH-1140
Fixes GH-1175
Fixes GH-1176

GH-1175 Refactor Table Widget

---

src/common/Shape.js
src/common/Text.js
src/common/TextBox.js
src/graph/Edge.css
src/graph/Edge.js
src/graph/Graph.css
src/graph/Graph.js
src/graph/Vertex.js

Text Widget would not show duplicate lines.
Text Widget would not maintain correct order.
Added tooltip support to:
* Shape, TextBox, Vertex, Edge
Added selection support for edges.
Reversed scroll wheel and ctrl+scroll wheel behaviour.

Tweaks for HPCC ECL Watch

---

src/common/Utility.js
src/common/Widget.js
src/layout/Surface.css
src/layout/Surface.js
test/DataFactory.js
test/commonFactory.js

Adds an Exporter widget so that  any widget can export its data to CSV, TSV, or JSON formats, and save as a file.
Fixes GH-1005

GH-1005 Export Option on Table Widget

---

src/other/Table.js

Widget was skipping applyStyleToRows() unless fixedColumn() was set to true.  Rearranged code accordingly
Fixes GH-1286.

GH-1286 Table- some row color params are only applied if fixedColumn() = true

---

src/google/Common.js
src/google/Common2D.js
src/google/CommonND.js
src/google/MaterialBar.js
test/googleFactory.js

Hack to work around google webfont issue:  https://github.com/typekit/webfontloader/issues/278
Fixes GH-995

GH-995 RequireJS + Google Material Charts

---

src/layout/Grid.css
src/layout/Grid.js

Fixes GH-1275
Cells are now selected when the user single-clicks a cell (without dragging the mouse).
Clicking a selected cell now deselects that cell.
Control+Click still allows the user to select multiple Cells (Control+Clicking on a cell appends that cell to the selection bag).
http://rawgit.com/jbrundage/Visualization/GH-1275/demos/dermatology.html?src/layout/Grid&designMode=true

GH-1275 Improves Grid Cell selection

---

src/layout/Popup.js
test/layoutFactory.js

Adds shrinkWrap() parameter that resizes the popup around its content widget if it has an explicit size.
Also adds the centerPopup() parameter which will center the popup in its container, or in the window.
Fixes GH-1195

GH-1195 Popup Layout needs shrink to fit option

---

.jshintrc
src/composite/MegaChart.js
src/map/Layered.js
src/marshaller/HTML.js
src/marshaller/HipieDDL.js
src/other/Persist.js

HTML marshaller incorrectly included itself in the "existing widgets" array.
Choropeths throw exception if asked to render before being placed in a target (highlighted by the above).
Minor refactor of MargaChart chartTypeProperties handling.
Fixes GH-1356

GH-1356 Marshaller Regression (GH-1320, GH-1316)

---

src/composite/MegaChart.js
src/layout/Surface.css
src/other/Toolbar.css
src/other/Toolbar.js
test/DataFactory.js
test/otherFactory.js

Fixes GH-1199
Also adds the Toolbar widget as a part of the MegaChart displaying a select input to allow the user to change the chartType.
http://rawgit.com/jbrundage/Visualization/Adds_Toolbar/demos/dermatology.html?src/composite/MegaChart
@GordonSmith I used the new Toolbar widget to add a Select element at the top of the MegaChart widget allowing the users to easily switch between chart types.
I rebased this branch onto @mlzummo GH-1229 so I could use his Select widget instead of the Input widget.

GH-1199 Adds Toolbar widget

---

src/composite/MegaChart.js

The marshaller won't attach a click handler, if the chart does not have a default one already.

GH-1370 MegaChart missing click handler

---

src/other/Comms.js

Allow JS casting when comparing filter fields.
Fixes GH-1414

GH-1414 Local filtering should allow casting

---

src/chart/MultiChart.js
src/common/PropertyExt.js

Switch MultiChart from a SVGWidget to a HTMLWidget to prevent unnecessary usage of the polyfil Mutation Observer (which is is "slow").
Fixes GH-1382

GH-1382 IE9/10 Performance Issue

---

src/marshaller/HipieDDL.js

Check for missing data during the mapping process for graphs.
Fixes GH-1339

GH-1339 Graph displays "undefined" instead of ""

---

src/c3chart/Common.js
test/c3chartFactory.js

If render is called while the previous render is still "transitioning", then the corruption can occur.
Fixes GH-1399

GH-1399 C3Charts can corrupt

---

src/chart/MultiChart.js
src/composite/MegaChart.js
src/marshaller/HipieDDL.js
src/other/Persist.js

Not backward compatible with persist strings that cave no fields.
Fixes GH-1458

GH-1458 Field Persist Issues

---

src/chart/MultiChart.js
src/common/Widget.js

As chart is a PP it gets rendered by Widget.js already.
Fixes GH-1475

GH-1475 MultiChart Double Render

---

src/common/PropertyExt.js
src/marshaller/HipieDDL.js

Sort data before mapping it.
Force null to undefined for default optional properties.
Fixes GH-1535

GH-1535 DDL sorts wrong column

---

src/map/ChoroplethCounties.js

Optionally convert fips code to a string with leading zeros for the click event.
Fixes GH-1552

GH-1552 convert FIPS to string on click

---

src/c3chart/Donut.js

Allow title to be changed at runtime.
Fix properties being set _after_ render.
Fixes GH-1629

GH-1629 Default c3 donut title to blank

---

src/loader.js

am charts "shims" are not being called when hosted on rawgit.
Fixes GH-1641

GH-1641 AM Charts + rawgit

---

src/chart/BulletChart.js
test/runner_build_nonamd.html

non-amd build test failing
D3 Bullet constructor not used.

1.12 Merge Conflicts

---

src/common/Database.js
src/marshaller/HipieDDL.js

Persisted widgets need to "merge" in column changes (specifically removals)
Fixes GH-1674

GH-1674 DDL Column Change

---

src/common/PropertyExt.js

Was converting to '"undefined"' for strings.
Fixes GH-1717

GH-1717 Setting optional PP as undefined

---

src/common/Database.js
src/marshaller/HTML.js
src/marshaller/HipieDDL.js

Insert place-holders when response data is missing.
Fixes GH-1743

GH-1743 HIPIE Responses may omit data fields

---

src/marshaller/HipieDDL.js
test/marshallerFactory.js

Graph edge mapping use their own mapping stucture and not the vertex mappings.
Fixes GH-1745

GH-1745 Graph Edge Mappings Fail

---

src/marshaller/HipieDDL.js

Ignore datasource.output.filter for the purpose of initial render.
Fixes GH-1770

GH-1770 datasource.output.filter invalid

---

gulpfile.js

d3-bullet must be loaded after d3
Fixes GH-1817

GH-1817 Bundle Race Condition

---

src/marshaller/HipieDDL.js

Merge the DDL columns with Persist Columns prior to initial render.
Fixes GH-1828

GH-1828 DDL Columns v Persist Columns

---

src/marshaller/HipieDDL.js
test/marshallerFactory.js

When two widgets update a third by the same field ID, the wrong filter value
can be used.
Fixes GH-1758

GH-1758 Duplicate filter input issue

---

src/map/GMap.js

Initial render arrives too early?
Fixes GH-1855

GH-1855 GMap + Pins initial render in FF

---

src/chart/Axis.js
src/chart/Column.js
src/chart/XYAxis.js
src/common/Platform.js

Stack values instead of overlaying them.
Prevent axis extend from crossing the 0 barrier
Fix tooltips on ranged column charts
Fixes GH-1424

GH-1424 Stacked Column

---

src/other/PropertyEditor.js

This allows tooltips to appear in the property editor, sourced from the property descriptions.

Added title attribute to property editor rows

---

src/marshaller/HipieDDL.js

Clear all visualization before calculating their default states
Fixes GH-1918

GH-1918 Default values ignored during primeData

---

src/map/TopoJSONChoropleth.js
src/other/WordCloud.js

Two visualizations still have legacy tooltip code.
Fixes GH-1929

GH-1929 Legacy Tooltip Code

---

src/loader.js
test/loader.js

Add ability to replace viz.hpccsystems.com with an alternative source.
Fixes GH-1932

GH-1932 Override default CDN host

---

src/marshaller/FlyoutButton.js
src/marshaller/HipieDDLMixin.js

Workaround issue by opening the single instance of the form.
Fixes GH-1953

GH-1953 Flyout form + multiple targets

---

src/common/Widget.js

GH-1963 locateParentWidget fails when _target is not set

---

src/marshaller/HipieDDL.js
test/marshallerFactory.js

Check for NULL data prior to instantiating the nested Table.
Field order and mapping order can be different now.
Fixes GH-1954

GH-1954 Nested Table + no data

---

src/marshaller/HipieDDL.js

Propagate clear needs a corresponding propagate update (otherwise the clear is not rendered).
Fixes GH-1971

GH-1971 Propagate Clear Render Issue

---

src/marshaller/HipieDDL.js

Race condition allows wrong response to be forwarded to visualizations.
Fixes GH-2004

GH-2004 Response transaction sync issue

---

src/marshaller/HipieDDL.js
test/marshallerFactory.js

During initial load change logic to give preference over inputs with default values.
Then fallback to default call for roxie queries and widgets with no inputs.
Fixes GH-2164

GH-2164 PrimeData Logic Priorities

---

src/c3chart/Donut.js
src/c3chart/Pie.js

When legend filtering alters the visible rows (rather than columns), then
d.index will be incorrect during the selection.

GH-2197 C3 Legend Filtering Issue

---

src/common/Database.js
src/marshaller/HipieDDL.js

Previous fix, didn't work 100%.  Rolled back change and fixed by ensuring
d3.nest is "stable".
Fixes GH-2246

GH-2246 Sort + aggregated fields broken

---

src/other/Comms.js

On deselection we expect the changed field to be "undefined"
Fixes GH-2264

GH-2264 Select/deselect issue

---

src/chart/MultiChart.js
src/composite/MegaChart.js
src/graph/Graph.js
src/marshaller/HipieDDL.js

Graph events not being propogated through MutliChart and MegaChart.
Graph layout tick can be called even after stop() has been called.
Fixes GH-2287

GH-2287 Graph events and MutliChart / MegaChart

---

src/other/Comms.js

WUID request ignores declared filters when there is no selection.
Fixes GH-2298

GH-2298 De-selected filter issue.

---

src/layout/Grid.js

d3 drag handler prevents text selection in contained widgets.
Fixes GH-2292

GH-2292 Grid prevents text selection

---

src/amchart/CommonSerial.js

Ensure deselecting an item in AM Charts returns "false"
Fixes GH-2293

GH-2293 AM charts deselection issue

---

package.json

Don't use global versions of gulp and bower to ensure which version is used.
Update gulp-git to work with node v8.x.x

Legacy Build

---

src/graph/Graph.js

Evidently IE10 didn't like setting the contents of an svg filter element using `.html()`
Fixes GH-2400

GH-2400 Fixes graphGraph centroid filter in IE10

---

packages/common/src/FAChar.ts

Since the fonts will get pulled relative to the host web page and not the
bundle, it can never work in a "prod" environment.

GH-2372 Remove FA from common bundle

---

packages/layout/src/Layered.css

layout/Layered incorrectly disables SVG widget mouse events.

GH-2426 layout/Layered SVG mouse events

---

packages/ddl-shim/src/ddl.ts

REAL4, REAL8, INTEGER4, INTEGER8
viz.source.first can be a string.

GH-2469 Add missing types to DDL1

---

packages/other/src/CalendarHeatMap.ts

CHeck if any columns are set prior to aggregates.
Fixes GH-2473

GH-2473 CalendarHeatMap Invalid Formatting

---

packages/layout/src/ChartPanel.ts
packages/layout/src/Legend.ts

Switch ChartPanel and Legend to use Fields instead of Columns.
Legend should not show fields that start with "__".
Fixes GH-2475

GH-2475 ChartPanel + Legend use Fields

---

packages/common/src/Widget.ts

Should hide the element and not the placeholder element.
Fixes GH-2500

GH-2500 Widget.visible issue

---

packages/phosphor/src/DockPanel.css
packages/phosphor/src/DockPanel.ts

Optionally hide single tabs in docking panels.
Fixes GH-2521

GH-2521 DockPanel Hide Single Tabs

---

package.json

Add new option to test a publish without updating git + npm
Start using Conventional Commits (https://conventionalcommits.org/)

refactor:  Lerna publish call

---

packages/dgrid/src/DBStore.ts

fix:  DGrid table sorting fails when undefined cells exist

---

packages/ddl-shim/src/ddl2.ts
packages/ddl-shim/src/upgrade.ts
packages/marshaller/src/dashy.ts
packages/marshaller/src/ddl2/activities/databomb.ts
packages/marshaller/src/ddl2/activities/sort.ts
packages/marshaller/src/ddl2/ddl.ts

While not strictly needed it helps with the Java code generation.
Add known fields to the outputs during update.

fix:  Add extra references to assist the DDL2 schema generation

---

packages/common/package.json

chore: Lock down d3-dsv type information

---

packages/comms/src/clienttools/eclcc.ts

Fails to set the working dir correctly.

fix: locate client tools fails when exact match

---

packages/comms/src/clienttools/eclcc.ts

fix(Syntax Check): ECL Error Parser could not handle "C:\"

---

packages/common/src/Widget.css

Hide the canvas div used to calculate the text sizes.

fix(eclwatch): Hide canvas text Calculator

---

.vscode/launch.json
demos/dermatology/index.html

FF doesn't support window.location.origin
Also updated VSCode launch file to use the new dermatology/index.html path

fix(FF): Dermatology window.location.protocol

---

packages/marshaller/src/index.ts

If a consumer is using the marshaller and a different version of comms, then they had no way of hooking the marshaller comms layer.

feat(comms): Export hookSend from marshaller

---

packages/ddl-shim/package.json
packages/ddl-shim/tsconfig-cli.json

cli version should include tslib functions via importHelpers=false

fix(ddl-shim): npx @hpcc-js/ddl-shim fails with missing module "tslib"

---

packages/api/src/Tooltip.ts

The new tooltip code doesn't need scrollTop and scrollLeft because it's relative to a container now.

fix(tooltip): Removed scrollTop and scrollLeft

---

packages/api/src/ITooltip.ts
packages/map/src/Pins.css
packages/map/src/Pins.ts

Pins had hard coded black stroke, preventing selection from showing.
Selection would get out of sync on re-render.
Fixes GH-2796

fix(GMapPin): Tooltips broken on layered surfaces

---

packages/dgrid/src/Table.ts

It can be very slow, so the onus is on the caller to call it sensibly.  This is inline with all the other visualizations.

fix(table): Remove check for data change from table

---

packages/phosphor/src/DockPanel.ts

fix(DockPanel): DockPanel.render not rendering internal widgets

---

packages/graph/src/Graph.ts

Calculate delta between the mouse down and vertex x,y
Fixes GH-2931

fix(Graph): Dragging Vertex causes it to snap to mouse position

---

packages/graph/src/Graph.ts
packages/graph/src/Vertex.ts

If the user has set a pos for a Vertex, use it as its starting position.

fix(graph): Use Vertex.pos as starting position

---

packages/ddl-shim/src/upgrade.ts

fix(ddl): Don't convert FAChar hex values to chars

---

packages/chart/src/XYAxis.ts
packages/common/src/SVGWidget.ts

Applying a non existent selection filter causes element to be hidden

fix(chart): X-Axis focus hiding columns

---

demos/dashy/src/index.ts
packages/marshaller/src/ddl2/activities/roxie.ts
packages/marshaller/src/ddl2/activities/wuresult.ts
packages/util/src/debounce.ts
tests/test-util/src/debounce.spec.ts

Service calls need to preserve order they were called in, otherwise clicks could get out of sync.
Fixes GH-3106

fix(marshaller): Race condition

---

packages/api/src/ITooltip.ts
packages/api/src/Tooltip.ts

fix(tooltip): Re-targeted widgets lose tooltip styling

---

src/common/Utility.js

Tested the change in isolation. 
#3150 was created to track the possibility that other characters should be supported as well.

fix: ddlParamsFormat now allows spaces

---

packages/eclwatch/src/WUTimeline.ts

Signed-off-by: Gavin Halliday <gavin.halliday@lexisnexis.com>

fix(eclwatch): Avoid accessing detailed subgraph stats for graph Timeline

---

packages/map/src/leaflet/GMap.ts

I tested this using `map/dist/index.js` and some styles from snazzy maps. It only works on the initial render call, but it's better than not working at all.

feat(map): Add GMap styling to leaflet/GMap.ts

---

packages/dgrid/src/Common.ts

dgrid has intermittent crash, when moved from div to div.

fix(dgrid): Exit/Enter/Update Issue

---

demos/gallery/samples/chart/dataMeta/PieColumn.js
packages/chart/src/Column.ts
packages/chart/src/Pie.ts
packages/common/src/Widget.ts

Add support for dataMeta.sum to Column.ts and Pie.ts
Fixes #3189
Tested in gallery and dermatology

feat: Add dataMeta to Widget.ts

---

packages/chart/src/XYAxis.ts
tests/test-util/src/types.spec.ts

pointSizeColumn is now optional
Fixed an issue with yAxisTypeLogBase
I created a diff of the output of this code snippet before and after this PR's code change.
```javascript
import { XYAxis } from "@hpcc-js/chart";
const a = new XYAxis();
console.log(JSON.stringify(a._publishedProperties, null, "  "))
```
Here's the diff: https://gist.github.com/jbrundage/de8d813f629f0da02fd8fce661f4d829/revisions?diff=unified#diff-90926d6e3c250de42124b3f713fed614

chore(chart): Add XYAxis interface for publish properties

---

src/common/Utility.js

Tested a few template strings directly

feat: template can use parens to removeHTMLFromString

---

package-lock.json
packages/api/package.json
packages/api/src/ITooltip.ts
packages/chart/package.json
packages/codemirror-shim/package.json
packages/codemirror/package.json
packages/common/package.json
packages/comms/package.json
packages/composite/package.json
packages/ddl-shim/package.json
packages/dgrid-shim/package.json
packages/dgrid/package.json
packages/eclwatch/package.json
packages/form/package.json
packages/graph/package.json
packages/html/package.json
packages/layout/package.json
packages/loader/package.json
packages/map/package.json
packages/marshaller/package.json
packages/other/package.json
packages/phosphor-shim/package.json
packages/phosphor/package.json
packages/preact-shim/package.json
packages/react/package.json
packages/timeline/package.json
packages/tree/package.json
packages/util/package.json

Fix spurious deprecation warning

chore(build): Bump lint version

---

packages/comms/src/ecl/workunit.ts

UI should be responsible for interpreting the information.

fix(Workunit): Simplify response handling

---

src/chart/MultiChart.js
src/composite/MegaChart.js
src/other/Legend.js
test/compositeFactory.js

Fixes #3324
I've tested this in the dermatology editor and there are two edge case issues that can be experienced, but they may not be worth addressing in this pull request as this is an opt-in feature that will be primarily used on `PIE`. 
First issue: 
1) enable the `hideRowOnLegendClick` feature
2) hide a row
3) switch chart types
4) the previously hidden row is now missing from the dataset
Second issue:
1) change `chartType` to an ND chart
2) enable the `hideRowOnLegendClick` feature
3) click a legend label
4) a "row" is now missing (corresponding to the clicked legend index)... legend labels are based on "column"s for ND charts

feat(v1): Add filter by Legend click

---

packages/common/src/SVGWidget.ts

This will cause the page to "hard reload".
Fixes #3347

fix(SVGWidget): Incomplete feColorMatrix node can cause IE/Edge to crash

---

demos/gallery/samples/chart/Gantt/Gantt.js

fix(demo): Gantt demo missing yAxisType of "time"

---

demos/gallery/samples/codemirror/CSSEditor.js
demos/gallery/samples/codemirror/DOT Editor.js
demos/gallery/samples/codemirror/ECLEditor.js
demos/gallery/samples/codemirror/HTMLEditor.js
demos/gallery/samples/codemirror/JSEditor.js
demos/gallery/samples/codemirror/MarkdownEditor.js
demos/gallery/samples/codemirror/XMLEditor.js

Tweaked other codemirror samples for consistency

fix(gallery): Codemirror markdown sample display incorrectly

---

packages/comms/src/clienttools/eclcc.ts
tests/test-comms/src/clienttools/eclcc.spec.ts

Error parsing fails when there is a space in the path.

fix(eclcc): Syntax Error Parse Issue

---

demos/dermatology/tests/chartFactory.js
demos/gallery/samples/other/QuartileCandlestick.js
packages/chart/docs/QuartileCandlestick.md
packages/chart/src/QuartileCandlestick.ts

Add QuartileCandlestick to chartFactory.js
Prevent text overlap in QuartileCandlestick

feat(docs): Add QuartileCandlestick md

---

packages/api/rollup.config.js
packages/chart/rollup.config.js
packages/codemirror/rollup.config.js
packages/composite/rollup.config.js
packages/dgrid/rollup.config.js
packages/eclwatch/rollup.config.js
packages/form/rollup.config.js
packages/graph/rollup.config.js
packages/html/rollup.config.js
packages/layout/rollup.config.js
packages/map/rollup.config.js
packages/map/tsconfig.json
packages/marshaller/rollup.config.js
packages/other/rollup.config.js
packages/phosphor/rollup.config.js
packages/react/rollup.config.js
packages/timeline/rollup.config.js
packages/tree/rollup.config.js

Note:  d3.event needs to be a global singleton

fix(build): Remove duplicate d3 packages from bundles

---

packages/chart/docs/RadialBar.md
packages/chart/src/RadialBar.ts

Fixed issue that was affecting RadialBar valueMaxAngle accuracy

feat(docs): Add RadialBar.md

---

packages/comms/src/clienttools/eclcc.ts

fix(ClientTools): Overridden eclccPath should also override envChk

---

packages/dgrid/src/Common.ts

fix(dgrid):  Typo in multiSelect property

---

packages/common/src/Text.ts
packages/graph/src/Vertex.ts

This is to prevent CSS from taking precedent.

fix(faChar): Move font-family into "style"

---

packages/comms/src/clienttools/eclcc.ts
tests/test-comms/.vscode/tasks.json
tests/test-comms/package.json
tests/test-comms/src/clienttools/eclcc.spec.ts
tests/test-comms/src/index.node.spec.ts
tests/test-comms/src/index.spec.ts
tests/test-comms/tsconfig.json

fix(eclcc):  locateClientTools missing args option.

---

packages/comms/src/ecl/topology.ts

fix:  fetchTargetClusters can fail in some environments

---

packages/comms/src/services/wsDFU.ts

feat(comms): Separate Cost property for DFUQuery response for access and at rest costs

---

packages/comms/utils/index.ts

The namespace as defined in the WSDL will be used for both the file path / name of generated files & as the service name passed into the ...Service constructor

fix(comms): In utils wsdlToTs code generator, use namespace as defined in the WSDL

---

packages/comms/src/index-common.ts
packages/comms/src/services/wsLogaccess.ts

fix(comms): add LogAccessType enum to exports in wsLogaccess & include wsDali in exported comms services

---

packages/comms/src/ecl/workunit.ts

fix(comms): WUDetails should include scopes with no properties

---

components/editor/src/codemirror.md
components/editor/src/codemirror.ts

fix: Initialise editor to text content

---

packages/graph/src/__tests__/data.ts
packages/graph/src/__tests__/index.ts
packages/graph/src/__tests__/test2.ts
packages/graph/src/graph2/dataGraph.ts
packages/react/src/icon.tsx
packages/react/src/image.tsx
packages/react/src/vertex3.tsx

DataGraph:
* vertexImageUrl
* vertexImageUrlColumn
Icon:
* imageUrl
Fixes #4072

GH-4072 Graph2 add support for image icons

---

packages/comms/src/services/wsLogaccess.ts

eg, when TotalLogLinesAvailable is 0, this returns 10000

fix(comms): incorrect default for line count returned by GetLogs

---

packages/comms/src/services/wsLogaccess.ts

Fixing the scenario where there is one filter with two separate values, eg class = 'ERR' && class = 'WRN'

fix(comms): wsLogaccess GetLogs fix an incorrect boolean operator

---

packages/dgrid-shim/src/gridHelper.ts

when the value returned from ESP is UNKNOWN_NUM_ROWS

fix(comms): dgrid-shim gridHelper reset huge total to sensible number

---

packages/comms/src/ecl/dfuWorkunit.ts
packages/comms/src/services/fileSpray.ts

consistent with WsWorkunits.WUFile

fix(comms): extend FileSpray.DFUWUFile to change reponse type to text

---

packages/common/src/Utility.ts
packages/html/src/BreakdownTable.ts

fix(html/common): correct BreakdownTable tooltip height calculation

---

packages/phosphor/src/DockPanel.ts
packages/phosphor/src/WidgetAdapter.ts

feat:  Add "LayoutChanged" event to DockPanel

---

packages/codemirror/.vscode/tasks.json
packages/codemirror/src/Editor.ts

Deprecated setOption as it has issues when used prior to the underlying `_codemirror` creation

feat:  Add "option" get/set to Editor

---

packages/comms/src/ecl/workunit.ts

Ensure there are always "some" values for TimeLocalExecute

feat:  Parse the DefinitionList at source

---

packages/comms/src/ecl/workunit.ts

fix:  Tweak grouped label

---

packages/chart/index.html
packages/chart/src/Column.ts
packages/chart/src/test.ts

If it doesn't fit, then hide it.

fix:  Don't relocate text in "Stacked" mode.

---

demos/gallery/samples/chart/Column/StackedTotalsBar.js
packages/chart/index.html
packages/chart/src/Axis.ts
packages/chart/src/XYAxis.ts
packages/chart/src/test.ts

Allow user to ensure total labels don't spill off screen

feat: Add Axis Padding

---

packages/comms/src/services/wsMachine.ts

ESP typically returns any sizes in bytes, but WsMachine returns these disk usage sizes in kilobytes, so multiply by 1024.

fix(comms): WsMachine Target Cluster sizes are in KB

---

packages/dgrid-shim/src/gridHelper.ts

When pagination counts are unknown, change the text of the maximum page link to reflect this, rather than the unreasonably large UNKNOWN_NUM_ROWS returned by ESP

fix(dgrid-shim): max page when pagination counts are unknown

---

packages/comms/utils/index.ts

The values of enums shouldn't be modified from how they exist in the WSDL. In this case, they were being written with white space removed. For example, "Allqueries" (incorrect) instead of "All queries" (correct), which is used as values of the SuspendedFilter request parameter of WsWorkunits.WUListQueries

fix(comms): correct wsdl generated services enum values

---

packages/common/src/Palette.ts

fix:  Unable to select "Accent" ordinal palette

---

packages/comms/src/services/wsdl/FileSpray/v1.26/FileSpray.ts
packages/comms/src/services/wsdl/WsDfu/v1.65/WsDfu.ts
packages/comms/src/services/wsdl/WsWorkunits/v2/WsWorkunits.ts

regen FileSpray, WsDfu with requests wrapped in Partials and WsWorkunits with corrected enum values

fix(comms): regenerate some comms services with Partials

---

packages/comms/src/services/wsLogaccess.ts

The filter passed to WsLogaccess.GetLogs should change the "LogCategory" request parameter based upon the field that is being searched. (eg, HPCC-31896)
Also, corrects TargetAudience.Programmer value to "PRO", see https://github.com/hpcc-systems/HPCC-Platform/blob/master/esp/scm/ws_logaccess.ecm#L145

fix(comms): change LogCategory filter based upon searchField

---

packages/comms/src/services/wsLogaccess.ts

logs returned by the log engine don't seem to use a default sort, so some default should be supplied in the request

fix(comms): wsLogaccess GetLogs results not sorted by default

---

packages/dgrid/src/Table.ts

Cell of width zero should never render.

fix: Custom cell render fails with plain string

---

packages/comms/src/services/wsLogaccess.ts

If the fields returned by WsLogaccess.GetLogAccessInfo exist in WsLogaccess.LogAccessType, have the filter use those categories, otherwise use the field defined by the log engine in the column map.
This is a preliminary attempt at support for the Grafana Loki engine.
Also, fixes an issue where searching by container name wouldn't return any log messages for ephemeral containers, eg "hthor-job-W2024..." as well as "hthor"

fix(comms): GetLogs use WsLogaccess.LogAccessType for filters

---

packages/comms/src/services/wsAccount.ts
packages/comms/src/services/wsdl/ws_account/v1.06/ws_account.ts

bumps ws_account to latest (1.06) and changed service to use the generated ws_account.ts. I opened and saved the 1.05 generated file, so all those changes are just whitespace.

chore(comms): bump WsAccount wsdl to 1.06

---

packages/comms/package.json
packages/comms/src/index-common.ts
packages/comms/src/services/wsSasha.ts
packages/comms/src/services/wsdl/WsSasha/v1.01/WsSasha.ts
tests/test-comms/src/services/wsSasha.spec.ts

Added WsSasha Service to comms layer.

Fixes #4219 Comms Layer for WsSasha Added

---

packages/esbuild-plugins/src/build.ts

Common up base build / watch functions

fix:  Sourcemap for watch was different to build

---

packages/comms/src/services/wsLogaccess.ts

recognizes the grafana engine manager type, also reduces arrays of log fields down into single objects:
the elastic & log analytics (LA) engines return rows formatted like: 
```
{
lines: [{
fields: [
{ timestamp: "...", container: "...", ...},
]
}]
}
```
and the loki engine currently returns rows formatted like: (separate objects per field)
```
{
lines: [{
fields: [
{ tsNs: "..." },
{ pod: "..."},
{ log: "..." }
]
}]
}
```
so just forcing the loki engine results to look like the elastic & LA

feat(comms): add support for the Grafana/Loki log engine

---

packages/comms/src/ecl/activity.ts
packages/comms/src/ecl/logicalFile.ts
packages/comms/src/ecl/query.ts
packages/comms/src/ecl/targetCluster.ts
packages/comms/src/ecl/topology.ts
packages/comms/src/espConnection.ts
packages/comms/src/services/wsWorkunits.ts

Make `attach` calls more consistent by allowing the current state to be passed in.
fixes #4277
fixes #4278

feat: Export `opts` for all services

---

packages/codemirror/src/index.ts
packages/esbuild-plugins/src/build.ts
packages/esbuild-plugins/src/index.ts
packages/esbuild-plugins/src/inline-css.ts
packages/phosphor/src/index.ts

feat: Bundle css files into index.js

---

packages/react/src/text.tsx

fix:  Revert text autosize changes

---

packages/dgrid-shim/src/gridHelper.ts
packages/dgrid/.vscode/launch.json
packages/dgrid/index.html
packages/dgrid/package.json
packages/dgrid/src/dgrid-shim.ts
packages/dgrid/vite.config.ts
packages/eclwatch/index-preview.html

fix: Paged dgrid failing in strict mode

---

packages/comms/esbuild.js
packages/comms/package.json
packages/comms/vite.config.ts

feat: Add support for NodeJS CJS package

---

packages/comms/src/ecl/workunit.ts

while looping through the properties of each scope, if the "Kind" property exists, assign the "Formatted" property the corresponding value from WUDetailsMetaResponse

fix(comms): map Kind ints to strings in normalizeDetails

---

packages/comms/src/ecl/workunit.ts

in Workunit.normalizeDetails(), the raw value of scope properties of measure "node" should be integers rather than strings

fix(comms): scopeProperty measure "node" should be int

---

package-lock.json
packages/comms/package.json
packages/comms/src/services/wsCloud.ts
packages/comms/tsconfig.json

feat: Relocate getPODs parsing into comms

---

eslint.config.js
package-lock.json
package.json
packages/comms/esbuild.js
packages/comms/src/clienttools/eclMeta.ts
packages/comms/src/clienttools/eclcc.ts
packages/comms/src/ecl/scope.ts
packages/comms/src/index.node.ts
packages/esbuild-plugins/src/build.ts
packages/markdown-it-plugins/esbuild.js
packages/markdown-it-plugins/package.json
packages/util/esbuild.js
tests/package.json
tests/type-leaks/type-dependencies.spec.ts
vitest.workspace.ts

Was missing some node deps still in devDeps

fix: Improve type-leaks test

---

packages/comms/src/ecl/logicalFile.ts
packages/comms/src/services/wsDFU.ts
packages/comms/tests/wsDFU.spec.ts

feat: Add recursiveFetchLogicalFiles

---

packages/observablehq-compiler/index-kit.html
packages/observablehq-compiler/src/compiler.ts
packages/observablehq-compiler/src/index.ts
packages/observablehq-compiler/src/kit/compiler.ts
packages/observablehq-compiler/src/kit/index.ts
packages/observablehq-compiler/src/kit/runtime.ts
packages/observablehq-compiler/tests/index-notebookkit.js
packages/observablehq-compiler/tests/index-notebookkit.ts

Fixes previous issues with update and remove

fix: improve runtime placeholder handling
