hpcc-systems/Visualization

- packages/layout/src/Border2.ts
- packages/layout/src/Carousel.ts
- packages/layout/src/ChartPanel.ts
> fix: Minor layout render timing issues

- packages/chart/src/Pie.css
- packages/chart/src/Pie.ts
- packages/common/src/PropertyExt.ts
- packages/common/src/Text.ts
- packages/common/src/Utility.ts
- packages/common/src/Widget.ts
> feat: Simplify Pie labels

- src/other/Table.js
> GH2615: Removed horiz scroll issue

- demos/dermatology/tests/DataFactory.js
- demos/dermatology/tests/chartFactory.js
- packages/chart/src/Radar.css
- packages/chart/src/Radar.ts
- packages/chart/src/index.ts
- tests/test-chart/src/chart.spec.ts
Signed-off-by: Jaman <jbrundage372@gmail.com>
> feat(Radar): Adds Radar widget

- packages/chart/src/Bubble.ts
- tslint.json
> fix: Better bubble text clipping

- packages/common/src/Widget.ts
> fix: textSize should work with coerced strings

- packages/graph/src/Vertex.ts
> fix(Graph): Edge flicker when intersecting with Icon and TextBox

- packages/form/src/Form.ts
> fix: Forms do not update when dashy changes

- demos/dermatology/tests/chartFactory.js
- packages/api/package.json
- packages/api/src/I2DChart.ts
- packages/api/src/INDChart.ts
- packages/chart/src/Bubble.ts
- packages/chart/src/Column.ts
- packages/chart/src/Pie.ts
- packages/chart/src/Radar.ts
- packages/chart/src/Scatter.ts
- packages/common/src/Class.ts
- packages/common/src/PropertyExt.ts
> feat(chart): Support runtime colour calculations

- packages/common/src/Class.ts
- packages/common/src/HTMLWidget.ts
- packages/common/src/PropertyExt.ts
- packages/common/src/Utility.ts
- packages/composite/src/Persist.ts
- packages/ddl-shim/src/ddl2.ts
- packages/ddl-shim/src/upgrade.ts
- packages/form/src/FieldForm.ts
- packages/graph/src/Sankey.ts
- packages/handson/src/Table.ts
- packages/marshaller/src/dashy.ts
- packages/marshaller/src/ddl2/activities/filter.ts
- packages/marshaller/src/ddl2/activities/groupby.ts
- packages/marshaller/src/ddl2/activities/project.ts
- packages/marshaller/src/ddl2/activities/sort.ts
- packages/marshaller/src/ddl2/ddl.ts
- packages/marshaller/src/ddl2/javascriptadapter.ts
- packages/marshaller/src/ddl2/model/element.ts
- packages/marshaller/src/ddl2/model/visualization.ts
- packages/other/src/Opportunity.ts
- packages/other/src/Persist.ts
- packages/react/src/Orb.ts
- packages/tree/src/Dendrogram.ts
- packages/tree/src/Indented.ts
- packages/tree/src/Treemap.ts
- packages/util/src/object.ts
> feat: Add lite serialize/deserialize

- packages/timeline/src/MiniGantt.ts
> feat(timeline): Add maxZoom and EntityPin collapse options

- packages/dgrid/package.json
- packages/dgrid/src/Common.ts
- packages/dgrid/src/DBStore.ts
- packages/dgrid/src/DatasourceStore.ts
- packages/dgrid/src/RowFormatter.ts
- packages/dgrid/src/Table.ts
- packages/eclwatch/src/WUResultStore.ts
> feat(dgrid): Data-driven cell colours

- src/other/Table.js
- test/otherFactory.js
> GH2620 - Adds Table hideEmptyColumns

- packages/chart/src/Axis.css
> style(axis): Add crispEdges styling to axis lines and paths

- packages/common/src/Database.ts
- packages/common/src/PropertyExt.ts
- packages/graph/src/Sankey.ts
- packages/handson/src/Table.ts
- packages/marshaller/src/dashy.ts
- packages/marshaller/src/ddl2/activities/filter.ts
- packages/marshaller/src/ddl2/activities/groupby.ts
- packages/marshaller/src/ddl2/activities/project.ts
- packages/marshaller/src/ddl2/activities/sort.ts
- packages/marshaller/src/ddl2/javascriptadapter.ts
- packages/marshaller/src/ddl2/model/visualization.ts
- packages/other/src/Opportunity.ts
- packages/other/src/PropertyEditor.ts
- packages/react/src/Orb.ts
- packages/tree/src/Dendrogram.ts
- packages/tree/src/Indented.ts
- packages/tree/src/Treemap.ts
Move constructor "owner" param to a set/get method.
Set the owner within the publish code.
This allows the generated JS to be 100% inline.
> chore(Dashy): Simplify generated JS

- packages/ddl-shim/src/ddl2.ts
> chore(DDL): Freeze version until ddl has gone gold.

- packages/common/src/Widget.ts
> fix: Widget flattenData now allows falsey values

- packages/chart/src/Axis.ts
> fix(Axis): Edge case when only one data point is present

- packages/common/src/Database.ts
> fix(database.field): Missing valid method

- src/map/GMapPin.js
> feat(map): Ctrl+Click gives priority to streetview

- src/chart/Bubble.js
> fix(bubble): Overlapping label trimming improved

- packages/graph/src/Graph.ts
- packages/graph/src/Vertex.css
TODO:  Need to disable dragging events on vertex when allowDragging is false.
> fix(graph): click event not firing

- packages/marshaller/src/ddl2/activities/filter.ts
- packages/marshaller/src/ddl2/activities/roxie.ts
- packages/marshaller/src/ddl2/javascriptadapter.ts
- packages/marshaller/src/ddl2/model/element.ts
Skip calling roxie if request hasn't changed.
> fix(marshaller): Multiselection not quite working

- demos/dermatology/tests/commonFactory.js
- packages/common/src/Entity.ts
- packages/common/src/EntityRect.css
- packages/common/src/EntityRect.ts
- packages/common/src/PropertyExt.ts
- packages/common/src/Shape.ts
- packages/common/src/Widget.ts
- packages/common/src/index.ts
- packages/marshaller/src/ddl2/model/visualization.ts
- packages/other/src/PropertyEditor.ts
- tests/test-common/src/common.spec.ts
> feat(EntityRect): Add EntityRect and EntityRectList

- packages/api/src/I2DAggrChart.ts
- packages/api/src/I2DChart.ts
- packages/api/src/index.ts
- packages/chart/src/HexBin.css
- packages/chart/src/HexBin.ts
> feat(HexBin): Add selection support

- src/graph/EdgeC.js
- src/graph/GraphC.js
> fix(graphc): Add edge color support via published properties

- src/graph/Graph.js
- src/marshaller/HipieDDL.js
> fix(graph):  Add edge color support via published properties

- apps/dashPOC/tsconfig.json
- apps/legacyDash/tsconfig.json
- packages/codemirror/src/Editor.ts
- packages/common/src/Entity.ts
- packages/comms/tsconfig.json
- packages/ddl-shim/src/ddl2.ts
- packages/dgrid-shim/src/index.ts
- packages/graph/src/Graph.ts
- packages/util/tsconfig.json
- tests/test-amchart/tsconfig.json
- tests/test-c3chart/tsconfig.json
- tests/test-chart/tsconfig.json
- tests/test-common/tsconfig.json
- tests/test-comms/tsconfig.json
- tests/test-composite/tsconfig.json
- tests/test-dgrid/tsconfig.json
- tests/test-eclwatch/tsconfig.json
- tests/test-form/tsconfig.json
- tests/test-google/tsconfig.json
- tests/test-graph/tsconfig.json
- tests/test-handson/tsconfig.json
- tests/test-layout/tsconfig.json
- tests/test-loader/tsconfig.json
- tests/test-map/tsconfig.json
- tests/test-marshaller/tsconfig.json
- tests/test-other/tsconfig.json
- tests/test-react/tsconfig.json
- tests/test-timeline/tsconfig.json
- tests/test-tree/tsconfig.json
> chore: Remove "skipLibCheck" and fix any issues.

- .vscode/launch.json
- src/layout/Modal.css
- src/layout/Modal.js
- src/marshaller/HipieDDLMixin.js
- test/layoutFactory.js
- test/marshallerFactory.js
> feat(DDL): Add support of _modalIfData

- demos/dermatology/tests/chartFactory.js
- packages/chart/src/BubbleXY.ts
- packages/chart/src/Scatter.ts
- packages/chart/src/XYAxis.ts
- packages/chart/src/index.ts
- tests/test-chart/src/chart.spec.ts
If the pointSizeColumn is null then BubbleXY defaults it to the last column.
> feat: Add BubbleXY

- demos/dermatology/tests/layoutFactory.js
- packages/layout/src/Modal.css
- packages/layout/src/Modal.ts
> fix(modal): Add fixedHeight and fixedWidth to v2

- packages/layout/src/Modal.ts
> fix(lint): Fixed lint issue with Modal.ts

- packages/marshaller/src/ddl2/activities/roxie.ts
- packages/marshaller/src/ddl2/javascriptadapter.ts
> chore(marshaller): Rollback previous removal of call to "requestFields"

- demos/dermatology/tests/timelineFactory.js
- packages/common/src/EntityPin.ts
- packages/timeline/src/MiniGantt.ts
> fix(timeline): Calc EntityPin height

- packages/chart/src/XYAxis.css
- packages/chart/src/XYAxis.ts
> feat: Add 2d selection to XYAxis

- packages/layout/src/ChartPanel.ts
> feat(panel): Add _hideLegendToggleList

- packages/common/src/Icon.css
> fix(icon): Remove pointer-events from icon text

- packages/chart/src/Bubble.ts
- packages/chart/src/Column.ts
- packages/chart/src/Pie.ts
- packages/chart/src/Radar.ts
- packages/chart/src/Scatter.ts
- packages/chart/src/WordCloud.ts
- packages/map/src/Pins.ts
> fix(tooltip): Add SVGElement to end of show args

- packages/chart/src/Axis.ts
> fix(axis): Remove svgLine getBBox call

- src/marshaller/HipieDDLMixin.js
> fix(marshaller): Add CSV option to modalIfData

- packages/phosphor-shim/package.json
- packages/phosphor-shim/rollup.config.js
> fix(phosphor): Remove "crypto" dependency

- packages/chart/src/Scatter.ts
- tests/test-util/package.json
- tests/test-util/src/index.node.spec.ts
- tests/test-util/src/types.spec.ts
TypeScript 2.9.2 is generating invalid .d.ts files when a dependency is inadvertently exposed in the bundled package.
> chore(tests): Add test for errand 'import("..' in type files.

- packages/common/src/SVGWidget.ts
> chore: Resolved SVGWidget NaN errors

- packages/common/src/PropertyExt.ts
- packages/marshaller/src/ddl2/activities/hipiepipeline.ts
- packages/other/src/PropertyEditor.ts
Add logic to handle Collapsed params within PropertyEditor.ts
> feat(PropertyEditor): Add Collapsed publish param tag

- src/other/Table.js
> feat(table): Add hiddenColumns publish param

- package.json
- packages/chart/package.json
- packages/common/package.json
- packages/dgrid-shim/webpack.config.js
- packages/map/package.json
- packages/requirejs-shim/package.json
- packages/requirejs-shim/requirejs.config.js
- tests/test-amchart/test.html
- tests/test-c3chart/test.html
- tests/test-chart/test.html
- tests/test-common/test.html
- tests/test-comms/test.html
- tests/test-composite/test.html
- tests/test-dgrid/test.html
- tests/test-eclwatch/test.html
- tests/test-form/test.html
- tests/test-google/test.html
- tests/test-graph/test.html
- tests/test-handson/test.html
- tests/test-layout/test.html
- tests/test-loader/test.html
- tests/test-map/package.json
- tests/test-map/test.html
- tests/test-marshaller/test.html
- tests/test-other/test.html
- tests/test-react/test.html
- tests/test-timeline/test.html
- tests/test-tree/test.html
- tests/test-util/package.json
- tests/test-util/test.html
> chore: No hoist take II

- demos/dermatology/tests/timelineFactory.js
- packages/common/src/EntityRect.ts
- packages/timeline/src/MiniGantt.css
- packages/timeline/src/MiniGantt.ts
> feat(timeline): Improved icon handling

- packages/amchart/rollup.config.js
- packages/api/rollup.config.js
- packages/c3chart/rollup.config.js
- packages/chart/rollup.config.js
- packages/codemirror/rollup.config.js
- packages/common/src/index.ts
- packages/composite/rollup.config.js
- packages/dgrid/rollup.config.js
- packages/eclwatch/rollup.config.js
- packages/form/rollup.config.js
- packages/google/rollup.config.js
- packages/graph/rollup.config.js
- packages/handson/rollup.config.js
- packages/html/rollup.config.js
- packages/layout/rollup.config.js
- packages/map/rollup.config.js
- packages/marshaller/rollup.config.js
- packages/other/rollup.config.js
- packages/phosphor/rollup.config.js
- packages/react/rollup.config.js
- packages/timeline/rollup.config.js
- packages/tree/rollup.config.js
d3-event is a global instance and needs to be shared between packages.
> fix(d3-event): d3-event is a global instance.

- packages/common/src/SVGZoomWidget.ts
> feat(SVGZoomWidget): Additional zoomTo methods

- packages/comms/src/ecl/graph.ts
- packages/comms/src/services/wsWorkunits.ts
> fix(WUDetails): Update to latest WsWorkunits.WUDetails

- package-lock.json
- packages/eclwatch/src/WUGraph.ts
- packages/graph/src/Graph.ts
> fix(graph): Remove inline status messages.

- packages/eclwatch/src/WUTimeline.ts
- packages/timeline/src/MiniGantt.css
- packages/timeline/src/MiniGantt.ts
Update WUTimeline to use latest MiniGantt features
> fix(MiniGantt): Fix corner case when data.length === 0

- demos/dermatology/tests/dgridFactory.js
- packages/dgrid/src/Common.ts
> feat(dgrid): Add PP for noDataMessage and loadingMessage

- packages/timeline/src/MiniGantt.ts
> feat(timeline): Add several features to MiniGantt

- packages/api/src/ITooltip.ts
- packages/chart/src/HexBin.ts
> feat(hexbin): Add tooltip to HexBin.ts

- packages/graph/src/Graph.ts
> fix(graph): FF tooltip fix for Graph

- packages/dgrid/src/Common.ts
> fix(dgrid): PP for DGrid messages have wrong type

- demos/dermatology/tests/timelineFactory.js
- packages/timeline/src/MiniGantt.ts
> feat(timeline): Add yOffsetColumn to MiniGantt.ts

- packages/comms/src/ecl/query.ts
- packages/marshaller/src/ddl2/activities/roxie.ts
- tests/test-comms/src/ecl/query.spec.ts
- tests/test-comms/src/testLib.ts
> fix(comms): Query.attach should not return a promise.

- packages/codemirror/src/Editor.ts
Fix changes param to include actual changes.
> feat(codemirror):  Add hasFocus Method

- packages/ddl-shim/package.json
- packages/ddl-shim/src/ddl2.ts
- packages/ddl-shim/src/upgrade.ts
- packages/marshaller/src/dashy.ts
- packages/marshaller/src/ddl2/dashboard.ts
- packages/marshaller/src/ddl2/ddl.ts
> feat(ddl): Move layout string into DDL 2.0

- demos/demoware/.vscode/launch.json
- demos/demoware/index.html
- demos/demoware/lib-umd/DemoWidget.js
- demos/demoware/lib-umd/index.js
- demos/demoware/package.json
- demos/demoware/plugins/cm.js
- demos/demoware/plugins/text.js
- demos/demoware/samples/Bar.js
- demos/demoware/samples/Bubble.js
- demos/demoware/samples/Column.js
- demos/demoware/samples/Contour.js
- demos/demoware/samples/HelloWorld.js
- demos/demoware/samples/HexBin.js
- demos/demoware/samples/Line.js
- demos/demoware/samples/Pie.js
- demos/demoware/samples/Radar.js
- demos/demoware/samples/Scatter.js
- demos/demoware/samples/Step.js
- demos/demoware/samples/WordCloud.js
- demos/demoware/samples/index.js
- demos/demoware/src/DemoWidget.ts
- demos/demoware/src/index.ts
- demos/demoware/style/index.css
- demos/demoware/tsconfig.json
> chore(demoware):  Add demoware demo

- demos/gallery/.vscode/launch.json
- demos/gallery/galleryItem.html
- demos/gallery/lib-umd/DemoWidget.js
- demos/gallery/src/DemoWidget.ts
- demos/gallery/style/index.css
> fix(playground): Resize fails to resize widget.

- packages/chart/src/Axis.ts
> fix(axis): Axis text not displaying

- demos/dermatology/tests/timelineFactory.js
- packages/timeline/src/MiniGantt.ts
> fix(timeline): Axis is adjusted according to maxYOffset

- packages/api/src/ITooltip.ts
- packages/api/src/Tooltip.ts
- packages/chart/src/Bubble.ts
- packages/chart/src/Column.ts
- packages/chart/src/HexBin.ts
- packages/chart/src/Pie.ts
- packages/chart/src/Radar.ts
- packages/chart/src/Scatter.ts
- packages/chart/src/WordCloud.ts
- packages/graph/src/Graph.ts
- packages/loader/src/meta.ts
- packages/map/src/Pins.ts
- utils/data/package.json
> fix(tooltip): Workaround FF issue with getScreenCTM

- demos/dermatology/tests/treeFactory.js
- demos/gallery/samples/widget/Treemap.js
- packages/tree/src/Treemap.css
- packages/tree/src/Treemap.ts
> feat(treemap): Treemap improvements

- demos/dermatology/tests/formFactory.js
- packages/form/src/Slider.css
- packages/form/src/Slider.ts
> feat(slider): Refactored Slider.ts

- demos/gallery/samples/chart/Pie/Donut.js
- demos/gallery/samples/chart/Pie/Donut2.js
- demos/gallery/samples/chart/Pie/Donut3.js
> feat(gallery): Add 3 Pie samples

- demos/gallery/samples/tree/CirclePacking/CirclePacking.js
- demos/gallery/samples/tree/Dendrogram/Circular.js
- demos/gallery/samples/tree/Dendrogram/Dendrogram.js
- demos/gallery/samples/tree/Indented/Indented.js
- demos/gallery/samples/tree/Sunburst/Sunburst.js
- demos/gallery/samples/tree/Treemap/Treemap.js
> feat(gallery): Add 4 tree gallery samples

- demos/gallery/samples/chart/BubbleXY/Area.js
- demos/gallery/samples/chart/BubbleXY/BubbleXY.js
> feat(gallery): Add BubbleXY sample

- demos/dermatology/tests/timelineFactory.js
- packages/common/src/Entity.ts
- packages/common/src/EntityRect.ts
- packages/timeline/src/MiniGantt.ts
Minor performance improvements.
> fix(timeline): Revert to "nice" tick formats

- demos/gallery/samples/chart/Gantt/Gantt II.js
- demos/gallery/samples/chart/Gantt/Gantt.js
> feat(gallery): Add 2 Gantt samples

- packages/common/src/PropertyExt.ts
- packages/other/src/PropertyEditor.ts
> feat(PP): Allow SET to optionally support text + value

- packages/graph/src/Subgraph.ts
> fix(graph): Subgraph text can reach beyond edge of border.

- packages/eclwatch/src/WUStatus.ts
> fix(WUStatus): Executed fell through to Completed

- lerna.json
- package.json
> chore(lerna):  Bump lerna version.

- packages/layout/src/ChartPanel.ts
- packages/layout/src/Legend.ts
> fix(legend): Show/Hide series was not refreshing correctly

- demos/dermatology/tests/layoutFactory.js
- packages/api/src/I1DChart.ts
- packages/api/src/I2DChart.ts
- packages/api/src/IGraph.ts
- packages/api/src/INDChart.ts
- packages/layout/src/ChartPanel.ts
- packages/layout/src/Legend.ts
> fix(legend):  Legend incorrect for 2D charts

- demos/gallery/samples/chart/Bullet.js
> feat: Add Bullet sample

- demos/gallery/samples/graph/SankeyValues.js
> feat: Add SankeyValues sample

- demos/gallery/samples/graph/Sankey.js
> feat: Add Sankey sample

- demos/gallery/samples/chart/Summary.js
> feat: Add Summary sample

- src/common/Database.js
- src/common/Utility.js
> fix: remove html from csv export

- packages/marshaller/src/ddl2/dashboard.ts
- packages/marshaller/src/ddl2/model/element.ts
- packages/phosphor/src/DockPanel.ts
- packages/phosphor/src/WidgetAdapter.ts
> feat(DockPanel): Optionally show close [x] button

- demos/gallery/samples/layout/Chart Panel.js
- packages/common/src/TitleBar.ts
- packages/layout/src/ChartPanel.ts
Ability to preset the toggle values.
Ability to show/hide individual buttons.
Let Title bar worry about spacer placement / visibility.
Fixes GH-2813
> feat(ChartPanel):  Add API for toolbar buttons

- demos/gallery/samples/chart/SummaryC.js
> feat: Add SummaryC sample

- demos/gallery/samples/chart/Radial Bar.js
- demos/gallery/src/playground.ts
> fix(gallery): Radial Bar not rendering on timer

- demos/gallery/samples/graph/Sankey.js
- demos/gallery/samples/graph/SankeyValues.js
> fix(gallery): Sankey examples don't load

- demos/gallery/samples/palette/Ordinal/Basic.js
- demos/gallery/samples/palette/Ordinal/Chart Panel.js
- demos/gallery/samples/palette/Ordinal/Shared.js
> chore(gallery): Add palette samples

- packages/layout/src/Legend.ts
> fix(ChartPanel): Legend toggle not refreshing columns

- demos/gallery/samples/graph/Custom Colors.js
- demos/gallery/tsconfig.json
- packages/common/src/Icon.ts
- packages/graph/src/Edge.ts
- packages/graph/src/Graph.ts
- packages/graph/src/Subgraph.ts
Subgraph: title, border and fill support.
Edge: Text color.
Fixes GH-2845
Fixes GH-2829
> feat(Graph): Additional color support

- demos/gallery/samples/palette/Ordinal/Runtime.js
- demos/gallery/src-umd/playground.js
- packages/layout/src/Legend.ts
> fix(Legend): Legend should use "fillColor" when available

- src/other/Table.js
> fix: Removed update on Table row selection

- packages/ddl-shim/cli/index.ts
- packages/ddl-shim/src/upgrade.ts
> fix(ddl): Optionally lowercase field IDs

- packages/other/src/ESP.ts
> fix(other): Add missing exports

- packages/marshaller/src/ddl2/activities/dspicker.ts
- packages/marshaller/src/ddl2/activities/roxie.ts
- packages/marshaller/src/ddl2/javascriptadapter.ts
> fix(marshaller): Default to HipieResultRef

- packages/layout/src/Grid.ts
> fix(layout): Grid layout not rendering.

- packages/marshaller/src/ddl2/activities/databomb.ts
- packages/marshaller/src/ddl2/javascriptadapter.ts
> fix(marshaller): Add DDL support to Form

- packages/marshaller/src/ddl2/model/visualization.ts
> fix(marshaller): Add missing visualizations

- packages/comms/src/ecl/graph.ts
- packages/comms/src/ecl/workunit.ts
> fix(comms):  Add option to get "all" graphs for a WU

- demos/gallery/util/dir2json.js
> feat(gallery): dir2json now parses imports

- packages/chart/src/RadialBar.ts
> fix: Add standard click events to RadialBar.ts

- packages/layout/src/Carousel.ts
> fix(Carousel): Carousel should not render when hidden

- packages/map/src/Choropleth.ts
> fix(choropleth): Using mesh color/width in update

- packages/graph/src/Edge.ts
- packages/graph/src/Graph.ts
- packages/graph/src/Subgraph.ts
- packages/graph/src/Vertex.ts
> chore(Graph): Refactor PP to use interface mixin

- packages/marshaller/src/ddl2/activities/datasource.ts
- packages/marshaller/src/ddl2/activities/dspicker.ts
- packages/marshaller/src/ddl2/activities/hipiepipeline.ts
- packages/marshaller/src/ddl2/ddl.ts
- packages/marshaller/src/ddl2/model/element.ts
> fix(marshaller): Distinguish between RoxieResult and RoxieService

- packages/graph/src/Graph.ts
- packages/graph/src/GraphLayouts.ts
Add missing promise to "doLayout" so zoom to fit works after layout.
> feat(Graph): Add "digraph" option to hierarchy layout

- package.json
- packages/graph/src/Graph.ts
- tests/test-comms/src/ecl/query.spec.ts
- tests/test-graph/package.json
- tests/test-graph/src/coreTests.ts
- tests/test-graph/src/graph.spec.ts
> fix(graph): Render callback not being called.

- packages/api/src/ITooltip.css
> fix: Tooltip arrow styling issues

- demos/dermatology/tests/graphFactory.js
- demos/gallery/samples/graph/Scaled.js
- packages/common/src/SVGWidget.ts
> fix: Add scale to move within SVGWidget.ts

- packages/chart/src/HexBin.ts
> fix(HexBin): Classic closure bug with "data"

- packages/chart/src/Pie.ts
- packages/layout/src/Legend.ts
Also resolved a bug that was preventing Legend from working with 2D charts
Fixes #2888
> feat: Add pie series percentages

- demos/dermatology/tests/formFactory.js
- packages/form/src/OnOff.css
- packages/form/src/OnOff.ts
This is in preparation for the new property editor.
> feat(form): Add features to OnOff.ts

- demos/gallery/samples/legend/Values.js
- packages/layout/src/ChartPanel.ts
- packages/layout/src/Legend.ts
> feat: Add option to show legend values

- packages/chart/src/Column.ts
- packages/chart/src/Scatter.ts
> feat: Add value display options for XYAxis etc

- demos/dashy/src/index.ts
- package-lock.json
- tests/test-comms/src/clienttools/eclcc.spec.ts
- tests/test-comms/src/testLib.ts
- tests/test-eclwatch/src/eclwatch.spec.ts
> chore(test): Switch to new test server

- demos/gallery/samples/chart/Pie/HalfDonut.js
- demos/gallery/samples/chart/Pie/HalfPie.js
- demos/gallery/samples/chart/Pie/QuarterDonut.js
- demos/gallery/samples/chart/Pie/QuarterPie.js
- demos/gallery/samples/chart/Scatter/ScatterValues.js
> feat: Add 3 samples to showcase CL changes

- packages/chart/src/Column.ts
> fix: valueCendered now works with Bar.ts

- demos/gallery/samples/layout/Splitters.js
> fix(gallery): Splitters demo fails during unit test

- packages/chart/src/Column.ts
- packages/chart/src/XYAxis.ts
Add use of textColor to values within column/bar
Fixes #2912
> feat: Adjust position of cutoff values

- demos/gallery/.vscode/launch.json
- demos/gallery/src/test.ts
> chore(gallery): Add option to "test" single sample easily

- packages/api/src/ITooltip.ts
- packages/chart/src/Axis.ts
- packages/chart/src/Bubble.ts
- packages/chart/src/Column.ts
- packages/chart/src/Contour.ts
- packages/chart/src/HexBin.ts
- packages/chart/src/Pie.ts
- packages/chart/src/Radar.ts
- packages/chart/src/RadialBar.ts
- packages/chart/src/Scatter.ts
- packages/chart/src/WordCloud.ts
- packages/common/src/Entity.ts
- packages/common/src/EntityVertex.ts
- packages/common/src/TextBox.ts
- packages/dgrid/src/Table.ts
- packages/graph/src/Sankey.ts
- packages/graph/src/Vertex.ts
- packages/map/src/Choropleth.ts
- packages/map/src/GeoHash.ts
- packages/other/src/CalendarHeatMap.ts
- packages/other/src/HeatMap.ts
- packages/tree/src/CirclePacking.ts
- packages/tree/src/Dendrogram.ts
- packages/tree/src/SunburstPartition.ts
- packages/tree/src/Treemap.ts
- src/graph/VertexC.js
> chore: Add descriptions for many publish parameters

- demos/dermatology/tests/commonFactory.js
- demos/gallery/samples/widget/TextFontSize.js
- packages/common/src/Text.ts
- packages/common/src/TextBox.ts
> feat(textbox): Add fontSize

- packages/api/src/Tooltip.ts
- packages/graph/src/Graph.ts
> feat(tooltip): tooltipHTML returning null prevents show

- packages/common/src/FAChar.ts
> feat(fachar): Add generic click handling

- packages/marshaller/src/dashy.ts
> fix(Marshaller): Open new DDL should auto-select first element

- packages/chart/src/SummaryC.ts
> feat: Value/label centering in SummaryC.ts

- packages/chart/src/Axis.ts
- packages/chart/src/XYAxis.ts
- packages/common/src/Widget.ts
- packages/marshaller/src/ddl1/FlyoutButton.ts
- tests/test-common/src/common.spec.ts
> feat(Widget): Enhanced classed call to match d3 v4 call signature.

- packages/graph/src/Graph.ts
- packages/graph/src/GraphData.ts
> feat(graph): Optionally drag singleton neighbours with drag node

- packages/graph/src/Graph.ts
> fix(Graph): Calling raise during dragstart breaks click event

- demos/gallery/samples/graph/Les Miserables.js
- packages/common/src/SVGWidget.ts
- packages/common/src/Widget.ts
- packages/graph/src/Graph.ts
Common up selection and centroid glow colour code.
> feat(Graph): Add PP to change centroid colour

- packages/common/src/SVGZoomWidget.ts
- packages/graph/src/Graph.ts
> feat(Graph): Add option to clear selection on background click

- packages/ddl-shim/src/upgrade.ts
> fix(ddl-upgrade): Runtime error upgrading ddl

- packages/ddl-shim/package.json
- packages/ddl-shim/src/upgrade.ts
> fix(ddl-upgrade): SCALE not handled

- demos/gallery/samples/graph/Les Miserables.js
- packages/graph/src/Graph.css
- packages/graph/src/Graph.ts
- packages/graph/src/GraphData.ts
> feat(Graph): Optionally highlight selected path to centroid

- packages/comms/package.json
> chore(comms): Some node dependencies were marked as "develop"

- demos/dermatology/tests/layoutFactory.js
- demos/gallery/samples/advanced/GraphSlider.js
- packages/layout/src/Layered.ts
Add DonutSummary.ts
Add samples/chart/Pie/DonutSummary.js
Added ability to center value and labels to SummaryC.ts
> feat: Layered.ts can give placement to layers

- packages/layout/src/FlexGrid.ts
> fix(FlexGrid): Add exit/remove to FlexGrid.ts

- packages/dgrid-shim/src/gridHelper.ts
- packages/dgrid-shim/src/index.ts
- packages/dgrid/src/DatasourceStore.ts
- packages/dgrid/src/DatasourceTable.ts
> fix(dgrid):  DatasourceStore defaulting to page "-1"

- packages/phosphor/src/TabPanel.ts
> feat(TabPanel):  Add ability to set active tab

- packages/graph/README.md
> feat(readme): Add packages/graph/README.md

- packages/chart/README.md
> feat(readme): Add README.md for chart package

- packages/tree/README.md
> feat(readme): Add packages/tree/README.md

- demos/gallery/samples/layout/Modal.js
- packages/layout/README.md
> feat(readme): Add packages/layout/README.md

- packages/layout/src/Legend.ts
> fix(legend): Limiting legend value sums by columns

- packages/marshaller/src/dashy.ts
> fix(dashy): Selection state unpredictable

- packages/chart/src/Scatter.ts
> fix(line): Use proper colors to match legend

- packages/other/src/PropertyEditor.ts
> feat(PropertyEditor): Add option to hide header.

- demos/gallery/src/test.ts
> chore(gallery): Increase test timeout

- demos/dashy/src/index.ts
- packages/marshaller/src/ddl2/activities/datasource.ts
- packages/marshaller/src/ddl2/activities/wuresult.ts
- packages/marshaller/src/ddl2/dashboard.ts
- packages/marshaller/src/ddl2/ddl.ts
- packages/marshaller/src/ddl2/dsTable.ts
- packages/phosphor/src/TabPanel.ts
> fix(marshaller): WU Results should share WU instances

- demos/dashy/.vscode/launch.json
- demos/gallery/src-umd/test.js
- packages/comms/package.json
- tests/test-util/src/types.spec.ts
> fix(build): Add missing dependency for "module" releases

- packages/common/src/PropertyExt.ts
> fix(PropertyExt): Improved changed hashing

- packages/common/src/SVGZoomWidget.ts
- packages/common/src/TitleBar.css
- packages/common/src/TitleBar.ts
- packages/eclwatch/src/WUGraph.ts
- packages/graph/src/Graph.ts
- packages/layout/src/ChartPanel.ts
- packages/marshaller/src/ddl2/dashboard.ts
- packages/marshaller/src/ddl2/dsTable.ts
- tests/test-common/src/common.spec.ts
Change icon + tooltip to be consistent getter/setter methods.
> feat(toolbar): Add selection group

- demos/dermatology/tests/chartFactory.js
- demos/gallery/samples/chart/Column/Percent Domain.js
- demos/gallery/samples/chart/Column/Percent Series.js
- demos/gallery/samples/legend/Values.js
- demos/gallery/src/test.ts
- packages/chart/src/Column.ts
Increase gallery unit test timeout
Fixes #2969
> feat(column): Add option to show percent values

- demos/gallery/.vscode/launch.json
- demos/gallery/samples/chart/Column/Domain Spacing.js
- packages/chart/src/Axis.ts
- packages/chart/src/Column.ts
- packages/chart/src/XYAxis.ts
> feat(column): Add inner/outer padding for column/ordinal charts 

- packages/layout/src/Border2.ts
> fix(ChartPanel): Add missing render callback call.

- packages/marshaller/src/dashy.ts
- packages/marshaller/src/ddl2/activities/datasource.ts
- packages/marshaller/src/ddl2/activities/filter.ts
- packages/marshaller/src/ddl2/activities/logicalfile.ts
- packages/marshaller/src/ddl2/activities/project.ts
- packages/marshaller/src/ddl2/activities/sort.ts
- packages/marshaller/src/ddl2/activities/wuresult.ts
- packages/marshaller/src/ddl2/dashboard.ts
- packages/marshaller/src/ddl2/dsTable.ts
- packages/marshaller/src/ddl2/graphadapter.ts
- packages/marshaller/src/ddl2/javascriptadapter.ts
- packages/marshaller/src/ddl2/model/visualization.ts
- packages/marshaller/src/ddl2/pipelinePanel.ts
> feat(dashy): Improved UI 

- packages/layout/src/Legend.ts
> fix(legend): Summing series correctly

- packages/marshaller/src/dashy.ts
> fix(dashy): Hide title on cloned dashboard.

- packages/marshaller/src/dashy.ts
- packages/marshaller/src/ddl2/graphadapter.ts
- packages/marshaller/src/ddl2/pipelinePanel.ts
> fix(dashy): Chart type was not visible

- packages/marshaller/src/ddl2/graphadapter.ts
- packages/marshaller/src/ddl2/pipelinePanel.ts
> fix(dashy): Pipeline graph not refreshing correctly

- demos/dashy/index.html
> fix(dashy): removed dashy dashboard test

- packages/common/src/TitleBar.ts
> fix(TitleBar): Tooltip not updatable

- packages/common/src/Widget.ts
> fix(Widget):  Classed could share object with all Widgets

- packages/common/src/PropertyExt.ts
- packages/other/src/PropertyEditor.css
- packages/other/src/PropertyEditor.ts
> feat(PropertyEditor):  Optionally highlight invalid properties

- .vscode/launch.json
- src/map/GMap.js
> fix(gmap):  Global key not being picked up correctly

- packages/layout/src/Legend.ts
> fix(legend): Summing legend totals via dataFamily

- packages/phosphor/src/DockPanel.ts
- packages/phosphor/src/PDockPanel.ts
- packages/phosphor/src/SplitPanel.ts
- packages/phosphor/src/TabPanel.ts
- packages/phosphor/src/WidgetAdapter.ts
> fix(phosphor): Render callback is called too soon

- packages/phosphor/src/DockPanel.ts
- packages/phosphor/src/WidgetAdapter.ts
Fix issue with stacked tabs not calling callback correctly
> feat(phosphor):  Add option set layout for next render

- packages/marshaller/src/ddl2/activities/databomb.ts
- packages/marshaller/src/ddl2/activities/dspicker.ts
- packages/marshaller/src/ddl2/activities/roxie.ts
> feat(dashy): Various datasource tweaks

- packages/marshaller/src/ddl2/dsTable.ts
> feat(dashy): Option to clone datasources

- packages/other/src/PropertyEditor.css
- packages/other/src/PropertyEditor.ts
> feat(PropertyEditor):  Improve how "object" is displayed

- packages/common/src/TitleBar.css
- packages/common/src/TitleBar.ts
- packages/marshaller/src/ddl2/activities/filter.ts
- packages/marshaller/src/ddl2/dashboard.ts
- packages/marshaller/src/ddl2/model/element.ts
- packages/marshaller/src/ddl2/model/visualization.ts
- packages/marshaller/src/ddl2/model/vizChartPanel.ts
> feat(dashy): Minor usability tweaks

- demos/WeCare/src/index.ts
- demos/WeCare/www/index.html
- package-lock.json
- packages/map/src/GMapGraph.ts
> fix(wecares): Google circles not rendering

- packages/marshaller/src/dashy.ts
- packages/marshaller/src/ddl2/dashboard.ts
- packages/marshaller/src/ddl2/model/element.ts
> fix(dashy): False positive error on initial load

- packages/common/src/Utility.ts
- packages/marshaller/src/ddl2/activities/project.ts
- packages/marshaller/src/ddl2/dashboard.ts
- packages/marshaller/src/ddl2/ddl.ts
> fix(ddl): Incorrect input/output lists in the DDL

- packages/marshaller/src/ddl2/activities/roxie.ts
Add drop down of available results.
> fix(marshaller): Unnamed roxie results fail to display

- packages/chart/src/Scatter.ts
- packages/chart/src/XYAxis.ts
- packages/common/src/Utility.ts
- packages/marshaller/src/ddl2/activities/filter.ts
- packages/marshaller/src/ddl2/model/element.ts
> feat(dashy): Enable XYAxis range selection

- packages/marshaller/src/ddl2/activities/filter.ts
Remove description logic out of remoteValue function.
> fix(marshaller): Potential filter issue

- packages/map/README.md
> feat(readme): Add packages/map/README.md

- packages/common/src/Utility.ts
> feat(SimpleSelection):  Return selection state on click

- packages/common/src/Widget.ts
> fix(rowToObj): Add guard to rowToObj

- packages/common/src/PropertyExt.ts
- packages/other/src/PropertyEditor.ts
> feat(PropertyExt): Add option to hide PP similar to disable

- packages/common/src/PropertyExt.ts
> fix(PropertyExt): Hashsum fails with proxied properties

- packages/layout/src/Border2.css
> fix(ie11): Fixed IE11 Border2 flex issue

- packages/timeline/README.md
I tested the stand-alone HTML page
> feat(readme): Add README.md to timeline package

- demos/gallery/samples/comms/Connection.js
- packages/comms/README.md
Add Connection gallery sample
Tested the stand-alone HTML and viewed the new sample in the gallery
> feat(readme): Add README.md to comms package

- demos/gallery/samples/codemirror/JSEditor.js
- demos/gallery/samples/codemirror/JSONEditor.js
- demos/gallery/samples/codemirror/XMLEditor.js
- packages/codemirror-shim/src/index.ts
- packages/codemirror/src/ECLEditor.ts
- packages/codemirror/src/JSEditor.ts
- packages/codemirror/src/JSONEditor.ts
- packages/codemirror/src/XMLEditor.ts
- tests/test-util/src/types.spec.ts
> feat(codemirror): Add XML support

- demos/dermatology/.vscode/launch.json
- demos/dermatology/tests/mapFactory.js
- demos/gallery/.vscode/launch.json
- demos/gallery/samples/geospatial/Leaflet/Cluster Icons.js
- demos/gallery/samples/geospatial/Leaflet/Cluster Pins Google.js
- demos/gallery/samples/geospatial/Leaflet/Cluster Pins MapBox.js
- packages/map/src/leaflet/Icons.ts
- packages/map/src/leaflet/Markers.ts
- packages/map/src/leaflet/Pins.ts
- packages/map/src/leaflet/US.ts
- packages/map/src/leaflet/USCounties.ts
- packages/map/src/leaflet/USStates.ts
- packages/map/src/leaflet/index.ts
Allow user to specify custom urls for the pins.
> feat(ClusterIcons): Add Cluster Icons support

- src/chart/Summary.js
- src/common/Database.js
- src/graph/Graph.js
- src/graph/GraphC.js
- src/map/GMap.js
- src/marshaller/HipieDDLMixin.js
> feat(Summary): Add options to change the font sizes

- demos/gallery/src-umd/devConfig.js
The gallery/playground now works with local sources when hosting a local web server for testing (ex: `http-server`)
> feat(gallery): Added support for localhost

- demos/dermatology/tests/chartFactory.js
- demos/dermatology/tests/layoutFactory.js
- demos/dermatology/tests/mapFactory.js
- demos/dermatology/tests/timelineFactory.js
- demos/dermatology/tests/treeFactory.js
Fixes #3097
I observed that the factory files no longer throw errors related to ES6 syntax when loaded in IE11.
> fix(factory): Replaced ES6 syntax with ES5

- demos/gallery/samples/codemirror/CSSEditor.js
- demos/gallery/samples/codemirror/HTMLEditor.js
- packages/codemirror-shim/src/index.ts
- packages/codemirror/README.md
- packages/codemirror/src/CSSEditor.ts
- packages/codemirror/src/HTMLEditor.ts
- packages/codemirror/src/index.ts
- tests/test-util/src/types.spec.ts
Tested the two new editors in a stand-alone html page.
> feat(codemirror): Add HTMLEditor and CSSEditor

- packages/chart/src/Scatter.ts
Fixes #3078
Tested the publish property on the dermatology page
> fix(scatter): Add interpolatePoint property

- packages/marshaller/src/ddl2/activities/filter.ts
> fix(marshaller): Nullable not working for "in" and "range"

- packages/api/src/IInput.ts
- packages/form/src/Input.ts
> feat: Added keyup and focus to Input/IInput

- tests/README.md
- tests/index.html
This simple html page has been a valuable testing tool.
> feat: Added index.html

- demos/gallery/samples/chart/Pie/HalfPie.js
- packages/chart/src/Pie.ts
Fixes #3077
I tested the new publish parameter in the dermatology page.
> feat(pie): Added showPercentageDecimals to Pie

- packages/marshaller/src/ddl2/dashboard.ts
> fix(dashy): Hide single tabs by default in Dashboard

- packages/marshaller/src/ddl2/model/visualization.ts
> fix(marshaller): Rollback choropleth to non leaflet version

- packages/marshaller/src/dashy.ts
- packages/phosphor/src/TabPanel.ts
> fix(marshaller): Debug "v1" + "v1->v2" not refreshing correctly

- packages/marshaller/src/ddl2/model/visualization.ts
> fix(marshaller): Preserve mapping setting when visualizations change

- packages/marshaller/src/ddl2/model/element.ts
- packages/marshaller/src/ddl2/model/visualization.ts
> fix(marshaller): Ensure Forms always have selection state.

- packages/other/src/Html.ts
> fix: Corrected style overflow use in Html.ts

- packages/tree/src/Treemap.ts
> feat(tree): Move Treemap weight/html into methods

- packages/marshaller/src/ddl2/dashboard.ts
- packages/marshaller/src/ddl2/model/element.ts
- packages/marshaller/src/ddl2/model/vizChartPanel.ts
- packages/phosphor/src/DockPanel.ts
> fix(marshaller): Add min size constraints to contained widgets.

- demos/dashy/dashy.code-workspace
- packages/common/src/ProgressBar.ts
- packages/common/src/TitleBar.ts
- packages/common/src/Widget.ts
- packages/ddl-shim/src/ddl2.ts
- packages/ddl-shim/src/upgrade.ts
- packages/layout/src/Border2.ts
- packages/layout/src/Carousel.ts
- packages/layout/src/ChartPanel.ts
- packages/layout/src/Legend.ts
- packages/layout/src/Modal.ts
- packages/marshaller/src/dashy.ts
- packages/marshaller/src/ddl2/activities/databomb.ts
- packages/marshaller/src/ddl2/dashboard.ts
- packages/marshaller/src/ddl2/ddl.ts
- packages/marshaller/src/ddl2/dvTable.ts
- packages/marshaller/src/ddl2/graphadapter.ts
- packages/marshaller/src/ddl2/model/element.ts
- packages/marshaller/src/ddl2/model/visualization.ts
- packages/marshaller/src/ddl2/model/vizChartPanel.ts
- packages/phosphor/src/DockPanel.ts
> fix(marshaller): Add missing "flyout" capability

- demos/gallery/samples/layout/SplitPanel.js
- demos/gallery/samples/layout/TabPanel.js
- packages/phosphor/README.md
Add two phosphor package samples
> feat(readme): Add README.md to phosphor package

- demos/dermatology/tests/commonFactory.js
- demos/gallery/samples/common/CanvasWidget.js
- demos/gallery/samples/common/EntityCard.js
- demos/gallery/samples/common/EntityPin.js
- demos/gallery/samples/common/EntityRect.js
- demos/gallery/samples/common/EntityVertex.js
- demos/gallery/samples/common/HTMLWidget.js
- demos/gallery/samples/common/Icon.js
- demos/gallery/samples/common/SVGWidget.js
- demos/gallery/samples/common/Shape.js
- demos/gallery/samples/common/TitleBar.js
- packages/common/README.md
- packages/common/src/CanvasWidget.ts
- packages/common/src/TitleBar.ts
> feat(readme): Add packages/common/README.md

- demos/gallery/samples/codemirror/MarkdownEditor.js
- packages/codemirror-shim/src/index.ts
- packages/codemirror/src/MarkdownEditor.ts
- packages/codemirror/src/index.ts
- tests/test-util/src/types.spec.ts
Viewed the MarkdownEditor sample via playground.html
> feat: Added MarkdownEditor and sample

- packages/chart/src/XYAxis.ts
> fix(xyaxis): Corrected calcMargin logic

- packages/layout/src/ChartPanel.ts
- packages/layout/src/Legend.ts
- packages/layout/src/Popup.ts
Fixed some invalid "super" calls.
Fixes #3134
> fix(Legend): Regression causing issues with legend clicks

- packages/timeline/src/MiniGantt.ts
Fixes #3141
Verified the change on the dermatology page
> feat(timeline): Add centerOnMostRecent to MiniGantt

- demos/gallery/src/devConfig.ts
Add html and preact-shim to gallery package
> feat(gallery): Add gallery localhost support

- demos/dermatology/tests/DataFactory.js
- demos/dermatology/tests/layoutFactory.js
- packages/layout/src/ChartPanel.ts
- packages/layout/src/Legend.ts
> feat(Legend): Add max label width for legend

- src/marshaller/FlyoutButton.js
Fixes #3115
I've tested that the `position: fixed` style resolves the issue, but I was unable to test the actual code change on a DDL-rendered dashboard. I'll work towards doing that now.
> fix(marshaller): Flyout getting clipped by parent

- src/graph/VertexC.js
> feat: GraphC now supports centroid

- src/api/ITooltip.css
- src/api/ITooltip.js
- src/chart/Bubble.js
- src/chart/Column.js
- src/chart/Pie.js
- src/chart/Scatter.js
Added tooltipFollowMouse to ITooltip
Added support for tooltipStyle series-table to Bubble, Column, Pie and Scatter
Dermatology tested in IE10 and Chrome
> feat: Added series-table tooltipStyle to ITooltip

- demos/gallery/samples/html/StyledTable.js
- packages/html/src/StyledTable.ts
- packages/html/src/index.ts
> feat(html): Add StyledTable.ts

- packages/api/src/ITooltip.css
- packages/api/src/ITooltip.ts
- packages/chart/src/Bubble.ts
- packages/chart/src/Column.ts
- packages/chart/src/Pie.ts
- packages/chart/src/Scatter.ts
- packages/common/src/Utility.ts
- packages/marshaller/src/ddl1/FlyoutButton.ts
- src/graph/GraphC.js
- src/graph/VertexC.js
> Candidate 2.x.x

- packages/comms/src/ecl/targetCluster.ts
- packages/comms/src/services/wsMachine.ts
> feat(WsMachine): Add support for GetTargetClusterUsage

- packages/layout/src/FlexGrid.ts
> feat(FlexBox): Add option to force scroll bars

- packages/chart/src/Gauge.ts
> feat(Gauge): Add "click" event for entire Gauge

- packages/chart/src/Column.ts
> fix(column): Correctly adjusts valueText position

- packages/marshaller/src/dashy.ts
- packages/marshaller/src/ddl2/activities/databomb.ts
- packages/marshaller/src/ddl2/activities/project.ts
Add support for "dashy" file extensions
> fix(marshaller): Nested databombs fail to display correctly

- demos/gallery/samples/html/BreakdownTable.js
- packages/html/src/BreakdownTable.ts
- packages/html/src/SimpleTable.ts
- packages/html/src/index.ts
> feat(html): Add BreakdownTable.ts

- demos/gallery/samples/html/StatsTable.js
- packages/html/src/SimpleTable.ts
- packages/html/src/StatsTable.ts
- packages/html/src/StyledTable.ts
- packages/html/src/index.ts
> feat(html): Add StatsTable.ts

- demos/dermatology/tests/layoutFactory.js
- packages/chart/src/Pie.ts
- packages/common/src/SVGWidget.ts
- packages/layout/src/ChartPanel.ts
- packages/layout/src/Legend.ts
Ensure Pie does not sort the underlying data
> feat(SVGWidget): Allow SVG Widgets to Scroll

- demos/gallery/samples/chart/QuartileCandlestick.js
- packages/chart/src/QuartileCandlestick.ts
- packages/chart/src/index.ts
- tests/test-chart/src/chart.spec.ts
> feat(chart): Add QuartileCandlestick.ts

- packages/chart/src/Pie.ts
> fix(pie): Pie centerOnLabels when data.length > 1

- demos/dashy/dashy.code-workspace
- demos/dashy/package.json
- demos/dashy/src/index.ts
- packages/comms/src/connection.ts
- packages/ddl-shim/src/ddl2.ts
- packages/marshaller/src/ddl2/activities/dspicker.ts
- packages/marshaller/src/ddl2/activities/filter.ts
- packages/marshaller/src/ddl2/activities/hipiepipeline.ts
- packages/marshaller/src/ddl2/activities/logicalfile.ts
- packages/marshaller/src/ddl2/activities/roxie.ts
- packages/marshaller/src/ddl2/activities/wuresult.ts
- packages/marshaller/src/ddl2/dashboard.ts
- packages/marshaller/src/ddl2/ddl.ts
- packages/marshaller/src/ddl2/dsTable.ts
- packages/marshaller/src/ddl2/dvTable.ts
- packages/marshaller/src/ddl2/graphadapter.ts
- packages/marshaller/src/ddl2/javascriptadapter.ts
- packages/marshaller/src/ddl2/model/element.ts
- packages/marshaller/src/index.ts
> feat(marshaller): Add "hookSend" to ElementContainer

- packages/chart/src/Pie.ts
> feat(pie): Add showSeriesValue to Pie

- packages/layout/src/Legend.ts
Edge case where row[0] is a numeric
> fix(legend): Issue with numeric labels

- packages/common/src/PropertyExt.ts
> fix(PropertyExt): Incorrect hashSum calculation

- demos/WeCare/.vscode/launch.json
- demos/WeCare/package.json
- demos/WeCare/src/index.ts
- demos/WeCare/webpack.config.js
- demos/WeCare/www/index.html
> feat(WeCare): Add lexid URL param

- src/other/Table.js
> fix: Table.js transforms now apply by fields idx

- demos/dashy/dashy.code-workspace
- packages/dgrid/src/index.ts
- packages/marshaller/src/ddl2/activities/databomb.ts
- packages/marshaller/src/ddl2/model/visualization.ts
> feat(dashy): Add preliminary support for "object" field types

- package-lock.json
- packages/chart/package.json
- packages/comms/package.json
- packages/comms/src/connection.ts
- packages/comms/src/index.node.ts
- packages/composite/package.json
- packages/graph/package.json
- packages/layout/package.json
- packages/tree/package.json
- tests/test-comms/src/connection.spec.ts
- tests/test-util/src/types.spec.ts
> fix(comms): rejectUnauthorized does nothing in NodeJS

- packages/common/src/Database.ts
- packages/common/src/SVGWidget.ts
- packages/common/src/Utility.ts
- packages/composite/src/MegaChart.ts
- packages/layout/src/ChartPanel.ts
- packages/marshaller/src/dashy.ts
- packages/marshaller/src/ddl1/HipieDDLMixin.ts
ChartPanel:  Add option to download image of SVG visualization
> feat(SVGWiget): Add image download capability

- packages/comms/src/clienttools/eclMeta.ts
> fix(eclcc): Add missing meta attributes

- packages/comms/package.json
> fix(build): Add missing dependency "tmp"

- demos/gallery/samples/codemirror/JSEditor.js
- packages/codemirror/src/Editor.css
- packages/codemirror/src/Editor.ts
> feat(codemirror): Add markText to Editor.ts

- src/other/Table.js
> fix(Table): Empty columns no longer overwrite field type

- .travis.yml
- package.json
- src/api/ITooltip.js
- src/chart/Bubble.js
- src/chart/Column.js
- src/chart/Pie.js
- src/chart/Scatter.js
- test/widgets.js
> chore(build): Fix travis build issues

- packages/chart/src/Axis.ts
- packages/chart/src/XYAxis.ts
> feat(xyaxis): Add xAxisTitle support to XYAxis.ts

- packages/phosphor/src/SplitPanel.ts
> feat(SplitPanel): Expose relativeSizes

- packages/chart/src/BubbleXY.ts
- packages/chart/src/Scatter.ts
- packages/chart/src/XYAxis.ts
> fix(chart): Corrected pointShapeColumn use condition

- src/c3chart/Common1D.js
- src/c3chart/Common2D.js
- src/c3chart/CommonND.js
> fix(c3): corrected c3 color assignments

- src/marshaller/HipieDDL.js
Fixes #3237
Will test this fix in dsp before checking "The change has been fully tested".
> feat: marshaller removes parens from empty titles

- apps/dashPOC/rollup.config.js
- packages/api/rollup.config.js
- packages/chart/rollup.config.js
- packages/codemirror-shim/rollup.config.js
- packages/codemirror/rollup.config.js
- packages/common/rollup.config.js
- packages/comms/rollup.config.js
- packages/composite/rollup.config.js
- packages/dgrid/rollup.config.js
- packages/eclwatch/rollup.config.js
- packages/form/rollup.config.js
- packages/graph/rollup.config.js
- packages/html/rollup.config.js
- packages/layout/rollup.config.js
- packages/loader/rollup.config.js
- packages/map/rollup.config.js
- packages/marshaller/rollup.config.js
- packages/other/rollup.config.js
- packages/phosphor-shim/rollup.config.js
- packages/phosphor/rollup.config.js
- packages/preact-shim/rollup.config.js
- packages/react/rollup.config.js
- packages/timeline/rollup.config.js
- packages/tree/rollup.config.js
- packages/util/rollup.config.js
- tests/test-dgrid/rollup.config.js
> chore(build): Minimize embedded CSS

- src/layout/Modal.js
- src/marshaller/HipieDDL.js
- src/marshaller/HipieDDLMixin.js
Verified this change within DSP-DEV
> fix: Modal title removes leading/trailing parens

- src/marshaller/HipieDDLMixin.js
Fixes #3243
Tested within DSP-DEV
> feat: Add disableModals to HipieDDLMixin

- packages/chart/src/Summary.ts
- packages/layout/src/Popup.ts
- packages/map/src/GMap.ts
- packages/other/src/Legend.ts
> fix: Changed d3 style use to v4+ format

- package-lock.json
- packages/comms/src/connection.ts
- packages/comms/src/ecl/query.ts
- packages/comms/src/ecl/result.ts
- packages/comms/src/ecl/store.ts
- packages/comms/src/ecl/targetCluster.ts
- packages/comms/src/ecl/workunit.ts
- packages/comms/src/espConnection.ts
- packages/comms/src/index-common.ts
- packages/comms/src/services/wsDFU.ts
- packages/comms/src/services/wsEcl.ts
- packages/comms/src/services/wsStore.ts
- packages/comms/src/services/wsTopology.ts
- packages/comms/src/services/wsWorkunits.ts
- packages/util/src/dispatch.ts
- packages/util/src/index.ts
- packages/util/src/stateful.ts
- tests/test-comms/src/ecl/store.spec.ts
- tests/test-comms/src/index.spec.ts
- tests/test-util/src/observer.spec.ts
- tests/test-util/src/stateful.spec.ts
- tests/test-util/src/types.spec.ts
Add new Dispatch / Observable pattern to @hpcc-js/util
> feat(WsStore): Add WsStore support to comms layer

- packages/comms/src/ecl/logicalFile.ts
- packages/comms/src/ecl/result.ts
- packages/comms/src/index-common.ts
- packages/comms/src/services/wsDFU.ts
> Logical file

- packages/comms/src/ecl/targetCluster.ts
- packages/comms/src/services/wsTopology.ts
> Default target cluster

- demos/dermatology/tests/chartFactory.js
- packages/chart/src/Column.ts
- packages/common/src/SVGWidget.ts
> fix: XYAxis values no longer overlapped by shapes

- packages/map/src/GMap.ts
- tests/test-comms/src/services/wsDFU.spec.ts
> GH-3258 Delay setting GMap API

- packages/comms/src/connection.ts
- tests/test-comms/src/ecl/workunit.spec.ts
- tests/test-comms/src/services/wsDFU.spec.ts
> feat(hookSend): Add optional "headers" option

- src/marshaller/HipieDDLMixin.js
> fix: modalIfData title no longer erased

- .github/stale.yml
> chore(issues): Add "Stale" app to monitor/close old issues

- demos/dashy/package.json
- demos/dermatology/package.json
- package.json
> chore(build): Bump lerna/local-web-server versions

- packages/comms/.vscode/tasks.json
- packages/comms/src/clienttools/eclcc.ts
> feat(eclcc):  Add basic support for EnvChk

- tests/test-comms/src/connection.spec.ts
> chore(serializeRequest): Add extra tests

- demos/gallery/.vscode/launch.json
- demos/gallery/samples/codemirror/DOT Editor.js
- packages/codemirror-shim/src/index.ts
- packages/codemirror-shim/src/mode/dot/dot.ts
- packages/codemirror/src/DOTEditor.ts
- packages/codemirror/src/index.ts
> feat(CodeMirror): Add support for DOT Language

- packages/layout/src/Legend.ts
> fix: Legend total translate fixed for IE

- apps/docs/index.html
- apps/docs/index.js
> fix(Gallery): Indexed gallery pulling sources from wrong location

- packages/chart/src/Pie.ts
> feat: Add showLabels to Pie.ts

- demos/gallery/samples/layout/Grid.js
- packages/layout/src/Grid.ts
- packages/layout/src/Surface.ts
Add adaptiveSnapping to Grid
Add altText to Surface
> feat: Add applyLayout to Grid

- demos/dashy/.vscode/launch.json
- demos/dashy/dashPOC2.html
- demos/dashy/dashy.code-workspace
- demos/dashy/src/dashPOC2.ts
- packages/marshaller/src/ddl2/dashboard.ts
- packages/marshaller/src/ddl2/model/vizChartPanel.ts
> fix(dashy): Flyout not rendering in runtime dashboard

- demos/dashy/src/dashPOC.ts
- packages/marshaller/src/ddl2/activities/databomb.ts
- packages/marshaller/src/ddl2/activities/datasource.ts
- packages/marshaller/src/ddl2/activities/dspicker.ts
- packages/marshaller/src/ddl2/activities/filter.ts
- packages/marshaller/src/ddl2/activities/groupby.ts
- packages/marshaller/src/ddl2/activities/limit.ts
- packages/marshaller/src/ddl2/activities/logicalfile.ts
- packages/marshaller/src/ddl2/activities/project.ts
- packages/marshaller/src/ddl2/activities/roxie.ts
- packages/marshaller/src/ddl2/activities/sort.ts
- packages/marshaller/src/ddl2/activities/wuresult.ts
- packages/marshaller/src/ddl2/dsTable.ts
- packages/marshaller/src/ddl2/pipelinePanel.ts
Add DDL editor for each activity
> feat(dashy): Preserve DDL fields on load.

- packages/marshaller/src/ddl2/activities/project.ts
When no child mappings are specified, include all (for consistency)
> fix(dashy): Mapped fields should include all children by default

- demos/dermatology/.vscode/launch.json
- packages/common/src/SVGWidget.ts
- packages/layout/src/ChartPanel.ts
> feat(ChartPanel): Download image includes legend (if visible)

- packages/chart/src/Pie.ts
> fix(pie): Conditionally center on labels

- .vscode/launch.json
- demos/dashy/.vscode/launch.json
- demos/dashy/src/index.ts
- packages/common/src/Widget.ts
- packages/ddl-shim/cli/index.ts
- packages/ddl-shim/src/ddl.ts
- packages/ddl-shim/src/dermatology.ts
- packages/ddl-shim/src/upgrade.ts
- packages/layout/src/Grid.ts
- packages/marshaller/src/dashy.ts
- packages/marshaller/src/ddl2/dashboard.ts
- packages/marshaller/src/ddl2/dashboardDockPanel.ts
- packages/marshaller/src/ddl2/dashboardGrid.ts
- packages/marshaller/src/ddl2/model/vizChartPanel.ts
Add DashboardGrid to marshaller
> feat(dashy): Add dermatology upgrade script to ddl-shim

- package-lock.json
- packages/chart/src/Column.ts
- packages/chart/src/Scatter.ts
- packages/chart/src/XYAxis.ts
- packages/comms/src/espConnection.ts
- packages/map/src/CanvasPins.ts
- packages/util/src/debounce.ts
> fix: Tweak sources to ensure compatibility with Angular 6

- packages/chart/src/Summary.css
> fix(chart): Remove dependency on Google font

- packages/api/src/Tooltip.ts
- packages/common/src/HTMLWidget.ts
- packages/common/src/SVGWidget.ts
> fix(style): Ensure "px" exists for top/left

- demos/quickstart/cdn_loader/.vscode/launch.json
- demos/quickstart/cdn_loader/index.html
> feat(quickstart):  Add CDN / Loader example

- demos/dashy/.vscode/launch.json
- demos/dashy/index.html
- demos/dashy/package.json
- demos/dashy/src/index.ts
> feat: Add option to render direct to Dashboard

- packages/marshaller/src/ddl2/activities/project.ts
- packages/marshaller/src/ddl2/model/visualization.ts
> fix(dashy): __lparam assigned wrong type

- utils/bundle/src/index.ts
> fix(build): Simplify bundle shim logic

- packages/marshaller/src/ddl2/dashboard.ts
- packages/marshaller/src/ddl2/model/visualization.ts
> fix(Dashy): Flyout menu not rendering on initial load

- packages/marshaller/src/ddl2/PopupManager.ts
- packages/marshaller/src/ddl2/dashboardDockPanel.ts
- packages/marshaller/src/ddl2/dashboardGrid.ts
> feat: Add PopupManager.ts

- packages/marshaller/src/ddl2/ddl.ts
> fix(DDL): Include all known fields in datasource section

- demos/dashy/dashy.code-workspace
- packages/chart/src/WordCloud.ts
> fix(WordCloud): Click event did not include entire row.

- packages/common/src/SVGWidget.ts
> feat(SVGWidget): Expose Blob Generation

- demos/dermatology/.vscode/launch.json
- demos/dermatology/tests/mapFactory.js
- packages/common/src/Widget.ts
- packages/map/src/leaflet/ClusterCircles.css
- packages/map/src/leaflet/ClusterCircles.ts
- packages/map/src/leaflet/Polygons.ts
- packages/map/src/leaflet/index.ts
> Cluster circles

- packages/chart/src/Summary.ts
> feat: Add two publish params to chart_Summary

- src/chart/Pie.js
> feat(v1): Add series percentage feature to PIE

- packages/comms/src/ecl/workunit.ts
- packages/util/src/stateful.ts
> fix(Workunit): Relax monitoring frequency

- src/other/Legend.js
> feat(v1): Add opacity to disabled Legend items

- demos/dermatology/tests/phosphorFactory.js
- packages/common/src/Widget.ts
> fix(widget): Skip render if size is invalid

- src/chart/Pie.js
> fix: Pie label size now refreshes before boxInArc

- packages/layout/src/Legend.ts
> fix(Legend): Fails to render when data is empty.

- packages/other/src/CalendarHeatMap.ts
> fix(CalendarHeatMap): Removed data fails to clear boxes

- src/common/Utility.js
- test/otherFactory.js
> fix(v1): normalize undefined or null sort values

- packages/marshaller/src/dashy.ts
- packages/marshaller/src/ddl2/pipelinePanel.ts
> feat(Dashy): Add PP to optionally disable activities in the pipeline.

- demos/dermatology/.vscode/launch.json
- demos/dermatology/tests/mapFactory.js
- packages/map/src/GMap.ts
> fix(GMap) Layers not rendering

- apps/headless/iife.html
- apps/headless/index.html
- apps/headless/params.js
> feat: Add apps/headless

- packages/layout/src/ChartPanel.ts
> feat(panel): Add file download name options

- packages/dgrid-shim/webpack.config.js
> fix(dgrid): Load blank.gif from CDN as needed

- test/marshallerFactory.js
> feat(v1): Add ddl1_modalIfData dermatology sample

- demos/dermatology/.vscode/launch.json
- packages/map/src/leaflet/Leaflet.ts
- packages/map/src/leaflet/OpenStreet.ts
> feat(map):  Add OpenStreet Base Map

- packages/marshaller/src/ddl2/activities/databomb.ts
- packages/marshaller/src/ddl2/activities/form.ts
- packages/marshaller/src/ddl2/dashboard.ts
> fix(dashy): Remove Form default values

- packages/marshaller/src/dashy.ts
- packages/marshaller/src/ddl2/activities/databomb.ts
- packages/marshaller/src/ddl2/activities/datasource.ts
- packages/marshaller/src/ddl2/activities/dspicker.ts
- packages/marshaller/src/ddl2/activities/form.ts
- packages/marshaller/src/ddl2/activities/logicalfile.ts
- packages/marshaller/src/ddl2/activities/wuresult.ts
> fix(dashy): Databomb + Form field coercion

- demos/dermatology/tests/mapFactory.js
- demos/gallery/.vscode/launch.json
- demos/gallery/samples/geospatial/Leaflet/Draw.js
- packages/map/rollup.config.js
- packages/map/src/leaflet/DrawLayer.ts
- packages/map/src/leaflet/index.ts
> feat(map):  Add draw layer to leaflet

- packages/layout/src/Modal.ts
- packages/marshaller/src/ddl2/PopupManager.ts
- packages/marshaller/src/ddl2/model/vizChartPanel.ts
> feat: Add intuitive closing logic for flyout

- packages/marshaller/src/ddl2/PopupManager.ts
- packages/marshaller/src/ddl2/dashboard.ts
- packages/marshaller/src/ddl2/model/vizChartPanel.ts
> fix(dashy): Flyout icon not rendering consistently

- packages/chart/docs/Area.md
- packages/chart/docs/Bar.md
- packages/chart/docs/HalfPie.md
- packages/chart/docs/Pie.md
- packages/chart/docs/QuarterPie.md
- website/index.html
- website/src/index.ts
- website/style/index.css
- website/util/index.ts
Tweak navigation scheme to use hash locations
Support partial paths in MD files.
> feat(docs): Add 6 chart md files with verbiage

- docs/index.md
- packages/chart/docs/Bar.md
- packages/chart/docs/Column.md
- website/index.html
- website/src/hpccIndex.css
- website/src/hpccIndex.ts
- website/src/markdown.css
- website/src/markdown.ts
- website/src/markdownPlugins/classMeta.ts
- website/src/markdownPlugins/index.ts
- website/src/markdownPlugins/publishedProperties.ts
- website/src/markdownPlugins/sampleCarousel.ts
Tweaked CSS to make more like GitHub
> feat(website) Add sample carousel

- docs/index.md
- docs/installation.md
- packages/chart/docs/index.md
- website/index.html
- website/src/markdown.css
- website/src/markdown.ts
- website/src/markdownPlugins/index.ts
- website/src/markdownPlugins/source.ts
> feat(website) Add initial installation docs

- packages/common/src/TitleBar.ts
> fix(TitleButton) FAChar didn't change on update

- packages/layout/src/Carousel.ts
> fix(Carousel) Better support for "undefined" active widget

- packages/common/src/Palette.ts
- packages/common/tsconfig.json
- packages/layout/src/Legend.ts
- packages/other/src/Legend.ts
- tslint.json
> chore(Palette) Add better typings for ordinal and rainbow

- packages/chart/docs/Area.md
- packages/chart/docs/Bar.md
- packages/chart/docs/Column.md
- packages/chart/docs/HalfPie.md
- packages/chart/docs/Pie.md
- packages/chart/docs/QuarterPie.md
- packages/common/docs/Palette.md
- packages/common/docs/index.md
- website/package.json
- website/src/index.ts
- website/src/markdown.ts
- website/src/markdownPlugins/classMeta.ts
- website/src/markdownPlugins/index.ts
- website/src/markdownPlugins/palette/ordinal.ts
- website/util/discover.ts
- website/util/docs.ts
- website/util/index.ts
- website/util/meta.ts
Improved "meta" processing
Move "meta" into html comment
> feat(Docs) Add Palette Documentation

- website/src/hpccScrollNav.ts
- website/src/index.ts
- website/src/markdown.ts
> feat(docs): Add sync rightnav marker scrolling

- packages/chart/docs/Gauge.md
- packages/chart/src/Gauge.ts
> feat(docs): Add Gauge.md

- packages/dgrid/src/RowFormatter.ts
- packages/form/src/Form.ts
- packages/marshaller/src/ddl2/activities/form.ts
> fix(marshaller): Finish support for databombs dataset fields

- demos/dermatology/tests/mapFactory.js
- packages/map/src/leaflet/Circles.ts
- packages/map/src/leaflet/FeatureLayer.ts
- packages/map/src/leaflet/Markers.ts
> feat(map): Add stroke and fill column support to Circles + D3Circles

- demos/dermatology/tests/chartFactory.js
- packages/chart/docs/Bullet.md
- packages/chart/src/Bullet.ts
Add ability to omit marker/range/measure columns
> feat(docs): Add Bullet md

- packages/chart/docs/WordCloud.md
- website/index.html
> feat(docs): Add WordCloud.md

- packages/map/src/leaflet/Markers.ts
> fix(Markers): Force tooltip and popup to strings

- demos/dashy/.vscode/launch.json
- demos/dashy/src/index.ts
- packages/marshaller/src/ddl2/activities/logicalfile.ts
- packages/marshaller/src/ddl2/activities/wuresult.ts
- packages/marshaller/src/ddl2/dashboard.ts
- packages/marshaller/src/ddl2/model/element.ts
Render dashboard on importDDL (to match Dashy)
> feat(dashy): Global override for sample sizes

- packages/marshaller/src/ddl2/activities/wuresult.ts
> fix(marshaller): ESPResult sampling is duplicating data

- packages/codemirror/docs/CSSEditor.md
- packages/codemirror/docs/ECLEditor.md
- packages/codemirror/docs/HTMLEditor.md
- packages/codemirror/docs/JSEditor.md
- packages/codemirror/docs/JSONEditor.md
- packages/codemirror/docs/MarkdownEditor.md
- packages/codemirror/docs/XMLEditor.md
> feat(docs): Add md files for codemirror package

- apps/scraped_imports/app.js
- apps/scraped_imports/scraped_imports.json
@GordonSmith this "apps" entry is a handy node script that makes it easy to browse widget imports
> feat: Add apps/scraped_imports

- packages/map-deck/src/Common.ts
This is an "at-runtime" feature. It seems that mapgl doesn't support the ability to add/remove layers after initialization?
> feat(map-deck): Add showBuildings to Common.ts

- packages/marshaller/src/ddl2/activities/project.ts
> fix(Dashy): Tweak Mappings mapped UI

- packages/marshaller/src/ddl2/ddl.ts
Refactor code to improve commoning up of datasources.
> fix(Dashy): Generated DDL for WUs + RoxieService Issue

- packages/chart/docs/Contour.md
- packages/chart/docs/HexBin.md
- packages/chart/src/Contour.ts
- packages/chart/src/HexBin.ts
> feat(docs): Add Contour and HexBin

- packages/map-deck/src/Common.ts
- packages/map-deck/tsconfig.json
- packages/map/src/leaflet/ClusterCircles.ts
> feat(map): Add weight format to Cluster Circles

- packages/chart/docs/Bubble.md
> feat(docs): Add Bubble.md

- packages/chart/docs/Area.md
- packages/chart/docs/Line.md
- packages/chart/docs/Scatter.md
- packages/chart/docs/Step.md
- packages/chart/src/Scatter.ts
Modified Area.md to match Line, Scatter and Step
Modified Scatter.ts to display text infront of line, area and data points
> feat(docs): Add Line.md, Scatter.md and Step.md

- packages/chart/docs/Gantt.md
> feat(docs): Add Gantt.md

- packages/chart/docs/Radar.md
- packages/chart/src/Radar.ts
Fixed Radar.ts fontFamily and fontSize properties
> feat(docs): Add Radar.md

- packages/comms/src/ecl/workunit.ts
- packages/comms/src/services/wsWorkunits.ts
- packages/ddl-shim/schema/.gitignore
- packages/ddl-shim/schema/.npmignore
Fixed possible issue with npm publish and DDL Schemas
> feat(comms): Add publish method to workunit.ts

- packages/chart/docs/Summary.md
- packages/chart/src/Summary.ts
Fixed Summary.ts moreText rendering issue that was preventing moreText content from rendering on the initial update call
> feat(docs): Add Summary.md

- website/style/index.css
> fix(docs): Add overflow-y scroll to leftnav

- index.html
- package-lock.json
- package.json
- utils/publish-gh-pages.js
> chore(gh-pages): Add publish scripts for gh-pages

- packages/dgrid/docs/Table.md
- website/style/index.css
> feat(doc): Add dgrid/docs/Table.md

- packages/layout/src/Legend.ts
> fix: Legend text alignment adjusted for IE

- packages/map/src/leaflet/GMap.ts
> fix(GMap): Incorrect developer attribution displayed

- packages/map/src/Layer.ts
> fix(GMapPin): Pins disappear when selected

- demos/gallery/samples/codemirror/ECLEditor.js
- packages/codemirror/src/Editor.css
- packages/codemirror/src/Editor.ts
> feat(codemirror): Add highlightError, highlightWarning and highlightInfo

- packages/common/src/Utility.ts
- packages/common/src/Widget.ts
> chore(textSize): Refactor textSize out of Widget

- packages/marshaller/src/ddl2/dashboardGrid.ts
> fix(Marshaller): Use public ID function

- packages/marshaller/src/ddl2/dashboardGrid.ts
- packages/util/src/array.ts
- tests/test-util/src/array.spec.ts
- tests/test-util/src/index.spec.ts
> feat(compare): New compare function for Object Arrays

- packages/common/src/SVGZoomWidget.ts
> chore(SVGZoomWidget): Minor refactor

- demos/dashy/package.json
- demos/dermatology/package.json
- package-lock.json
- package.json
> chore(security): Bump lerna and local-web-server versions.

- packages/common/src/Utility.ts
- packages/common/src/Widget.ts
> fix(textSize): Cached value should be readonly

- utils/publish-gh-pages.js
- website/package.json
> chore(website): Default to "no meta" for build.

- packages/util/src/graph2.ts
- packages/util/src/index.ts
> feat(util): Add new Graph data collection

- packages/comms/src/ecl/workunit.ts
- packages/comms/src/services/wsWorkunits.ts
- packages/eclwatch/docs/ECLArchiveViewer.md
- packages/eclwatch/package.json
- packages/eclwatch/src/ECLArchiveViewer.ts
- packages/eclwatch/src/index.ts
- packages/tree/src/DirectoryTree.ts
- packages/tree/src/index.ts
- tests/test-eclwatch/src/eclwatch.spec.ts
- tests/test-tree/src/tree.spec.ts
> feat: Add ECLArchiveViewer

- packages/comms/src/clienttools/eclcc.ts
> feat(comms): Expose binPath for eclcc

- packages/common/src/PropertyExt.ts
> feat(PP): Support serialized classes + AutoExpand

- demos/dashy/src/index.ts
- packages/marshaller/src/ddl2/activities/form.ts
- packages/marshaller/src/ddl2/dashboard.ts
> chore(Dashy): Tweak built-in samples

- packages/util/src/graph2.ts
> feat(util): Add Dijkstra algorithm to graph2

- packages/graph/docs/DataGraph.md
- packages/graph/src/Graph.ts
- packages/graph/src/graph2/dataGraph.ts
- packages/graph/src/graph2/graph.css
- packages/graph/src/graph2/graph.ts
- packages/graph/src/graph2/layouts/placeholders.ts
- packages/marshaller/src/ddl2/dashboard.ts
* Vertex Events
* Mouse over highlighting
* Customizable Vertices (TODO need solid example)
* Preservation of original data
* Set/Get current selection
> feat(Graph2): Various Graph2 improvements:

- package-lock.json
- packages/leaflet-shim/package.json
> fix(build): switch from git: to https: for github ref.

- packages/form/src/FieldForm.ts
> fix(Dashy): FieldForm had invalid mapping

- packages/common/src/PropertyExt.ts
- packages/marshaller/src/ddl2/activities/project.ts
> fix: Add noDeserialize to computedFields

- packages/layout/src/Border2.ts
Fixes #3488
I've viewed the related gallery and dermatology items.
> fix(Legend): Add room for scrollbar to display

- packages/graph/src/graph2/graph.ts
- [*] The commit message is properly formatted and free of typos.
- [*] The commit message title makes sense in a changelog, by itself.
- [*] The commit message includes a "fixes" reference if appropriate.
- [*] The commit is signed.
- [*] The change has been fully tested:
- [*] There are no similar instances of the same problem that should be addressed
> chore(graph2): Reordered a few methods

- packages/react/src/ImageChar.tsx
- packages/react/src/icon.tsx
- packages/react/src/shape.tsx
- packages/react/src/subgraph.tsx
- packages/react/src/text.tsx
> chore(react): Improved tsx template readability

- packages/graph/docs/Graph2.md
> fix(graph): Updated Graph2.md

- packages/chart/docs/StatChart.md
- packages/chart/src/QuartileCandlestick.ts
- packages/chart/src/StatChart.ts
- packages/chart/src/index.ts
- tests/test-chart/src/chart.spec.ts
> feat(chart): Add StatChart

- packages/chart/src/Gauge.ts
> feat(Gauge): Emphasis gauge is "clickable"

- apps/widget_tree/index.html
- packages/graph/src/graph2/graph.ts
- packages/react/src/index.ts
- packages/react/src/shape.tsx
- packages/react/src/text.tsx
- packages/react/src/vertex.tsx
- packages/react/src/vertex2.tsx
> feat(graph2): Add vertex2

- apps/widget_tree/index.html
- packages/graph/src/graph2/layouts/dagre.ts
- packages/react/src/shape.tsx
Improved readability in dagre.ts
Removed console log statement from shape.tsx
> feat(graph2): Improved widget_tree app

- apps/widget_tree/index.html
Improved apps/widget_tree stylings a bit
> feat(graph2): Add apps/square_root_tree

- packages/marshaller/src/ddl2/activities/rest.ts
> fix(dashy): no data when responseField === ""

- packages/react/src/ImageChar.tsx
- packages/react/src/icon.tsx
> feat: Add padding and yOffset to ImageChar

- packages/layout/src/Border2.ts
- packages/layout/src/Legend.ts
> fix: Legend scrolling issue

- packages/dgrid/src/Common.ts
- packages/dgrid/src/DBStore.ts
> feat(dgrid): Add multi select support

- packages/ddl-shim/src/ddl/v2.ts
- packages/marshaller/src/ddl2/activities/activity.ts
- packages/marshaller/src/ddl2/activities/databomb.ts
- packages/marshaller/src/ddl2/activities/datasource.ts
- packages/marshaller/src/ddl2/activities/dspicker.ts
- packages/marshaller/src/ddl2/activities/form.ts
- packages/marshaller/src/ddl2/activities/logicalfile.ts
- packages/marshaller/src/ddl2/activities/rest.ts
- packages/marshaller/src/ddl2/activities/roxie.ts
- packages/marshaller/src/ddl2/activities/wuresult.ts
- packages/marshaller/src/ddl2/ddl.ts
- packages/marshaller/src/ddl2/dsTable.ts
- packages/marshaller/src/ddl2/graphadapter.ts
> feat(Dashy): Improved REST support

- packages/dgrid/src/Common.ts
- packages/dgrid/src/DBStore.ts
- packages/marshaller/src/ddl2/model/element.ts
- packages/marshaller/src/ddl2/model/visualization.ts
> fix(dgrid): Click regression (multi selection)

- packages/util/src/graph2.ts
Removing a Vertex would leave a dangling edge.
> fix(Graph2): Removal of Vertex Issue

- packages/layout/src/Legend.ts
> fix(Legend): _boundingBox may be undefined

- packages/util/src/array.ts
> fix(Compare2): Remove O^2 algorithm

- packages/common/src/Utility.ts
> chore(SelectionBag): Add typings to Selection Bag

- packages/tree/src/DirectoryTree.ts
> feat(tree): Add more flexibility to DirectoryTree

- packages/graph/package.json
- packages/loader/package.json
> chore(@hpcc-js/wasm): Bump @hpcc-js/wasm to latest

- packages/comms/src/services/wsEcl.ts
- packages/ddl-shim/src/ddl/v2.ts
- packages/marshaller/src/ddl2/activities/rest.ts
- packages/marshaller/src/ddl2/activities/roxie.ts
- packages/marshaller/src/ddl2/ddl.ts
- packages/marshaller/src/ddl2/pipelinePanel.ts
> feat(Dashy):  Add support for "set" HIPIE inputs

- packages/tree/src/DirectoryTree.ts
> feat: Added omitRoot to DirectoryTree

- packages/ddl-shim/package.json
> chore(build): Add missing file to release.

- packages/tree/src/DirectoryTree.ts
> feat: Restyle DirectoryTree interactions

- package.json
- packages/util/src/platform.ts
- tests/test-comms/src/connection.spec.ts
Add code to detect GitHub environment
Enable full comms test suite
> chore(build): Switch to GitHub Actions for CI

- packages/marshaller/src/dashy.css
> fix(Dashy): Remove stray CSS

- package.json
- utils/purge-jsdelivr.js
> chore(build): Add script to purge JSDelivr CDN

- packages/comms/src/services/wsMachine.ts
> fix(GetTargetClusterUsageEx): Check for omitted responses

- packages/common/src/TitleBar.ts
> fix(TitleBar):  Select had incorrect "selected" value.

- packages/marshaller/src/dashy.ts
> Add "Save" option to DDL View

- packages/codemirror/src/Editor.css
> fix: Editor warning style priority

- demos/dermatology/tests/dgridFactory.js
- packages/dgrid/src/DatasourceStore.ts
- packages/dgrid/src/RowFormatter.ts
- packages/dgrid/src/Table.ts
> fix(dgrid): Nested tables not rendering correctly

- packages/util/src/dispatch.ts
> feat(dispatch): Add better typing for dispatch messages

- packages/common/src/Database.ts
> fix(PropertyExt): Legacy code - "super" getting called twice.

- packages/codemirror-shim/src/index.ts
- packages/codemirror-shim/src/mode/markdown/markdown.ts
- packages/codemirror/src/Editor.ts
- packages/codemirror/src/MarkdownEditor.ts
- packages/codemirror/src/ObservableMarkdownEditor.ts
- packages/codemirror/src/index.ts
Add option to default code sections to specific language.
> feat(codemirror): Switch Markdown to GitHub Flavour Markdown

- packages/common/src/Widget.ts
> feat: lazyRender returns this

- demos/gallery/samples/table/Nested Data.js
- demos/gallery/src-umd/config.js
- package-lock.json
- packages/dgrid/src/Common.ts
- packages/dgrid/src/DBStore.ts
- packages/dgrid/src/DatasourceStore.ts
- packages/dgrid/src/DatasourceTable.ts
- packages/dgrid/src/RowFormatter.ts
- packages/eclwatch/src/WUResult.ts
- packages/eclwatch/src/WUResultStore.ts
Optionally disable (to ensure backward compatibility).
Fixes #3573
> fix(dgrid): Allow embedding of html by default

- packages/dgrid/src/Table.ts
> fix(dgrid): Formatter cell renderer regression

- demos/gallery/samples/chart/Column/ColumnWithIcons.js
- demos/gallery/src-umd/config.js
- packages/chart/src/Axis.ts
- packages/chart/src/XYAxis.ts
> feat: Add fontSize and fontFamily to Axis

- demos/gallery/samples/graph2/500 Nodes.js
- demos/gallery/samples/graph2/Subgraphs.js
- packages/graph/src/graph2/graph.ts
- packages/graph/src/graph2/layouts/placeholders.ts
- packages/react/src/subgraph.tsx
- packages/react/src/text.tsx
- packages/react/src/vertex.tsx
- packages/react/src/vertex2.tsx
> feat(graph) Add font family support to graph2

- packages/chart/src/Column.ts
- packages/chart/src/Scatter.ts
> feat: Add __lparam to color callbacks

- package-lock.json
- packages/ddl-shim/package.json
- packages/ddl-shim/rollup.config.js
> fix(ddl-shim): npx @hpcc-js/ddl-shim not working

- demos/dashy/src/dashPOC.ts
- packages/ddl-shim/src/ddl/v2.ts
- packages/ddl-shim/src/upgrade.ts
- packages/graph/src/graph2/dataGraph.ts
- packages/graph/src/graph2/graph.ts
- packages/marshaller/src/ddl2/ddl.ts
- packages/marshaller/src/ddl2/graphadapter.ts
- packages/marshaller/src/ddl2/javascriptadapter.ts
- packages/marshaller/src/ddl2/model/element.ts
- packages/marshaller/src/ddl2/model/visualization.ts
> feat (dashy):  Initial support for Dual Table graph

- packages/ddl-shim/src/upgrade.ts
> fix(ddl upgrade): Catch mismatched mapping issue

- demos/gallery/samples/chart/InnerTextBar.js
- demos/gallery/src-umd/config.js
- packages/chart/src/Column.ts
> feat: Add Column innerText and value font props

- demos/gallery/src-umd/config.js
> fix: Removed two empty gallery sample folders

- packages/map/src/leaflet/MapBox.ts
Previous API expires June 1, 2020
> fix(MapBox): Upgrade to latest MapBox API

- packages/common/src/Widget.ts
> fix(lazyRender): callback failing regression

- demos/gallery/samples/codemirror/ReadOnly.js
- demos/gallery/src-umd/config.js
- packages/codemirror/src/Editor.ts
> feat: Add readOnly mode to Editor.ts

- packages/comms/.vscode/tasks.json
- packages/comms/src/ecl/store.ts
- packages/comms/src/services/wsMachine.ts
Add additional check for disk usage.
> fix(WsStore):  Assume WsStore may not exist

- demos/dashy/.vscode/tasks.json
> chore(Dashy): Tweak build tasks

- packages/graph/src/graph2/dataGraph.ts
- packages/marshaller/src/ddl2/javascriptadapter.ts
- packages/marshaller/src/ddl2/model/element.ts
- packages/marshaller/src/ddl2/model/visualization.ts
- packages/util/src/graph2.ts
> fix(Dashy): DataGraph not clearing on new selection.

- package-lock.json
- packages/graph/package.json
- packages/loader/package.json
> fix(wasm): Graph layouts can get out of sync with current wasm versions

- .vscode/tasks.json
- package.json
- packages/api/src/I2DChart.ts
- packages/api/src/INDChart.ts
Tweaked default global compile to work in GIT Bash
Fixes #3604
> fix(API): origRow not being passed through for all colour calls

- demos/gallery/samples/chart/Bar/Inner Text With Icons.js
- packages/chart/src/Axis.ts
- packages/chart/src/Column.ts
- packages/chart/src/XYAxis.ts
Tweaked default global compile to work in GIT Bash
Fixes #3606
> fix(Bar): Alternative approach to Axis Icon mappings

- apps/arjuna_map/index.html
- packages/map/src/leaflet/Text.ts
- packages/map/src/leaflet/index.ts
> feat: Add Text leaflet layer

- demos/dashy/src/dashPOC.ts
> chore: Fix sample.

- packages/codemirror-shim/src/index.ts
- packages/codemirror/docs/CSSEditor.md
- packages/codemirror/docs/ECLEditor.md
- packages/codemirror/docs/Editor.md
- packages/codemirror/docs/HTMLEditor.md
- packages/codemirror/docs/JSEditor.md
- packages/codemirror/docs/JSONEditor.md
- packages/codemirror/docs/MarkdownEditor.md
- packages/codemirror/docs/XMLEditor.md
> feat: Add search/replace to Editor

- packages/graph/src/graph2/graph.ts
- packages/graph/src/graph2/layouts/placeholders.ts
> feat: Add hideVertex and showVertex to graph2

- packages/deck-shim/package.json
- packages/deck-shim/webpack.config.js
- packages/dgrid-shim/package.json
- packages/dgrid-shim/webpack.config.js
- packages/leaflet-shim/package.json
- packages/leaflet-shim/webpack.config.js
> chore(webpack): Switch to Terser from Uglify

- packages/observable-md/src/ojsRuntime.ts
Needs a namespace to avoid clashes
> fix(Observable): Remove hpcc stdlib

- demos/gallery/galleryItem.html
- demos/gallery/playground.html
> fix: Preloading fonts in gallery

- packages/graph/src/graph2/layouts/graphviz.ts
- packages/graph/workers/src/graphviz.ts
> fix(graph): GraphViz edges may have no pos

- packages/chart/src/Column.ts
> fix: Apply font-family to inner text element

- packages/graph/src/graph2/graph.ts
> feat: Add automatic edge validation to Graph2

- demos/dashy/src/dashPOC.ts
- packages/marshaller/src/ddl2/javascriptadapter.ts
- packages/marshaller/src/ddl2/model/element.ts
- packages/marshaller/src/ddl2/model/visualization.ts
- packages/util/src/graph2.ts
Secondary data-sources were not being calculated before the Graph was rendered.
Add topological sort to Graph.
> fix(dashy):  Race condition

- packages/chart/src/Column.ts
> feat: Improved Bar and Column tooltip handling

- packages/chart/src/Column.ts
- packages/common/src/Text.ts
> fix: Column/Bar events moved to parent dataCell

- packages/chart/src/Column.ts
> fix: ellipsis tooltip shows for any truncated row

- packages/util/src/math.ts
- tests/test-util/src/math.spec.ts
> feat: Add polar coordinate functions to util

- .travis.yml
- package.json
- src/config.js
- src/goog.js
- src/loader.js
> fix(google charts): Tweak loader to work with gstatic

- packages/react/src/vertex3.tsx
> feat: Vertex3 omits subtext for subText empty str

- demos/gallery/samples/graph2/RIN.js
- packages/graph/src/graph2/graph.ts
> feat: Add graph2 vertex_dblclick

- packages/timeline/src/MiniGantt.ts
> feat: Improved MiniGantt render performance

- packages/graph/index.html
- packages/graph/src/graph2/graph.ts
- packages/graph/src/graph2/layouts/tree.ts
* Tree
* RadialTree
* Dendrogram
* RadialDendrogram
> feat(Graph2):  Additional Layouts

- apps/graph2/color_data.js
- apps/graph2/images.html
- apps/graph2/rectangles.html
> feat: Add apps/graph2 for stress testing

- packages/graph/src/graph2/graph.ts
- packages/react/src/vertex.tsx
> feat: Add Graph2 property showVertexLabels

- packages/graph/src/graph2/graph.ts
> fix: Graph2 centerOnItem works as expected

- packages/react/src/vertex3.tsx
> feat: Vertex3 placement adjusts for missing data

- apps/graph2/color_data.js
- apps/graph2/rectangles.html
- packages/graph/package.json
- packages/graph/src/graph2/dataGraph.ts
- packages/graph/src/graph2/graph.ts
- packages/graph/src/graph2/layouts/placeholders.ts
- packages/html/src/HTMLTooltip.ts
> feat(Graph2): Add vertex tooltip support

- demos/gallery/samples/codemirror/Line Comments.js
- demos/gallery/src-umd/config.js
- packages/codemirror/src/Editor.ts
> feat: Add codemirror line comments

- packages/dataflow/package.json
> chore(build): Remove not needed dependency

- .github/workflows/testPullRequest.yml
> chore(build): Migrate to "trunk" as default branch

- packages/comms/src/ecl/workunit.ts
> feat(comms): Allow user to specify nested filter scope for graphs

- packages/comms/src/ecl/graph.ts
- packages/comms/src/ecl/workunit.ts
> feat(comms): Include functions when creating graph

- demos/gallery/samples/geospatial/Google Maps/StreetView.js
- demos/gallery/samples/geospatial/Google Maps/StreetView2.js
- demos/gallery/src-umd/config.js
- packages/map/src/GMap.ts
> feat: Add useComputedHeading to GMap streetView

- packages/chart/src/Pie.ts
> fix: Pie label click passes correct selection

- packages/dataflow/package.json
> chore(package): Include source files (for map resolution).

- packages/eclwatch/src/WUTimeline.ts
- packages/html/src/HTMLTooltip.ts
- packages/react/src/text.tsx
- packages/timeline/src/ReactAxisGantt.ts
- packages/timeline/src/ReactGantt.ts
- packages/timeline/src/ReactTimeline.ts
> feat: Add MiniGantt back compat to React timeline

- packages/chart/package.json
- packages/chart/src/Heat.ts
Removed reference to "simpleheat"
> feat(HeatChart):  Add support for elliptical "blobs"

- packages/eclwatch/src/WUResultStore.ts
> fix(eclwatch): Nested results not displaying correctly

- packages/codemirror/src/Editor.ts
- packages/html/src/HTMLTooltip.ts
- packages/tree/src/DirectoryTree.ts
Fixed HTMLTooltip.ts sizing bug
Added markerTextAlign to codemirror_Editor
Added fontFamily, fontSize, onmouseenter and onmouseleave to codemirror_Editor addGutterMarker method
> feat: Added weight markers to DirectoryTree.ts

- packages/comms/src/clienttools/eclcc.ts
- packages/comms/src/ecl/workunit.ts
- packages/dgrid/src/DatasourceStore.ts
- packages/dgrid/src/Table.ts
- packages/eclwatch/src/WUResultStore.ts
- packages/graph/src/Graph.ts
- packages/marshaller/src/ddl2/activities/roxie.ts
- packages/marshaller/src/ddl2/javascriptadapter.ts
Switched to replace all as appropriate
> fix: Potential replace issues

- demos/gallery/samples/geospatial/Google Maps/StreetView2.js
- packages/map/src/GMap.ts
> feat: Add outdoorStreetViewOnly to GMap

- packages/comms/src/ecl/topology.ts
> feat(comms):  Add support for LogicalClusters

- demos/gallery/samples/layout/Chart Panel2.js
- demos/gallery/samples/layout/Chart Panel3.js
- demos/gallery/samples/layout/Chart Panel4.js
- demos/gallery/samples/layout/Chart Panel5.js
- demos/gallery/samples/layout/Chart Panel6.js
- demos/gallery/src-umd/config.js
- packages/common/src/SVGWidget.ts
- packages/layout/src/Border2.css
- packages/layout/src/Border2.ts
- packages/layout/src/ChartPanel.ts
- packages/layout/src/Legend.ts
Fixes #3710
Fixes #3697
Adds 6 symbol legend shapes
Adds label alignment options
Adds bottom legend feature to ChartPanel
> feat: Add enhancements to Legend

- packages/comms/src/connection.ts
- packages/comms/src/ecl/result.ts
- packages/comms/src/espConnection.ts
- packages/comms/src/services/wsWorkunits.ts
Also added to Result.fetchRows
> feat(comms): Added abort option to WUResult

- demos/gallery/samples/geospatial/Google Maps/StreetView3.js
- demos/gallery/src-umd/config.js
- packages/map/src/GMap.ts
> feat: Add GMap option for error response callback

- packages/comms/src/ecl/xsdParser.ts
- packages/dgrid/src/DBStore.ts
- packages/dgrid/src/DatasourceStore.ts
- packages/dgrid/src/RowFormatter.ts
- packages/eclwatch/src/WUResultStore.ts
> fix(Result):  Improved SET OF support

- packages/comms/src/clienttools/eclcc.ts
> feat(bundle):  Add initial bundle support

- packages/comms/src/services/wsAccount.ts
> fix(WsAccount): Improve "Old Client" response

- demos/gallery/.vscode/launch.json
- packages/graph/src/graph2/graph.ts
> fix(graph2): Layout not triggered on option change

- packages/comms/src/ecl/result.ts
> fix(comms):  Result value not getting updated in cache

- packages/util/src/graph2.ts
- tests/test-util/src/graph2.spec.ts
- tests/test-util/src/index.spec.ts
Added graph2 unit tests
Fixes #3729
> fix(util): Graph2 remove inEdge bug

- packages/timeline/src/ReactGantt.ts
> fix: Add deselection to ReactGantt

- apps/graph2/centroid.html
- apps/graph2/fa_centroids.html
- demos/gallery/samples/chart/dataMeta/PieColumn.js
- packages/common/src/Utility.ts
- packages/common/src/Widget.ts
- packages/graph/src/graph2/graph.ts
- packages/graph/src/graph2/layouts/circle.ts
- packages/graph/src/graph2/layouts/dagre.ts
- packages/graph/src/graph2/layouts/forceDirected.ts
- packages/graph/src/graph2/layouts/forceDirectedWorker.ts
- packages/graph/src/graph2/layouts/graphviz.ts
- packages/graph/src/graph2/layouts/null.ts
- packages/graph/src/graph2/layouts/tree.ts
- packages/graph/src/test.ts
- packages/graph/workers/src/forceDirectedOptions.ts
- packages/react/src/ImageChar.tsx
- packages/react/src/icon.tsx
feat: Add textRect to common Utility
feat(graph2): Add Force Directed option to pin centroid
> feat: Add several publish properties to Graph2

- .github/workflows/codeql-analysis.yml
- .github/workflows/ossar-analysis.yml
> chore(security):  Exclude demos and snippets

- packages/comms/src/index-common.ts
- packages/comms/src/services/wsCodesign.ts
> feat(comms): Add ws_codesign support

- packages/util/src/object.ts
> fix(security): Potential prototype pollution

- packages/marshaller/src/ddl2/activities/roxie.ts
> fix(security):  Incorrect suffix check

- packages/dataflow/src/__tests__/histogram.ts
- packages/dataflow/src/activities/histogram.ts
> fix(histogram):  Generator input could fail

- packages/comms/src/ecl/topology.ts
- packages/comms/src/services/wsTopology.ts
> feat(TpLogicalClusterQuery):  Add support for latest API

- packages/eclwatch/src/WUTimeline.ts
> fix(WUTimeline):  Invalid calcTooltip call

- packages/comms/src/ecl/workunit.ts
- packages/comms/src/services/wsWorkunits.ts
> feat(WUInfo):  Update to latest WUInfo call

- packages/comms/src/ecl/workunit.ts
> feat(Workunit):  Add compile static method

- package-lock.json
- packages/observable-md/package.json
> chore(observable):  Bump version

- packages/comms/src/services/wsCodesign.ts
> feat(CodeSign): Upgrade to latest API

- packages/comms/src/services/wsCodesign.ts
> fix(sign): SigningMethod should be optional

- packages/comms/src/ecl/workunit.ts
> feat(Workunit): Expose WUInfo call

- packages/comms/src/ecl/activity.ts
- packages/comms/src/ecl/workunit.ts
- packages/comms/src/services/wsSMC.ts
> feat(WsSMC): Update service to latest version

- packages/util/src/stateful.ts
> fix(stateful):  Switch to deepEquals for void()

- packages/common/src/Utility.ts
- packages/graph/src/graph2/graph.ts
> fix(graph2): Ctrl+Click should multi select

- packages/common/.vscode/tasks.json
- packages/common/src/SVGZoomWidget.css
- packages/common/src/SVGZoomWidget.ts
- packages/common/src/Utility.ts
- packages/comms/.vscode/tasks.json
- packages/graph/src/graph2/graph.ts
- packages/graph/src/test.ts
> feat(graph2): Add marquee selection mode

- packages/graph/src/graph2/graph.ts
- packages/graph/src/graph2/layouts/forceDirected.ts
- packages/graph/src/graph2/layouts/forceDirectedWorker.ts
- packages/graph/workers/src/forceDirectedOptions.ts
> feat(graph): Add params for d3 force

- packages/graph/src/graph2/graph.css
- packages/graph/src/graph2/graph.ts
> feat(graph): Add move all selected on drag

- package-lock.json
- packages/common/src/SVGZoomWidget.ts
- packages/graph/package.json
- packages/loader/package.json
Bump @hpcc-js/wasm to latest version
> fix(graph):  Zoom to fit regression

- packages/graph/index.html
- packages/graph/src/Graph.ts
- packages/graph/src/graph2/graph.ts
- packages/graph/src/test.ts
Fix invalid d3Event calls.
Fixes #3775
> fix(graph): Prevent double click vertex from zooming in

- packages/graph/src/graph2/graph.ts
> fix(graph): Add dblclick to drag end callback

- package-lock.json
- packages/comms/package.json
- tests/test-util/src/index.spec.ts
- tests/test-util/src/xmldom.spec.ts
> fix(security):  Bump xmldom to latest version

- packages/chart/src/Heat.ts
> fix(chart): Set Heat bg color to transparent

- packages/common/src/TitleBar.ts
> feat: TitleBar long titles are now truncated

- packages/map/src/GMap.ts
> feat: Add ability to override google within GMap

- packages/map/src/GMap.ts
Added new function requireGoogleMapTimeout to adjust the default (15000ms)
> feat:  Add timeout to Google Map API loader

- package-lock.json
- packages/graph/package.json
- packages/loader/package.json
- website/package-lock.json
- website/package.json
Bump website package-lock.json
> fix:  Bump @hpcc-js/wasm to latest

- apps/docs/index.css
- apps/docs/index.html
- apps/docs/index.js
- apps/docs/index.sass
> fix: Fixed index page

- packages/codemirror/src/Editor.ts
> feat: Expose codemirror setOption method

- packages/codemirror/src/Editor.ts
fixes #3796 
add getLineLength function to Editor
> feat(codemirror): Add method to get line length

- packages/comms/src/ecl/result.ts
- packages/dgrid/.vscode/tasks.json
- packages/dgrid/src/Common.ts
- packages/eclwatch/.vscode/tasks.json
- packages/eclwatch/src/WUResult.ts
- packages/eclwatch/src/WUResultStore.ts
Add option to change default page size
Add 50 to list of default page sizes
> feat(WUResult):  Add optional filter

- package-lock.json
- packages/observable-md/README.md
- packages/observable-md/index.html
- packages/observable-md/package.json
> chore(ObservableMD):  Bump versions

- packages/graph/src/graph2/graph.ts
- packages/graph/src/test.ts
- packages/react/src/vertex3.tsx
> feat(graph): Show labels on hover while hidden

- packages/util/.vscode/tasks.json
- packages/util/src/platform.ts
- tests/test-comms/src/services/wsWorkunits.spec.ts
> fix:  Remove evaluation code to prevent downstream security warnings

- packages/comms/src/ecl/logicalFile.ts
- packages/comms/src/services/wsDFU.ts
> feat(comms): Update WsDFU API

- packages/comms/src/services/wsWorkunits.ts
These are relatively new options, that were previous defaulted to true.
> fix(comms):  Some "lite" items should be defaulted to true

- packages/comms/src/ecl/logicalFile.ts
> feat:  Add update method to LogicalFile

- package-lock.json
- packages/observable-md/.vscode/launch.json
- packages/observable-md/.vscode/tasks.json
- packages/observable-md/package.json
> feat:  Bump observable version

- demos/dashy/src/index.ts
- packages/comms/src/ecl/result.ts
- packages/comms/src/ecl/workunit.ts
- packages/eclwatch/src/WUResult.ts
- packages/marshaller/src/ddl2/activities/logicalfile.ts
- packages/marshaller/src/ddl2/activities/wuresult.ts
> fix(comms): expose NodeGroup property for logical files

- packages/dgrid-shim/src/gridHelper.ts
- packages/dgrid/src/Common.ts
> feat(dgrid):  Allow selection to be set

- packages/comms/src/ecl/result.ts
- packages/comms/src/services/wsWorkunits.ts
- tests/test-comms/src/ecl/workunit.spec.ts
> fix:  WUResult state not being initialized correctly.

- packages/comms/src/__tests__/workunit.ts
- packages/comms/src/ecl/workunit.ts
- packages/comms/src/services/wsWorkunits.ts
- packages/graph/package.json
- packages/loader/package.json
- packages/util/src/debounce.ts
- tests/test-comms/src/ecl/workunit.spec.ts
Bump wasm graph version.
Add Util.sleep function.
Fixes #3829
> fix:  Workunit.clone() fails.

- packages/observable-md/src/observable.ts
- packages/observable-md/src/ojsRuntime.ts
> fix(observable):  Plugins are being ignored

- packages/observable-md/src/observable.css
> fix:  css ID regression

- packages/deck-shim/package.json
> chore(security):  Bump Deck to latest version

- packages/chart/src/StatChart.ts
- packages/timeline/src/ReactAxisGantt.ts
- packages/timeline/src/ReactAxisGanttSeries.ts
- packages/timeline/src/ReactGantt.ts
Added 2 pixel x-offset to candlestick widget in StatChart
> feat: Add bucketColumn to ReactGantt

- packages/comms/src/ecl/query.ts
- packages/comms/src/services/wsWorkunits.ts
> feat(comms):  Add WUQueryGetSummaryStats to Query

- package-lock.json
- packages/observable-md/index.html
- packages/observable-md/package.json
- packages/observable-md/src/ojsRuntime.ts
- packages/observable-md/src/omdRuntime.ts
- packages/observable-md/src/util.ts
> chore(observable-md):  Minor cleanup

- packages/comms/src/ecl/topology.ts
> feat(comms):  Add fetchServices to Topology

- package-lock.json
- packages/deck-shim/.vscode/tasks.json
- packages/deck-shim/package.json
- packages/map-deck/.vscode/launch.json
- packages/map-deck/.vscode/tasks.json
- packages/map-deck/index.html
- packages/map-deck/src/Common.ts
- packages/map-deck/src/test.ts
> fix(map-deck):  Rendering regression

- packages/util/src/logging.ts
> feat(logging):  Add ability to override raw writing

- packages/phosphor/src/DockPanel.ts
> fix:  Dock Panel is not cleaning up when removed from page

- packages/observable-md/package.json
> chore:  Bump observable runtime

- packages/comms/src/clienttools/eclcc.ts
> fix(clientTools):  Exclude broken client tools

- packages/comms/src/ecl/workunit.ts
- packages/graph/.vscode/tasks.json
> fix(comms):  Workunit details should include formatted properties

- packages/graph/src/graph2/graph.ts
> fix(graph):  Support multi line edge labels

- packages/graph/src/graph2/graph.ts
> fix(graph):  Regression in previous PR

- packages/comms/src/ecl/logicalFile.ts
- packages/comms/src/services/wsAccount.ts
- packages/comms/src/services/wsDFU.ts
Added DefFile, History support to logicalFile
Updated interfaces for WsAccount
> feat(comms):  Update WsDFU and WsAccount

- packages/codemirror/src/Editor.ts
> feat: Add onclick to codemirror gutter markers

- packages/comms/src/ecl/logicalFile.ts
- packages/comms/src/services/wsDFU.ts
> fix:  Bump WsDFU version to v1.60

- demos/gallery/src-umd/devConfig.js
- demos/gallery/src/devConfig.ts
- package.json
- packages/common/package.json
- packages/common/rollup.config.js
- packages/loader/src/meta.ts
> chore:  Bump colorbrewer version

- packages/util/src/graph2.ts
> feat:  Add support for numeric IDs

- packages/common/src/Utility.ts
> fix:  textSize can leave remnants

- demos/gallery/samples/graph/Sankey.js
- demos/gallery/samples/graph/SankeyValues.js
- packages/graph/src/graph2/dataGraph.ts
- packages/graph/src/graph2/graph.ts
- packages/graph/src/graph2/index.ts
- packages/graph/src/graph2/layouts/graphviz.ts
- packages/graph/src/graph2/sankeyGraph.ts
- packages/graph/workers/rollup.config.js
- tests/test-graph/src/graph.spec.ts
> feat:  Add SankeyGraph

- packages/comms/src/ecl/result.ts
> fix(WU Result):  Refreshing the result list ignores changes

- demos/gallery/samples/graph2/DataGraph.js
- demos/gallery/src-umd/config.js
- packages/graph/src/graph2/dataGraph.ts
- packages/graph/src/graph2/graph.ts
- packages/graph/src/graph2/layouts/placeholders.ts
> feat: Add edgeColorColumn to DataGraph

- packages/comms/src/ecl/activity.ts
> feat: Add setBanner to Activity

- packages/graph/src/graph2/dataGraph.ts
- packages/graph/src/graph2/sankeyGraph.css
- packages/graph/src/graph2/sankeyGraph.ts
- packages/graph/src/test.ts
> fix:  Add missing css for SankeyGraph

- packages/graph/src/Sankey.ts
> fix: Sankey data points mapped

- apps/xml_to_tree/index.html
- apps/xml_to_tree/xml2.hml
> feat: Add xml_to_tree app

- packages/comms/src/services/wsWorkunits.ts
> feat(comms): Add missing cost properties for WUQuery response

- packages/comms/src/services/wsDFU.ts
> feat(comms): Add missing cost property for DFUQuery response

- packages/observable-md/package.json
- packages/observable-shim/package.json
> chore(observable): Fix dependency issue

- packages/common/src/PropertyExt.ts
> fix: Drag end event has no stopPropagation

- packages/observable-shim/package.json
- packages/observable-shim/rollup.config.js
> fix(observable-shim):  Package failed to build

- packages/marshaller/src/ddl2/model/visualization.ts
- packages/react/src/vertex3.tsx
> fix(marshaller):  DataGraph should merge data by default

- packages/dataflow/package.json
> chore:  Reset dataflow version

- packages/comms/src/ecl/workunit.ts
> feat(comms):  Add support for "cost" metric

- packages/comms/src/index-common.ts
- packages/comms/src/services/wsLogaccess.ts
- packages/comms/src/services/wsdl/WsLogaccess/v1/WsLogaccess.ts
> feat(comms): Add WsLogaccess service

- packages/comms/src/index-common.ts
- packages/comms/src/services/wsResources.ts
- packages/comms/src/services/wsdl/WsResources/v1.01/WsResources.ts
> feat(comms):  Add WsReources Service

- packages/comms/src/ecl/machine.ts
- packages/comms/src/ecl/targetCluster.ts
- packages/comms/src/services/wsMachine.ts
- packages/comms/src/services/wsdl/WsMachine/v1.17/WsMachine.ts
- packages/comms/src/services/wsdl/ws_machine/v1.17/ws_machine.ts
> feat(comms): extend ws_machine to use interfaces generated from WSDL

- packages/comms/src/index-common.ts
- packages/comms/src/services/wsAccess.ts
- packages/comms/src/services/wsdl/ws_access/v1.16/ws_access.ts
- tests/test-comms/src/index.spec.ts
- tests/test-comms/src/services/wsAccess.spec.ts
> feat(comms): extend ws_access to use interfaces generated from WSDL

- packages/comms/src/services/wsAccess.ts
- packages/comms/src/services/wsLogaccess.ts
- packages/comms/src/services/wsMachine.ts
- packages/comms/src/services/wsdl/ws_access/v1.16/ws_access.ts
- packages/comms/src/services/wsdl/ws_logaccess/v1/ws_logaccess.ts
- packages/comms/src/services/wsdl/ws_machine/v1.17/ws_machine.ts
- packages/comms/utils/index.ts
> fix(comms): change names of classes generated from wsdl to ...ServiceBase

- packages/comms/src/ecl/targetCluster.ts
- packages/comms/src/services/wsMachine.ts
> fix(comms): revert change to GetTargetClusterUsageEx number of params

- packages/graph/src/test.ts
- packages/graph/workers/rollup.config.js
> fix:  Graph regression (missing graphlib in bundle)

- packages/comms/package.json
- packages/comms/src/services/wsDali.ts
- packages/comms/src/services/wsdl/WsDali/v1.04/WsDali.ts
- packages/comms/utils/index.ts
> feat(comms): Add WsDali service

- packages/chart/src/Pie.ts
> feat(pie): Add selectByLabel

- packages/chart/.vscode/launch.json
- packages/chart/.vscode/tasks.json
- packages/chart/index.html
- packages/chart/src/Pie.ts
- packages/chart/src/test.ts
- packages/common/src/Utility.ts
> feat(Pie):  Add support for set selection

- packages/layout/src/ChartPanel.ts
> fix: ChartPanel legend hides when dataVisible

- package-lock.json
- packages/dgrid2/src/table.tsx
- packages/layout/package.json
- packages/layout/src/ChartPanel.ts
> fix:  Switch to grid2 for layout

- apps/angular-13/README.md
- apps/angular-13/angular.json
- apps/angular-13/package-lock.json
- apps/angular-13/package.json
- apps/angular-13/src/index.html
- apps/angular-13/webpack-append.config.js
> chore:  Update Angular 13 demo to use latest versions

- packages/comms/src/services/wsCloud.ts
- packages/util/src/immutable.ts
> fix(WsCloud):  Extra parsing for Result: "string" in GetPODs

- components/layout/src/lumino/dockPanel.md
- components/layout/src/lumino/dockPanel.ts
- components/layout/src/lumino/splitPanel.md
- components/layout/src/lumino/splitPanel.ts
- components/layout/src/lumino/tabPanel.md
- components/layout/src/lumino/tabPanel.ts
> fix(wc-layout):  Document and expose lumino events

- package-lock.json
- packages/comms/package.json
- packages/comms/utils/index.ts
> feat(wsdl): use typescript-formatter to reformat .ts files according to rules

- packages/comms/src/services/wsTopology.ts
> fix(comms): bump version for WsTopology service

- packages/comms/src/services/wsWorkunits.ts
> feat(comms): add WUQueryFiles endpoint to WsWorkunits service

- packages/comms/src/services/wsCloud.ts
- packages/comms/src/services/wsLogaccess.ts
- packages/comms/src/services/wsdl/ws_logaccess/v1.02/ws_logaccess.ts
> chore(comms):  Bump ws_logaccess to latest version

- packages/comms/src/services/wsLogaccess.ts
- packages/comms/src/services/wsdl/ws_logaccess/v1.02/ws_logaccess.ts
- packages/comms/utils/index.ts
> fix(comms): Wsdl-TS enums should be within namespace

- packages/tree/src/Treemap.ts
> fix: Treemap skips bring to front

- packages/common/src/Database.ts
- packages/common/src/Widget.ts
> feat:  Expose import csv/tsv

- packages/util/src/immutable.ts
> feat:  Add strict function ref comparisons for deepEquals

- packages/comms/src/services/wsdl/WsDali/v1.04/WsDali.ts
- packages/comms/utils/index.ts
> fix(comms): Wsdl-TS should pass response name into base class

- packages/comms/src/ecl/logicalFile.ts
- packages/comms/src/services/wsDFU.ts
- packages/comms/src/services/wsdl/WsDfu/v1.63/WsDfu.ts
- packages/comms/utils/index.ts
> fix(comms): Wsdl-TS enum members & values should maintain casing of ESP wsdl

- packages/comms/src/ecl/result.ts
> fix:  Debounce Result.fetchXMLSchema calls

- packages/comms/.vscode/launch.json
- packages/graph/.vscode/launch.json
- packages/preact-shim/src/index.ts
- packages/react/src/ImageChar.tsx
- packages/react/src/edge.tsx
- packages/react/src/text.tsx
- packages/react/src/vertex.tsx
- packages/react/src/vertex2.tsx
- packages/react/src/vertex3.tsx
> chore:  Improve React usage

- apps/graph2b/index.html
- demos/gallery/package-lock.json
- demos/gallery/samples/graph2/IconAnnotations.js
- demos/gallery/src-umd/config.js
- packages/graph/src/graph2/graph.ts
- packages/react/src/icon.tsx
- packages/react/src/index.ts
- packages/react/src/shape.tsx
- packages/react/src/vertex4.tsx
> feat(graph): Add vertex4.tsx

- .vscode/launch.json
- packages/comms/src/services/wsLogaccess.ts
- packages/comms/src/services/wsdl/ws_logaccess/v1.03/ws_logaccess.ts
> feat(comms):  Add support for Azure logging

- packages/comms/src/services/wsWorkunits.ts
- packages/comms/src/services/wsdl/WsWorkunits/v1.94/WsWorkunits.ts
> feat(comms):  Add support for WU Hot Spots

- demos/gallery/samples/graph2/3 Nodes Anno.js
- demos/gallery/samples/graph2/3 Nodes.js
- demos/gallery/samples/graph2/IconAnnotations.js
- packages/graph/src/graph2/graph.ts
> feat: Add anno event data to all mouse events

- demos/gallery/samples/graph2/DataGraph.js
- packages/graph/src/graph2/dataGraph.ts
- packages/graph/src/graph2/graph.ts
- packages/graph/src/test.ts
- packages/react/src/vertex3.tsx
- packages/react/src/vertex4.tsx
> fix(graph):  Add support for annotation clicks to Vertex3

- packages/comms/src/services/wsdl/WsWorkunits/v1.94/WsWorkunits.ts
- packages/comms/utils/index.ts
> fix(comms): WSDL Enum Generation

- packages/comms/src/services/wsWorkunits.ts
- packages/comms/src/services/wsdl/WsWorkunits/v1.95/WsWorkunits.ts
Signed-off-by: Jeremy Clements <Jeremy.Clements@lexisnexisrisk.com>
> chore(comms): Bump wsWorkunits to latest (v1.95)

- components/editor/package.json
- components/editor/src/codemirror.ts
- package-lock.json
- packages/deck-shim/package.json
- packages/util/package.json
> chore:  Bump codemirror and deck gl versions

- components/editor/package.json
- components/editor/src/basicSetup.ts
- components/editor/src/codemirror.ts
- package-lock.json
> fix(editor): Bump codemirror to official release

- packages/observablehq-compiler/src/compiler.ts
> fix(observablehq): Add support for local files

- package-lock.json
- packages/observable-md/package.json
- packages/observablehq-compiler/package.json
- packages/observablehq-compiler/src/compiler.md
- packages/observablehq-compiler/src/compiler.ts
- packages/observablehq-compiler/src/util.ts
> chore:  Bump observable runtime versions

- packages/chart/src/Column.ts
> GH-4008 Hide overlapping values on stacked columns

- packages/graph/src/graph2/graphReactT.ts
- tests/test-graph/src/graph.spec.ts
> fix(graph):  Fix failing tests

- packages/observable-shim/src/parse.ts
- packages/observable-shim/src/types.ts
- packages/observablehq-compiler/bin/ojscc.mjs
- packages/observablehq-compiler/src/__tests__/node.ts
- packages/observablehq-compiler/src/compiler.ts
- packages/observablehq-compiler/src/index.ts
- packages/observablehq-compiler/src/util.ts
Rename some internal methods
Extend InspectorFactory to include ID
> feat(observablehq):  Add parser offset positions

- package-lock.json
- packages/observablehq-compiler/package.json
- packages/observablehq-compiler/src/__tests__/m1.mjs
- packages/observablehq-compiler/src/__tests__/node.ts
- packages/observablehq-compiler/src/compiler.ts
- packages/observablehq-compiler/src/cst.ts
- packages/observablehq-compiler/src/util.ts
> fix(observablehq):  Allow importing of local esm files

- packages/comms/src/clienttools/eclcc.ts
> feat(comms):  Add ability to clear the client tools cached locations

- packages/observable-shim/src/types.ts
> feat: Extend ojs Node type

- packages/graph/src/graph2/layouts/graphviz.ts
- packages/graph/workers/src/graphviz.ts
- packages/graph/workers/src/graphvizOptions.ts
> feat:  Add better error handling for graphviz webworker

- packages/observablehq-compiler/src/util.ts
Expose proxy overrides to download method.
> fix:  Switch to working cors proxy

- packages/graph/src/graph2/graphT.ts
> fix:  Event.path is non-standard

- packages/comms/src/services/wsdl/WsWorkunits/v1.95/WsWorkunits.ts
specifically, add support for WUAnalyseHotspot endpoint
> chore(comms): regenerate wsWorkunits wsdl service to include latest changes

- packages/common/src/Utility.ts
> fix:  Potential prototype pollution

- packages/comms/src/services/wsLogaccess.ts
> fix(comms): separate Logaccess StartDate & EndDate request filters

- packages/comms/src/services/wsLogaccess.ts
> fix(comms): wslogaccess, do not use binaryFilter if not necessary

- .github/workflows/testPullRequest.yml
> GH-4094 Fix CI comms testing

- packages/comms/src/services/wsLogaccess.ts
> fix(comms): use RemoteLogManagerType to build GetLogs request

- packages/comms/src/ecl/query.ts
Assumes details had been passed in
> fix:  Refresh does not load details

- packages/comms/src/ecl/dfuWorkunit.ts
- packages/comms/src/services/fileSpray.ts
- packages/comms/src/services/wsdl/FileSpray/v1.25/FileSpray.ts
> chore(comms): bump version of FileSpray service

- packages/comms/src/services/wsdl/FileSpray/v1.25/FileSpray.ts
destNumParts added to SprayVariable and SprayFixed requests
(added in 9.2.0-rc2 of the HPCC platform & needed for HPCC-29306)
> chore(comms): bump FileSpray version

- packages/comms/src/ecl/workunit.ts
Format large unformatted numbers
> feat:  Add extra formatting to WUDetails

- packages/comms/src/ecl/dfuWorkunit.ts
- packages/comms/src/services/fileSpray.ts
for use in ECL Watch DFU Workunit page, methods implemented include update, abort, delete, fetchXML
> feat(comms): update, abort, delete methods for dfuWorkunit

- packages/comms/src/ecl/query.ts
> fix:  Query fails fetching schemas

- packages/comms/src/services/wsAccess.ts
- packages/comms/src/services/wsdl/ws_access/v1.17/ws_access.ts
> chore(comms): bump ws_access to version 1.17

- packages/comms/src/services/wsWorkunits.ts
This reverts commit 464d75c9e97c7a5dd615a5078129ad6490e2b421.
> Revert "fix(comms):  Some "lite" items should be defaulted to true"

- apps/angular-13/package.json
- demos/react/typescript/package.json
- package-lock.json
- package.json
- packages/comms/package.json
- packages/comms/src/connection.ts
- packages/comms/src/index.node.ts
- packages/ddl-shim/package.json
- packages/observablehq-compiler/package.json
- utils/bundle/package.json
- website/package.json
Currently failing, fix is to use offical NodeJS fetch method with undici Agent
> fix:  NodeJS v18 fetch + rejectUnauthorization = false

- utils/bundle/src/index.ts
> fix:  Exclude undici from bundles

- tests/test-util/src/types.spec.ts
> fix:  Undici change broke tests

- packages/comms/src/services/wsTopology.ts
- packages/comms/src/services/wsdl/WsTopology/v1.32/WsTopology.ts
v1.32 adds WsTopology.TpListLogFiles endpoint. Related to https://track.hpccsystems.com/browse/HPCC-29971
> chore(comms): bump wsTopology to version 1.32

- packages/comms/src/services/wsLogaccess.ts
but should map columns based on the results of GetLogAccessInfo instead
> fix(comms): GetLogsEx still using hardcoded ...KnownColumns maps

- packages/comms/src/ecl/workunit.ts
- tests/test-comms/.vscode/launch.json
- tests/test-comms/src/ecl/workunit.spec.ts
> fix:  isWUComplete fails for compile + Attach

- packages/comms/src/services/wsLogaccess.ts
- packages/comms/src/services/wsdl/ws_logaccess/v1.05/ws_logaccess.ts
> chore(comms): bump version of ws_logaccess service

- packages/comms/src/ecl/workunit.ts
> feat(comms): allow the WU refresh function to accept optional request

- packages/comms/src/ecl/workunit.ts
- packages/comms/src/services/wsWorkunits.ts
- tests/test-comms/.vscode/launch.json
- tests/test-comms/src/ecl/workunit.spec.ts
> feat: Add Protect & Unprotect functions to Visualization WU Class

- packages/phosphor/src/DockPanel.ts
> feat:  Add padding property to DockPanel.addWidget

- package-lock.json
- package.json
- packages/api/package.json
- packages/chart/package.json
- packages/common/package.json
- packages/form/package.json
- packages/map-deck/package.json
- packages/map/package.json
> chore: Bump d3-color version (security)

- packages/comms/src/services/fileSpray.ts
> feat(comms): add a States enum to FileSpray service

- apps/react-next/README.md
> fix:  Doc generation failing

- packages/comms/src/ecl/workunit.ts
> fix:  grouped properties had "any" type.

- packages/comms/src/ecl/query.ts
- packages/comms/src/ecl/queryGraph.ts
- packages/comms/src/ecl/workunit.ts
> feat:  Add accumulated stats to Query Metrics

- packages/observable-md/README.md
> chore:  Deprecate @hpcc-js/observable-md

- packages/comms/src/services/wsWorkunits.ts
- packages/comms/src/services/wsdl/WsWorkunits/v1.98/WsWorkunits.ts
> chore(comms): bump WsWorkunits to version 1.98

- packages/comms/src/ecl/workunit.ts
- packages/comms/src/services/wsWorkunits.ts
extended version of publish(...) using the request definition in WsWorkunits v1.98
> feat(comms): add publishEx function to workunit

- packages/chart/src/Column.ts
- packages/chart/src/test.ts
> fix:  Don't relocate text in "Stacked" mode.

- packages/comms/src/services/fileSpray.ts
- packages/comms/src/services/wsdl/FileSpray/v1.26/FileSpray.ts
> chore(comms): bump FileSpray to version 1.26

- packages/comms/src/ecl/workunit.ts
- packages/comms/src/services/wsdl/WsWorkunits/v2/WsWorkunits.ts
- packages/comms/utils/index.ts
> fix:  Request string arrays had incorrect nesting

- packages/codemirror-shim/rollup.config.js
- packages/codemirror-shim/src/index.ts
- packages/codemirror/src/Editor.ts
- packages/codemirror/src/SQLEditor.ts
- packages/codemirror/src/index.ts
> feat:  Add SQL support to codemirror

- packages/comms/src/services/wsdl/ws_access/v1.17/ws_access.ts
corrects some of the unnecessarily expanded types
> fix(comms): regenerate ws_access service with most recent changes

- packages/comms/src/ecl/workunit.ts
> feat: Add additional skew information

- packages/timeline/src/ReactAxisGantt.ts
- packages/timeline/src/ReactAxisGanttSeries.ts
- packages/timeline/src/ReactGantt.ts
> feat:  Expose Gantt selection method

- packages/chart/src/Pie.ts
- packages/chart/src/__tests__/index.ts
- packages/chart/src/__tests__/pie.ts
> feat:  Add "sortByValue" PP to Pie Chart

- packages/comms/src/services/wsDali.ts
- packages/comms/src/services/wsdl/WsDali/v1.07/WsDali.ts
Update to WsDali Service in comms layer.
> Fixes #4231 Update WsDali Comms Layer

- packages/comms/src/ecl/logicalFile.ts
handles ESP exceptions thrown when a file has been deleted
> fix(comms): add exception handling to logicalFile fetchInfo

- demos/gallery/package.json
- package-lock.json
> fix:  Gallery tests failing

- .github/workflows/release-please.yml
> fix: Publish step failing

- package-lock.json
- packages/html/esbuild.js
- packages/html/index.html
- packages/html/package.json
- packages/html/src/VizComponent.tsx
- packages/html/src/VizInstance.tsx
> fix: Remove preact references from html

- package-lock.json
- packages/comms/package.json
- packages/ddl-shim/package.json
Lerna issue on windows (8.1.9)
Missing dependency with comms
> fix: Windows build and test failing

- packages/dgrid2/src/reactTable.tsx
> fix: dgrid2 producing tsc errors

- .github/workflows/release-please.yml
> fix: Automated release failing

- packages/react/src/text.tsx
> feat:  Drop preact-shim and bump versions

- packages/dgrid/index.html
- packages/dgrid/src/RowFormatter.ts
- packages/eclwatch/.vscode/launch.json
- packages/eclwatch/index.html
- packages/eclwatch/package.json
> fix: Nested datasets not rendering correctly

- packages/comms/src/espConnection.ts
- packages/comms/src/services/wsWorkunits.ts
> feat: Allow fetch exceptions to propogate up the stack

- packages/graph/package.json
- packages/graph/tsconfig.json
- packages/graph/vite.config.ts
> fix: Prevent React from being included in the bundle

- packages/comms/src/ecl/dfuWorkunit.ts
- packages/comms/src/ecl/logicalFile.ts
- packages/comms/src/ecl/workunit.ts
> fix(comms): add more info to unhelpful exception logging

- packages/comms/src/clienttools/eclcc.ts
> fix: Add try/catch for xml parsing

- packages/comms/src/services/wsDali.ts
> feat(comms): add Export function to WsDali service

- packages/comms/src/services/wsdl/ws_logaccess/v1.08/ws_logaccess.ts
> fix(comms): fix a type in WsLogaccess GetHealthReportResponse

- packages/composite/index-preview.html
- packages/composite/index.html
- packages/composite/tests/composite.browser.spec.ts
- packages/dgrid/tests/dgrid.browser.spec.ts
- packages/dgrid/tests/index.ts
- packages/layout/index-preview.html
- packages/layout/index.html
- packages/layout/package.json
- packages/layout/src/ChartPanel.ts
- packages/layout/tests/layout.browser.spec.ts
- packages/map/index-preview.html
- packages/map/index.html
- packages/map/tests/map.browser.spec.ts
- packages/other/index-preview.html
- packages/other/index.html
- packages/other/tests/other.browser.spec.ts
- packages/timeline/index-preview.html
- packages/timeline/index.html
- packages/timeline/tests/timeline.browser.spec.ts
> fix: Switch to dgrid for layouts

- packages/comms/package.json
> fix: Add missing dependency

- packages/comms/package.json
- packages/map/package.json
comms - wrong file extension
maps - missing files item
> fix: Resolve export issues

- package-lock.json
- package.json
- packages/esbuild-plugins/package.json
> chore: switch to nextgen vite
